<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseSharedCompilation>false</UseSharedCompilation>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="TestSuite.VisualSplitter.cs" Condition="!Exists('..\..\src\Clickra.Core\Processors\FileProcessing\VisualSplitModel.cs')" />
    <ProjectReference Include="..\..\src\Clickra.Core\Clickra.Core.csproj" />
  </ItemGroup>

</Project>
