using System;
using System.Collections.Generic;

namespace Clickra.Core
{
    public static class Localization
    {
        private static readonly Dictionary<string, Dictionary<string, string>> Translations = new(StringComparer.OrdinalIgnoreCase)
        {
            ["zh-TW"] = new(StringComparer.OrdinalIgnoreCase)
            {
                ["tab_status"] = "狀態",
                ["tab_history"] = "歷史",
                ["tab_settings"] = "設定",
                ["setting_silent_title"] = "背景靜默轉檔",
                ["setting_silent_desc"] = "在右鍵選單點擊時直接於背景處理，不顯示進度視窗",
                ["setting_notify_title"] = "顯示轉換通知",
                ["setting_notify_desc"] = "作業完成或失敗後，於系統右下角彈出 Windows Toast 通知",
                ["setting_output_title"] = "預設輸出路徑",
                ["setting_output_desc"] = "選擇轉換後 PDF 與圖片預設的儲存位置",
                ["setting_output_same_as_source"] = "與來源相同",
                ["setting_output_desktop"] = "桌面",
                ["setting_output_downloads"] = "下載",
                ["setting_output_custom"] = "自訂...",
                ["setting_output_selected_path"] = "已選取路徑",
                ["setting_output_browse_title"] = "選擇預設輸出資料夾",
                ["overview_engine_status"] = "轉換引擎狀態",
                ["overview_stats"] = "轉換統計",
                ["overview_stat_total"] = "總轉換次數",
                ["overview_stat_success"] = "成功次數",
                ["overview_stat_failed"] = "失敗次數",
                ["history_clear"] = "清除紀錄",
                ["history_clear_confirm"] = "您確定要清除所有的轉換歷史紀錄嗎？",
                ["history_empty"] = "尚無任何轉換紀錄。",
                ["status_pending"] = "等待中",
                ["status_converting"] = "轉換中",
                ["status_success"] = "成功",
                ["status_failed"] = "失敗",
                ["label_files"] = "個檔案",
                ["setting_lang_title"] = "介面語言",
                ["setting_lang_desc"] = "選擇 Dashboard 的顯示語言",
                ["search_lang_placeholder"] = "搜尋語言 / Search...",
                ["engine_pdf"] = "PDF 處理核心 (PDF Engine)",
                ["engine_ppt"] = "PowerPoint 轉換器 (PowerPoint)",
                ["engine_word"] = "Word 轉換器 (Word)",
                ["engine_ready"] = "已就緒",
                ["engine_office_not_installed"] = "Office 未安裝",
                ["overview_tip"] = "提示：直接在檔案總管選取檔案，右鍵即可呼叫 Clickra 選單進行轉換。",
                ["cmd_word_to_pdf"] = "Word → PDF",
                ["cmd_ppt_to_pdf"] = "PPT → PDF",
                ["cmd_merge_pdf"] = "合併 PDF",
                ["cmd_img_to_pdf"] = "圖片 → PDF",
                ["cmd_merge_img"] = "圖片合併",
                ["cmd_stitch_img"] = "圖片拼接",
                ["tab_convert"] = "轉檔",
                ["convert_drag_drop_hint"] = "拖曳檔案至此，或點擊此處選取檔案",
                ["convert_drag_drop_sub"] = "支援 Word, PPT, PDF 及多種圖片格式",
                ["convert_selected_count"] = "已選取 {0} 個檔案",
                ["convert_clear"] = "清除",
                ["convert_start"] = "開始轉檔",
                ["convert_err_min_files"] = "此功能至少需要 {0} 個檔案！",
                ["convert_err_invalid_ext"] = "檔案格式不符，請重新選取！",
                ["tab_about"] = "關於",
                ["about_desc_title"] = "專案說明",
                ["about_desc_body"] = "Clickra 是一款專為 Windows 11 量身打造的極致輕量、現代化右鍵轉檔工具。\n底層採用先進的 C# NativeAOT 技術，擺脫笨重的執行環境，實現小於 0.01 秒的瞬時啟動與免安裝極致體驗，與系統完美融為一體。",
                ["about_collab_title"] = "協作開發與原始碼",
                ["about_collab_body"] = "本專案以 Apache 2.0 協議完全開源！我們熱烈歡迎各位開發者加入，共同改善與擴充功能。\n您可以透過 GitHub 提交 Pull Request、回報 Issue，一起打造更實用的 Windows 生態系工具。",
                ["about_diag_title"] = "診斷與回報說明",
                ["about_diag_body"] = "遇到轉檔失敗或異常嗎？我們為您簡化了回報流程！\n點擊下方按鈕將一鍵開啟 Gmail 線上郵件撰寫，並同步在檔案總管為您選取好日誌檔「history.log」，您只需將該檔案拖曳至郵件中即可快速傳送診斷資訊。",
                ["about_btn_open_data_dir"] = "檢視日誌資料夾",
                ["about_btn_github"] = "GitHub 專案",
                ["about_btn_gmail"] = "Gmail 回報",
                ["history_detail_inputs"] = "輸入路徑",
                ["history_detail_outputs"] = "輸出路徑",
                ["history_detail_time"] = "轉換時間",
                ["history_detail_elapsed"] = "執行耗時",
                ["progress_cancel_confirm"] = "您確定要取消目前的轉換作業嗎？",
                ["history_detail_error"] = "錯誤訊息",
                ["error_user_aborted"] = "取消",
                ["progress_tray_hint"] = "按 — 或工作列圖示可縮至系統匣繼續執行",
                ["progress_background"] = "縮小至系統匣"
            },
            ["zh-CN"] = new(StringComparer.OrdinalIgnoreCase)
            {
                ["tab_status"] = "状态",
                ["tab_history"] = "历史",
                ["tab_settings"] = "设置",
                ["setting_silent_title"] = "背景静默转档",
                ["setting_silent_desc"] = "在右键菜单点击时直接于背景处理，不显示进度窗口",
                ["setting_notify_title"] = "显示转换通知",
                ["setting_notify_desc"] = "作业完成或失败后，于系统右下角弹出 Windows Toast 通知",
                ["setting_output_title"] = "默认输出路径",
                ["setting_output_desc"] = "选择转换后 PDF 与图片默认的存储位置",
                ["setting_output_same_as_source"] = "与来源相同",
                ["setting_output_desktop"] = "桌面",
                ["setting_output_downloads"] = "下载",
                ["setting_output_custom"] = "自定义...",
                ["setting_output_selected_path"] = "已选择路径",
                ["setting_output_browse_title"] = "选择默认输出文件夹",
                ["overview_engine_status"] = "转换引擎状态",
                ["overview_stats"] = "转换统计",
                ["overview_stat_total"] = "总转换次数",
                ["overview_stat_success"] = "成功次数",
                ["overview_stat_failed"] = "失败次数",
                ["history_clear"] = "清除记录",
                ["history_clear_confirm"] = "您确定要清除所有的转换历史记录吗？",
                ["history_empty"] = "尚无任何转换记录。",
                ["status_pending"] = "等待中",
                ["status_converting"] = "转换中",
                ["status_success"] = "成功",
                ["status_failed"] = "失败",
                ["label_files"] = "个文件",
                ["setting_lang_title"] = "界面语言",
                ["setting_lang_desc"] = "选择 Dashboard 的显示语言",
                ["search_lang_placeholder"] = "搜索语言...",
                ["engine_pdf"] = "PDF 处理核心 (PDF Engine)",
                ["engine_ppt"] = "PowerPoint 转换器 (PowerPoint)",
                ["engine_word"] = "Word 转换器 (Word)",
                ["engine_ready"] = "已就绪",
                ["engine_office_not_installed"] = "Office 未安装",
                ["overview_tip"] = "提示：直接在文件资源管理器中选择文件，右键即可呼叫 Clickra 菜单进行转换。",
                ["cmd_word_to_pdf"] = "Word → PDF",
                ["cmd_ppt_to_pdf"] = "PPT → PDF",
                ["cmd_merge_pdf"] = "合并 PDF",
                ["cmd_img_to_pdf"] = "图片 → PDF",
                ["cmd_merge_img"] = "图片合并",
                ["cmd_stitch_img"] = "图片拼接",
                ["tab_convert"] = "转档",
                ["convert_drag_drop_hint"] = "拖拽文件至此，或点击此处选择文件",
                ["convert_drag_drop_sub"] = "支持 Word, PPT, PDF 及多种图片格式",
                ["convert_selected_count"] = "已选择 {0} 个文件",
                ["convert_clear"] = "清除",
                ["convert_start"] = "开始转档",
                ["convert_err_min_files"] = "此功能至少需要 {0} 个文件！",
                ["convert_err_invalid_ext"] = "文件格式不符，请重新选择！",
                ["tab_about"] = "关于",
                ["about_desc_title"] = "项目说明",
                ["about_desc_body"] = "Clickra 是一款专为 Windows 11 量身打造的极致轻量、现代化右键转档工具。\n底层采用先进的 C# NativeAOT 技术，摆脱臃肿的运行环境，实现小于 0.01 秒的瞬时启动与免安装极致体验，与系统完美融为一体。",
                ["about_collab_title"] = "协作开发与源码",
                ["about_collab_body"] = "本项目以 Apache 2.0 协议完全开源！我们热烈欢迎各位开发者加入，共同改善与扩充功能。\n您可以通过 GitHub 提交 Pull Request、反馈 Issue，一起打造更实用的 Windows 生态系工具。",
                ["about_diag_title"] = "诊断与反馈说明",
                ["about_diag_body"] = "遇到转档失败或异常吗？我们为您简化了反馈流程！\n点击下方按钮将一键开启 Gmail 网页版邮件撰写，并同步在文件资源管理器中为您选好日志「history.log」，您只需将该文件拖拽至邮件中即可快速发送诊断信息。",
                ["about_btn_open_data_dir"] = "查看日志文件夹",
                ["about_btn_github"] = "GitHub 项目",
                ["about_btn_gmail"] = "Gmail 反馈",
                ["history_detail_inputs"] = "输入路径",
                ["history_detail_outputs"] = "输出路径",
                ["history_detail_time"] = "转换时间",
                ["history_detail_elapsed"] = "执行耗时",
                ["progress_cancel_confirm"] = "您确定要取消当前的转换作业吗？",
                ["history_detail_error"] = "错误信息",
                ["error_user_aborted"] = "取消",
                ["progress_tray_hint"] = "按 — 或任务栏图标可最小化到系统托盘继续运行",
                ["progress_background"] = "最小化到系统托盘"
            },
            ["en-US"] = new(StringComparer.OrdinalIgnoreCase)
            {
                ["tab_status"] = "Status",
                ["tab_history"] = "History",
                ["tab_settings"] = "Settings",
                ["setting_silent_title"] = "Silent Mode",
                ["setting_silent_desc"] = "Process in background without showing progress window",
                ["setting_notify_title"] = "Show Notifications",
                ["setting_notify_desc"] = "Show Toast notification when conversion completes/fails",
                ["setting_output_title"] = "Default Output Path",
                ["setting_output_desc"] = "Select the default save location for converted files",
                ["setting_output_same_as_source"] = "Same as source",
                ["setting_output_desktop"] = "Desktop",
                ["setting_output_downloads"] = "Downloads",
                ["setting_output_custom"] = "Custom...",
                ["setting_output_selected_path"] = "Selected path",
                ["setting_output_browse_title"] = "Select Default Output Folder",
                ["overview_engine_status"] = "Conversion Engine Status",
                ["overview_stats"] = "Conversion Stats",
                ["overview_stat_total"] = "Total Conversions",
                ["overview_stat_success"] = "Successful",
                ["overview_stat_failed"] = "Failed",
                ["history_clear"] = "Clear History",
                ["history_clear_confirm"] = "Are you sure you want to clear all history?",
                ["history_empty"] = "No conversion history.",
                ["status_pending"] = "Pending",
                ["status_converting"] = "Converting",
                ["status_success"] = "Success",
                ["status_failed"] = "Failed",
                ["label_files"] = "files",
                ["setting_lang_title"] = "Interface Language",
                ["setting_lang_desc"] = "Select the display language for the Dashboard",
                ["search_lang_placeholder"] = "Search language...",
                ["engine_pdf"] = "PDF Processing Engine",
                ["engine_ppt"] = "PowerPoint Converter",
                ["engine_word"] = "Word Converter",
                ["engine_ready"] = "Ready",
                ["engine_office_not_installed"] = "Office Not Installed",
                ["overview_tip"] = "Tip: Select files in File Explorer, right-click, and select Clickra to convert.",
                ["cmd_word_to_pdf"] = "Word → PDF",
                ["cmd_ppt_to_pdf"] = "PPT → PDF",
                ["cmd_merge_pdf"] = "Merge PDF",
                ["cmd_img_to_pdf"] = "Image → PDF",
                ["cmd_merge_img"] = "Merge Images",
                ["cmd_stitch_img"] = "Stitch Images",
                ["tab_convert"] = "Convert",
                ["convert_drag_drop_hint"] = "Drag files here, or click to browse",
                ["convert_drag_drop_sub"] = "Supports Word, PPT, PDF, and image files",
                ["convert_selected_count"] = "{0} files selected",
                ["convert_clear"] = "Clear",
                ["convert_start"] = "Start Conversion",
                ["convert_err_min_files"] = "This action requires at least {0} files!",
                ["convert_err_invalid_ext"] = "Invalid file extensions detected!",
                ["tab_about"] = "About",
                ["about_desc_title"] = "About Project",
                ["about_desc_body"] = "Clickra is a premium, ultra-lightweight modern context menu utility designed for Windows 11.\nBuilt with C# NativeAOT, it skips all runtime overhead to deliver sub-10ms instantaneous startup and a zero-dependency user experience that feels like a native OS feature.",
                ["about_collab_title"] = "Collaboration & Source",
                ["about_collab_body"] = "This project is fully open-source under the Apache 2.0 license! We love community contributions.\nVisit our GitHub repository to submit Pull Requests, report issues, or collaborate on building better tools for Windows.",
                ["about_diag_title"] = "Diagnostics & Support",
                ["about_diag_body"] = "Encountered a conversion issue? We've streamlined the feedback process!\nClick below to open Gmail Web Composer and highlight 'history.log' in File Explorer. Simply drag the highlighted file into Gmail to send us the diagnostic details.",
                ["about_btn_open_data_dir"] = "Open Log Folder",
                ["about_btn_github"] = "View on GitHub",
                ["about_btn_gmail"] = "Gmail Diagnostics",
                ["history_detail_inputs"] = "Input Paths",
                ["history_detail_outputs"] = "Output Path",
                ["history_detail_time"] = "Conversion Time",
                ["history_detail_elapsed"] = "Elapsed Time",
                ["progress_cancel_confirm"] = "Are you sure you want to cancel the current conversion?",
                ["history_detail_error"] = "Error Message",
                ["error_user_aborted"] = "Canceled",
                ["progress_tray_hint"] = "Click — or taskbar icon to minimize to tray",
                ["progress_background"] = "Minimize to System Tray"
            },
            ["ja-JP"] = new(StringComparer.OrdinalIgnoreCase)
            {
                ["tab_status"] = "状態",
                ["tab_history"] = "履歴",
                ["tab_settings"] = "設定",
                ["tab_convert"] = "変換",
                ["tab_about"] = "紹介",
                ["setting_silent_title"] = "サイレントモード",
                ["setting_silent_desc"] = "進行状況ウィンドウを表示せず、バックグラウンドで処理します",
                ["setting_notify_title"] = "変換通知を表示",
                ["setting_notify_desc"] = "完了または失敗時に、Windows トースト通知を表示します",
                ["setting_output_title"] = "既定の出力先",
                ["setting_output_desc"] = "変換後のファイルの保存先を選択します",
                ["setting_output_same_as_source"] = "ソースと同じ",
                ["setting_output_desktop"] = "デスクトップ",
                ["setting_output_downloads"] = "ダウンロード",
                ["setting_output_custom"] = "カスタム...",
                ["setting_output_selected_path"] = "選択されたパス",
                ["setting_output_browse_title"] = "既定の出力フォルダを選択",
                ["overview_engine_status"] = "変換エンジンの状態",
                ["overview_stats"] = "統計情報",
                ["overview_stat_total"] = "総変換回数",
                ["overview_stat_success"] = "成功回数",
                ["overview_stat_failed"] = "失敗回数",
                ["history_clear"] = "履歴をクリア",
                ["history_clear_confirm"] = "すべての変換履歴をクリアしてもよろしいですか？",
                ["history_empty"] = "変換履歴はありません。",
                ["status_pending"] = "待機中",
                ["status_converting"] = "変換中",
                ["status_success"] = "成功",
                ["status_failed"] = "失敗",
                ["label_files"] = "個のファイル",
                ["setting_lang_title"] = "表示言語",
                ["setting_lang_desc"] = "Dashboard の表示言語を選択します",
                ["search_lang_placeholder"] = "言語を検索...",
                ["engine_pdf"] = "PDF 処理エンジン",
                ["engine_ppt"] = "PowerPoint 変換器",
                ["engine_word"] = "Word 変換器",
                ["engine_ready"] = "準備完了",
                ["engine_office_not_installed"] = "Office 未インストール",
                ["overview_tip"] = "ヒント：エクスプローラーでファイルを選択し、右クリックして Clickra から変換します。",
                ["cmd_word_to_pdf"] = "Word → PDF",
                ["cmd_ppt_to_pdf"] = "PPT → PDF",
                ["cmd_merge_pdf"] = "PDF 結合",
                ["cmd_img_to_pdf"] = "画像 → PDF",
                ["cmd_merge_img"] = "画像結合",
                ["cmd_stitch_img"] = "画像結合 (縦/横)",
                ["convert_drag_drop_hint"] = "ここにファイルをドラッグするか、クリックして選択",
                ["convert_drag_drop_sub"] = "Word、PPT、PDF、および画像ファイルをサポート",
                ["convert_selected_count"] = "{0} 個のファイルが選択されました",
                ["convert_clear"] = "クリア",
                ["convert_start"] = "変換開始",
                ["convert_err_min_files"] = "この機能には少なくとも {0} 個のファイルが必要です！",
                ["convert_err_invalid_ext"] = "無効なファイル形式が含まれています！",
                ["about_desc_title"] = "プロジェクトについて",
                ["about_desc_body"] = "Clickra は、Windows 11 のために設計された極めて軽量でモダンな右鍵コンテキストメニュー変換ツールです。\nC# NativeAOT 技術を採用し、不要なランタイムを排除することで、0.01秒未満の瞬間起動と完全なスタンドアロン動作を実現しました。",
                ["about_collab_title"] = "コラボレーションとソースコード",
                ["about_collab_body"] = "本プロジェクトは Apache 2.0 ライセンスの下で完全にオープンソース化されています！\nGitHub での Pull Request や Issue の報告を通じて、Windows ユーザーのための優れたツール開発にぜひご協力ください。",
                ["about_diag_title"] = "診断とサポート",
                ["about_diag_body"] = "変換エラーや不具合が発生しましたか？フィードバックの手順を劇的に簡略化しました！\nボタンをクリックすると、Gmail 作成画面が開き、エクスプローラーでログファイル「history.log」が自動選択されます。ファイルをそのままドラッグ＆ドロップして送信してください。",
                ["about_btn_open_data_dir"] = "ログフォルダを開く",
                ["about_btn_github"] = "GitHub で表示",
                ["about_btn_gmail"] = "Gmail でフィードバック",
                ["history_detail_inputs"] = "入力パス",
                ["history_detail_outputs"] = "出力パス",
                ["history_detail_time"] = "変換日時",
                ["history_detail_elapsed"] = "処理時間",
                ["progress_cancel_confirm"] = "現在の変換作業をキャンセルしてもよろしいですか？",
                ["history_detail_error"] = "エラーメッセージ",
                ["error_user_aborted"] = "キャンセル",
                ["progress_tray_hint"] = "— またはタスクバーアイコンでトレイに最小化できます",
                ["progress_background"] = "システムトレイに最小化"
            },
            ["ko-KR"] = new(StringComparer.OrdinalIgnoreCase)
            {
                ["tab_status"] = "상태",
                ["tab_history"] = "기록",
                ["tab_settings"] = "설정",
                ["tab_convert"] = "변환",
                ["tab_about"] = "정보",
                ["setting_silent_title"] = "자동 변환 모드",
                ["setting_silent_desc"] = "진행 창을 표시하지 않고 백그라운드에서 바로 처리합니다",
                ["setting_notify_title"] = "변환 알림 표시",
                ["setting_notify_desc"] = "완료 또는 실패 시 Windows 토스트 알림을 표시합니다",
                ["setting_output_title"] = "기본 출력 경로",
                ["setting_output_desc"] = "변환된 파일의 기본 저장 위치를 선택합니다",
                ["setting_output_same_as_source"] = "원본과 동일",
                ["setting_output_desktop"] = "바탕 화면",
                ["setting_output_downloads"] = "다운로드",
                ["setting_output_custom"] = "사용자 정의...",
                ["setting_output_selected_path"] = "선택한 경로",
                ["setting_output_browse_title"] = "기본 출력 폴더 선택",
                ["overview_engine_status"] = "변환 엔진 상태",
                ["overview_stats"] = "오늘의 통계",
                ["overview_stat_total"] = "총 변환 횟수",
                ["overview_stat_success"] = "성공 횟수",
                ["overview_stat_failed"] = "실패 횟수",
                ["history_clear"] = "기록 삭제",
                ["history_clear_confirm"] = "모든 변환 기록을 삭제하시겠습니까?",
                ["history_empty"] = "변환 기록이 없습니다.",
                ["status_pending"] = "대기 중",
                ["status_converting"] = "변환 중",
                ["status_success"] = "성공",
                ["status_failed"] = "실패",
                ["label_files"] = "개의 파일",
                ["setting_lang_title"] = "표시 언어",
                ["setting_lang_desc"] = "Dashboard 표시 언어를 선택합니다",
                ["search_lang_placeholder"] = "언어 검색...",
                ["engine_pdf"] = "PDF 처리 엔진",
                ["engine_ppt"] = "PowerPoint 변환기",
                ["engine_word"] = "Word 변환기",
                ["engine_ready"] = "준비 완료",
                ["engine_office_not_installed"] = "Office 미설치",
                ["overview_tip"] = "팁: 파일 탐색기에서 파일을 선택하고 마우스 오른쪽 버튼을 클릭하여 Clickra로 변환하세요.",
                ["cmd_word_to_pdf"] = "Word → PDF",
                ["cmd_ppt_to_pdf"] = "PPT → PDF",
                ["cmd_merge_pdf"] = "PDF 병합",
                ["cmd_img_to_pdf"] = "이미지 → PDF",
                ["cmd_merge_img"] = "이미지 병합",
                ["cmd_stitch_img"] = "이미지 이어붙이기",
                ["tab_convert"] = "변환",
                ["convert_drag_drop_hint"] = "여기에 파일을 끌어다 놓거나 클릭하여 선택",
                ["convert_drag_drop_sub"] = "Word, PPT, PDF 및 이미지 파일 지원",
                ["convert_selected_count"] = "{0}개의 파일이 선택됨",
                ["convert_clear"] = "지우기",
                ["convert_start"] = "변환 시작",
                ["convert_err_min_files"] = "이 작업은 최소 {0}개의 파일이 필요합니다!",
                ["convert_err_invalid_ext"] = "잘못된 파일 확장자가 감지되었습니다!",
                ["tab_about"] = "정보",
                ["about_desc_title"] = "프로젝트 정보",
                ["about_desc_body"] = "Clickra는 Windows 11을 위해 특별히 설계된 초경량 현대식 마우스 오른쪽 버튼 변환 도구입니다.\n최첨단 C# NativeAOT 기술을 적용하여 불필요한 런타임을 배제하고 0.01초 미만의 즉각적인 실행 속도와 무설치 작동을 제공합니다.",
                ["about_collab_title"] = "협업 및 소스 코드",
                ["about_collab_body"] = "이 프로젝트는 Apache 2.0 라이선스 하에 완전한 오픈 소스로 제공됩니다!\nGitHub 리포지토리에서 Pull Request 제출, Issue 등록을 통해 더 편리한 Windows 환경을 만드는 데 동참해 주세요.",
                ["about_diag_title"] = "진단 및 지원",
                ["about_diag_body"] = "변환 중 문제가 발생하면 아래 버튼을 누르면 Gmail 작성 창이 열리고 탐색기에서 로그 파일「history.log」가 자동 선택됩니다. 파일을 메일에 드래그 앤 드롭하여 손쉽게 진단 정보를 보내주세요.",
                ["about_btn_open_data_dir"] = "로그 폴더 열기",
                ["about_btn_github"] = "GitHub 리포지토리",
                ["about_btn_gmail"] = "Gmail 피드백",
                ["history_detail_inputs"] = "입력 경로",
                ["history_detail_outputs"] = "출력 경로",
                ["history_detail_time"] = "변환 시간",
                ["history_detail_elapsed"] = "소요 시간",
                ["progress_cancel_confirm"] = "현재 변환 작업을 취소하시겠습니까?",
                ["history_detail_error"] = "오류 메시지",
                ["error_user_aborted"] = "취소됨",
                ["progress_tray_hint"] = "— 또는 작업 표시줄 아이콘을 클릭하면 트레이로 최소화됩니다",
                ["progress_background"] = "시스템 트레이로 최소화"
            }
        };

        public static string NormalizeLanguageCode(string langCode)
        {
            if (string.IsNullOrEmpty(langCode))
            {
                langCode = System.Globalization.CultureInfo.CurrentUICulture.Name;
            }

            if (langCode.StartsWith("en", StringComparison.OrdinalIgnoreCase)) return "en-US";
            if (langCode.Equals("zh-CN", StringComparison.OrdinalIgnoreCase)) return "zh-CN";
            if (langCode.StartsWith("ja", StringComparison.OrdinalIgnoreCase)) return "ja-JP";
            if (langCode.StartsWith("ko", StringComparison.OrdinalIgnoreCase)) return "ko-KR";
            if (langCode.StartsWith("zh", StringComparison.OrdinalIgnoreCase)) return "zh-TW";

            return "zh-TW";
        }

        public static string T(string key, string langCode)
        {
            string targetKey = NormalizeLanguageCode(langCode);

            // Try looking up the logical ID in the target language
            if (Translations.TryGetValue(targetKey, out var dict) && dict.TryGetValue(key, out var translated))
            {
                return translated;
            }

            // Fallback: If not found in target language, try Traditional Chinese (zh-TW)
            if (targetKey != "zh-TW" && Translations.TryGetValue("zh-TW", out var twDict) && twDict.TryGetValue(key, out var twTranslated))
            {
                return twTranslated;
            }

            // Fallback: If not found anywhere, return the key as-is
            return key;
        }
    }
}
