<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ApplicationIcon>../resources/app.ico</ApplicationIcon>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Authors>Youchen Jiang</Authors>
    <Description>Instant Windows Context Menu Utility Suite</Description>
    <DebugType>none</DebugType>
    <PublishAot>true</PublishAot>
    <OptimizationPreference>Size</OptimizationPreference>
    <CopyOutputSymbolsToPublishDirectory>false</CopyOutputSymbolsToPublishDirectory>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PdfSharp" Version="6.2.4" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <TrimmerRootAssembly Include="UglyToad.PdfPig" />
    <TrimmerRootAssembly Include="UglyToad.PdfPig.Core" />
    <TrimmerRootAssembly Include="UglyToad.PdfPig.Fonts" />
    <TrimmerRootAssembly Include="UglyToad.PdfPig.Package" />
    <TrimmerRootAssembly Include="UglyToad.PdfPig.Tokenization" />
    <TrimmerRootAssembly Include="UglyToad.PdfPig.Tokens" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Clickra.Core\Clickra.Core.csproj" />
  </ItemGroup>

</Project>
