import sys
import os
import json
import re
import subprocess
import shutil
import copy
import time
import random

if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8')
if hasattr(sys.stderr, 'reconfigure'):
    sys.stderr.reconfigure(encoding='utf-8')

MAX_RETRIES = 12
RETRY_BASE_DELAY = 30
RETRY_JITTER = 5
MSSTORE_ERROR_MARKER = "💥 Error!"  # Sentinel string emitted by msstore-cli on failure

# Mapping from listing markdown file suffix to Microsoft Store language locale code
LOCALE_MAP = {
    'ZH': 'zh-tw',       # StoreListing_ZH.md -> zh-tw
    'ZH-CN': 'zh-cn',    # StoreListing_ZH-CN.md -> zh-cn
    'EN': 'en',          # StoreListing_EN.md -> en
    'JA': 'ja-jp',       # StoreListing_JA.md -> ja-jp
    'KO': 'ko-kr'        # StoreListing_KO.md -> ko-kr
}

def process_string_char(char, escaped, output):
    """
    Handles a character inside a string literal.
    Returns: (new_escaped_state, in_string_still)
    """
    if escaped:
        if char not in ['\r', '\n']:
            output.append(char)
        return False, True
        
    if char == '\\':
        output.append(char)
        return True, True
    elif char == '"':
        output.append(char)
        return False, False
    elif char in ['\r', '\n']:
        last_chars = "".join(output[-5:])
        if not re.search(r'\\u[0-9a-fA-F]{0,3}$', last_chars):
            output.append('\\n')
    else:
        output.append(char)
        
    return False, True

def sanitize_json_content(content):
    r"""
    Cleans up malformed JSON generated by msstore-cli.
    Works around two bugs in msstore-cli's output formatting:
    1. Line wrapping at 80 characters inside string literals.
    2. Splitting unicode escape sequences (\uXXXX) across newlines.
    """
    content = content.replace('\r\n', '\n')
    output = []
    in_string = False
    escaped = False
    
    for char in content:
        if not in_string:
            if char == '"':
                in_string = True
            output.append(char)
        else:
            escaped, in_string = process_string_char(char, escaped, output)
        
    return "".join(output)

def match_section_name(header):
    if 'description' in header:
        return 'shortDescription' if 'short' in header else 'description'
    if 'new' in header or 'release' in header:
        return 'releaseNotes'
    if 'features' in header:
        return 'features'
    if 'keywords' in header:
        return 'keywords'
    return None

def parse_markdown_listing(file_path):
    """
    Parses a StoreListing markdown file into a dictionary of fields.
    """
    if not os.path.exists(file_path):
        print(f"Warning: Listing file {file_path} not found. Skipping.")
        return None

    print(f"Parsing listing file: {file_path}")
    with open(file_path, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    parsed = {
        'description': '',
        'releaseNotes': '',
        'features': [],
        'shortDescription': '',
        'keywords': []
    }

    current_section = None
    section_content = []

    for line in lines:
        stripped = line.strip()
        
        # Check for section header
        if line.startswith('## '):
            # Save previous section
            if current_section:
                save_section(parsed, current_section, section_content)
            
            # Identify new section by English keywords
            header = stripped[3:].lower()
            current_section = match_section_name(header)
            section_content = []
        else:
            if current_section:
                section_content.append(line)

    # Save last section
    if current_section:
        save_section(parsed, current_section, section_content)

    return parsed

def save_section(parsed, section, content_lines):
    content = "".join(content_lines).strip()
    content = re.sub(r'\n-+\n', '\n', content)
    
    if section in ['features', 'keywords']:
        items = []
        for line in content.split('\n'):
            line = line.strip()
            # Skip empty lines or notes/explanations in parentheses (e.g., *(Max 7)* or *(最多 7 個)*)
            if not line or ('(' in line and ')' in line) or ('（' in line and '）' in line):
                continue
            if line.startswith('-'):
                items.append(line[1:].strip())
            elif line.startswith('*'):
                items.append(line[1:].strip())
            else:
                items.append(line)
        parsed[section] = items
    else:
        parsed[section] = content

def add_missing_zh_cn(listings):
    existing_langs = [l.lower() for l in listings.keys()]
    if 'zh-cn' in existing_langs:
        return
        
    print("Adding zh-cn listing to metadata Listings...")
    template_lang = next((k for k in listings if k.lower() == 'zh-tw'), next(iter(listings)))
    new_listing = copy.deepcopy(listings[template_lang])
    base = new_listing.get('BaseListing') or new_listing.get('baseListing')
    if base:
        base['Title'] = 'Clickra'
        base['ShortDescription'] = ''
        base['Description'] = ''
        base['ReleaseNotes'] = ''
        base['Features'] = []
        base['Keywords'] = []
    listings['zh-cn'] = new_listing

def match_parsed_lang(lang, parsed_listings):
    for k in parsed_listings:
        if k.lower() == lang.lower() or (k.lower() == 'en' and lang.lower().startswith('en')):
            return k
    return None

def update_single_listing(base_listing, new_data):
    key_map = {
        'Description': 'description',
        'ReleaseNotes': 'releaseNotes',
        'Features': 'features',
        'ShortDescription': 'shortDescription',
        'Keywords': 'keywords'
    }
    for json_key, parsed_key in key_map.items():
        if parsed_key in new_data and new_data[parsed_key]:
            if json_key in base_listing:
                base_listing[json_key] = new_data[parsed_key]
            elif json_key.lower() in base_listing:
                base_listing[json_key.lower()] = new_data[parsed_key]
            else:
                base_listing[json_key] = new_data[parsed_key]

def update_metadata(metadata, parsed_listings):
    listings = metadata.get('Listings') or metadata.get('listings')
    if not listings or not isinstance(listings, dict):
        print("Error: Could not find Listings dictionary in metadata.")
        return 0
        
    add_missing_zh_cn(listings)
    
    updated_count = 0
    for lang, listing_container in listings.items():
        matched_lang = match_parsed_lang(lang, parsed_listings)
        if not matched_lang:
            continue
            
        base_listing = listing_container.get('BaseListing') or listing_container.get('baseListing')
        if not base_listing or not isinstance(base_listing, dict):
            continue
            
        update_single_listing(base_listing, parsed_listings[matched_lang])
        updated_count += 1
        print(f"Successfully updated metadata listing fields for: {lang}")
        
    return updated_count

def find_msstore_cli():
    # 1. Check if msstore is in PATH
    path_val = shutil.which("msstore")
    if path_val:
        return path_val
        
    # 2. Check localappdata fallback path
    local_app_data = os.environ.get("LOCALAPPDATA", "")
    if local_app_data:
        fallback = os.path.join(local_app_data, "Microsoft", "WindowsApps", "msstore.exe")
        if os.path.exists(fallback):
            return fallback
            
    return None

def load_store_config(config_path):
    if not os.path.exists(config_path):
        print(f"Error: Config file not found at {config_path}")
        sys.exit(1)
        
    with open(config_path, 'r', encoding='utf-8-sig') as f:
        config = json.load(f)
        
    t_id = config.get("TenantId") or config.get("tenantId")
    c_id = config.get("ClientId") or config.get("clientId")
    c_sec = config.get("ClientSecret") or config.get("clientSecret")
    s_id = config.get("SellerId") or config.get("sellerId")
    p_id = config.get("ProductId") or config.get("productId")
    m_path = config.get("MsixPath") or config.get("msixPath")
    
    if not all([t_id, c_id, c_sec, s_id, p_id, m_path]):
        print("Error: Missing credentials or paths in config file.")
        sys.exit(1)
        
    return t_id, c_id, c_sec, s_id, p_id, m_path

def run_command(cmd):
    res = subprocess.run(cmd, capture_output=True, text=True, encoding='utf-8', errors='replace', check=False)  # nosec
    return res

def _retry_command(cmd, max_retries, sleep_time, label, success_check=None, before_retry=None):
    """
    Execute cmd with retry logic.
    Returns the successful CompletedProcess result, or None if all attempts failed.

    Args:
        cmd: Command list to execute.
        max_retries: Maximum number of attempts.
        sleep_time: Seconds to wait between retries.
        label: Human-readable label for log messages.
        success_check: Optional callable(res) -> bool. Defaults to returncode == 0.
        before_retry: Optional callable() called before each retry (e.g., cleanup).
    """
    for attempt in range(1, max_retries + 1):
        print(f"{label} attempt {attempt}/{max_retries}...")
        res = run_command(cmd)
        is_success = success_check(res) if success_check else res.returncode == 0
        if is_success:
            return res
        print(f"{label} attempt {attempt}/{max_retries} failed.")
        if res.stdout:
            print(f"STDOUT:\n{res.stdout}")
        if res.stderr:
            print(f"STDERR:\n{res.stderr}")
        if attempt < max_retries:
            if before_retry:
                before_retry()
            print(f"Waiting {sleep_time} seconds before retrying...")
            time.sleep(sleep_time)
    return None

def run_reconfigure(msstore_bin, t_id, s_id, c_id, c_sec):
    print("Configuring Microsoft Store Developer CLI credentials...")
    cmd_config = [
        msstore_bin, "reconfigure",
        "--tenantId", t_id,
        "--sellerId", s_id,
        "--clientId", c_id,
        "--clientSecret", c_sec
    ]
    res = run_command(cmd_config)
    if res.returncode != 0:
        print("Error configuring credentials:")
        err_msg = res.stderr or res.stdout or ""
        if c_sec:
            err_msg = err_msg.replace(c_sec, "********")
        print(err_msg)
        sys.exit(1)
    print("Credentials configured successfully.")

def delete_pending_submission(msstore_bin, p_id):
    print("Checking and deleting any pending/failed submissions to ensure clean state...")
    cmd_del = [msstore_bin, "submission", "delete", p_id, "--no-confirm"]

    def success_check(res):
        combined = (res.stdout or "") + (res.stderr or "")
        if "No pending submission found" in combined:
            return True
        return res.returncode == 0 and MSSTORE_ERROR_MARKER not in combined

    res = _retry_command(cmd_del, max_retries=3, sleep_time=10,
                         label="Delete pending submission", success_check=success_check)
    if res is None:
        print("Warning: Could not delete pending submission (this is normal if clean).")
        return

    combined = (res.stdout or "") + (res.stderr or "")
    if "No pending submission found" in combined:
        print("No pending submission found. Clean state verified.")
    else:
        if res.stdout:
            print(f"STDOUT:\n{res.stdout}")
        print("Successfully cleared pending/failed submission.")
        print("Waiting 20 seconds for Partner Center to complete deletion...")
        time.sleep(20)

def fetch_partner_metadata(msstore_bin, p_id):
    print("Retrieving current app metadata from Partner Center...")
    cmd_get = [msstore_bin, "submission", "get", p_id]

    def success_check(res):
        return (res.returncode == 0 and
                res.stdout and
                MSSTORE_ERROR_MARKER not in res.stdout and
                MSSTORE_ERROR_MARKER not in (res.stderr or ""))

    res = _retry_command(cmd_get, max_retries=8, sleep_time=15,
                         label="Fetch metadata", success_check=success_check)
    if res is None:
        print("Error: Failed to retrieve submission after maximum retries.")
        sys.exit(1)

    if res.stdout:
        print(f"STDOUT:\n{res.stdout}")
    if res.stderr:
        print(f"STDERR:\n{res.stderr}")
    print("Sanitizing and parsing metadata JSON...")
    try:
        sanitized = sanitize_json_content(res.stdout)
        return json.loads(sanitized)
    except Exception as e:
        print("Failed to parse metadata JSON:")
        print(e)
        sys.exit(1)

def parse_all_listings(repo_root):
    print("Syncing app metadata from docs/StoreListing_*.md files...")
    parsed_listings = {}
    docs_dir = os.path.join(repo_root, 'docs')
    for suffix, locale in LOCALE_MAP.items():
        md_file = os.path.join(docs_dir, f"StoreListing_{suffix}.md")
        parsed = parse_markdown_listing(md_file)
        if parsed:
            parsed_listings[locale] = parsed
            
    if not parsed_listings:
        print("Error: No markdown store listing files were parsed.")
        sys.exit(1)
    return parsed_listings

def upload_partner_metadata(msstore_bin, p_id, metadata):
    minified_json = json.dumps(metadata, ensure_ascii=False, separators=(',', ':'))
    print("Uploading updated metadata to Partner Center...")
    cmd_update = [msstore_bin, "submission", "updateMetadata", p_id, minified_json, "-v"]

    res = _retry_command(cmd_update, max_retries=5, sleep_time=15, label="Upload metadata")
    if res is None:
        print("Error: Failed to upload metadata after maximum retries.")
        sys.exit(1)

    if res.stdout:
        print(f"STDOUT:\n{res.stdout}")
    if res.stderr:
        print(f"STDERR:\n{res.stderr}")
    print("Successfully uploaded metadata to Partner Center.")

def publish_msix_package(msstore_bin, m_path, p_id, no_commit=False):
    if no_commit:
        print("Uploading MSIX package (no commit) to Microsoft Store...")
    else:
        print("Uploading MSIX package and submitting to Microsoft Store...")
    cmd_pub = [msstore_bin, "publish", m_path, "-id", p_id]
    if no_commit:
        cmd_pub.append("--noCommit")

    def success_check(res):
        return (res.returncode == 0 and
                MSSTORE_ERROR_MARKER not in (res.stderr or "") and
                MSSTORE_ERROR_MARKER not in (res.stdout or ""))

    def before_retry():
        # Delete any half-created/pending state before retrying
        delete_pending_submission(msstore_bin, p_id)

    res = _retry_command(cmd_pub, max_retries=3, sleep_time=30,
                         label="Publish package",
                         success_check=success_check, before_retry=before_retry)
    if res is None:
        print("Error publishing package.")
        sys.exit(1)

    if not no_commit:
        print("SUCCESS: Clickra package successfully uploaded and submitted to Microsoft Store!")

def commit_submission(msstore_bin, p_id):
    print("Committing the submission to Microsoft Store...")
    cmd_commit = [msstore_bin, "submission", "publish", p_id]

    sleep_time = RETRY_BASE_DELAY + random.uniform(0, RETRY_JITTER)
    res = _retry_command(cmd_commit, max_retries=MAX_RETRIES, sleep_time=sleep_time,
                         label="Commit submission")
    if res is None:
        print("Error: Failed to commit submission after maximum retries.")
        sys.exit(1)

    if res.stdout:
        print(f"STDOUT:\n{res.stdout}")
    print("SUCCESS: Clickra package successfully uploaded, updated, and committed to Microsoft Store!")

def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    repo_root = os.path.dirname(script_dir)
    config_path = os.path.join(script_dir, "local_store_config.json")
    
    t_id, c_id, c_sec, s_id, p_id, m_path = load_store_config(config_path)
    
    if not os.path.isabs(m_path):
        m_path = os.path.abspath(os.path.join(repo_root, m_path))
        
    if not os.path.isfile(m_path):
        print(f"Error: Microsoft Store package path does not exist: {m_path}")
        sys.exit(1)
        
    msstore_bin = find_msstore_cli()
    if not msstore_bin:
        print("Error: Microsoft Store Developer CLI (msstore.exe) not found.")
        sys.exit(1)
    print(f"Found msstore CLI: {msstore_bin}")
    
    run_reconfigure(msstore_bin, t_id, s_id, c_id, c_sec)
    
    # 1. Clear any failed/pending submission first to ensure clean state
    delete_pending_submission(msstore_bin, p_id)
    
    # 2. Upload MSIX package but do not commit it yet (creates the new draft submission)
    publish_msix_package(msstore_bin, m_path, p_id, no_commit=True)
    
    # 3. Retrieve the newly created draft submission metadata
    metadata = fetch_partner_metadata(msstore_bin, p_id)
    
    # 4. Parse localization listings
    parsed_listings = parse_all_listings(repo_root)
    
    # 5. Merge listing changes
    update_metadata(metadata, parsed_listings)
    
    # 6. Upload updated metadata to the draft submission
    upload_partner_metadata(msstore_bin, p_id, metadata)
    
    # 7. Finally, commit the submission
    commit_submission(msstore_bin, p_id)

if __name__ == '__main__':
    main()
