import sys
import os
import json
import re
import subprocess
import shutil

# Mapping from listing markdown file suffix to Microsoft Store language locale code
LOCALE_MAP = {
    'ZH': 'zh-tw',       # StoreListing_ZH.md -> zh-tw
    'ZH-CN': 'zh-cn',    # StoreListing_ZH-CN.md -> zh-cn
    'EN': 'en',          # StoreListing_EN.md -> en
    'JA': 'ja-jp',       # StoreListing_JA.md -> ja-jp
    'KO': 'ko-kr'        # StoreListing_KO.md -> ko-kr
}

def sanitize_json_content(content):
    r"""
    Cleans up malformed JSON generated by msstore-cli.
    Works around two bugs in msstore-cli's output formatting:
    1. Line wrapping at 80 characters inside string literals.
    2. Splitting unicode escape sequences (\uXXXX) across newlines.
    """
    output = []
    in_string = False
    escaped = False
    
    i = 0
    n = len(content)
    while i < n:
        char = content[i]
        
        if in_string:
            if escaped:
                # If we have a backslash followed by a newline, skip the newline
                if char in ['\r', '\n']:
                    i += 1
                    escaped = False
                    continue
                else:
                    output.append(char)
                    escaped = False
            else:
                if char == '\\':
                    escaped = True
                    output.append(char)
                elif char == '"':
                    in_string = False
                    output.append(char)
                elif char in ['\r', '\n']:
                    # Check if we are in the middle of a split unicode escape (e.g. \u... \n ... XXXX)
                    last_chars = "".join(output[-5:])
                    if re.search(r'\\u[0-9a-fA-F]{0,3}$', last_chars):
                        # This is a split unicode escape sequence. Skip the newline to join it.
                        i += 1
                        continue
                    else:
                        # Raw newline in string: replace with literal '\n' characters
                        output.append('\\n')
                else:
                    output.append(char)
        else:
            if char == '"':
                in_string = True
                output.append(char)
            else:
                output.append(char)
        i += 1
        
    return "".join(output)

def parse_markdown_listing(file_path):
    """
    Parses a StoreListing markdown file into a dictionary of fields.
    """
    if not os.path.exists(file_path):
        print(f"Warning: Listing file {file_path} not found. Skipping.")
        return None

    print(f"Parsing listing file: {file_path}")
    with open(file_path, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    parsed = {
        'description': '',
        'releaseNotes': '',
        'features': [],
        'shortDescription': '',
        'keywords': []
    }

    current_section = None
    section_content = []

    for line in lines:
        stripped = line.strip()
        
        # Check for section header
        if line.startswith('## '):
            # Save previous section
            if current_section:
                save_section(parsed, current_section, section_content)
            
            # Identify new section
            header = stripped[3:].lower()
            if '說明' in header or 'description' in header:
                if '簡短' in header or 'short' in header:
                    current_section = 'shortDescription'
                else:
                    current_section = 'description'
            elif '新增功能' in header or "what's new" in header:
                current_section = 'releaseNotes'
            elif '功能' in header or 'features' in header:
                current_section = 'features'
            elif '關鍵字' in header or 'keywords' in header:
                current_section = 'keywords'
            else:
                current_section = None
            
            section_content = []
        else:
            if current_section:
                section_content.append(line)

    # Save last section
    if current_section:
        save_section(parsed, current_section, section_content)

    return parsed

def save_section(parsed, section, content_lines):
    content = "".join(content_lines).strip()
    content = re.sub(r'\n-+\n', '\n', content)
    
    if section in ['features', 'keywords']:
        items = []
        for line in content.split('\n'):
            line = line.strip()
            # Skip empty lines or notes/explanations in parentheses (e.g., *(Max 7)* or *(最多 7 個)*)
            if not line or ('(' in line and ')' in line) or ('（' in line and '）' in line):
                continue
            if line.startswith('-'):
                items.append(line[1:].strip())
            elif line.startswith('*'):
                items.append(line[1:].strip())
            else:
                items.append(line)
        parsed[section] = items
    else:
        parsed[section] = content

def update_metadata(metadata, parsed_listings):
    updated_count = 0
    listings = metadata.get('Listings') or metadata.get('listings')
    if not listings or not isinstance(listings, dict):
        print("Error: Could not find Listings dictionary in metadata.")
        return 0
        
    # Check if zh-cn is missing, and if so add it
    existing_langs = [l.lower() for l in listings.keys()]
    if 'zh-cn' not in existing_langs:
        print("Adding zh-cn listing to metadata Listings...")
        template_lang = 'zh-tw'
        if template_lang not in listings:
            template_lang = list(listings.keys())[0]
            
        import copy
        new_listing = copy.deepcopy(listings[template_lang])
        base_listing = new_listing.get('BaseListing') or new_listing.get('baseListing')
        if base_listing:
            base_listing['Title'] = 'Clickra'
        listings['zh-cn'] = new_listing

    for lang, listing_container in listings.items():
        matched_lang = None
        for k in parsed_listings:
            # Match locales (e.g. en-us and en match 'en'; zh-tw matches 'zh-tw')
            if k.lower() == lang.lower() or (k.lower() == 'en' and lang.lower().startswith('en')):
                matched_lang = k
                break
        
        if not matched_lang:
            continue
            
        base_listing = listing_container.get('BaseListing') or listing_container.get('baseListing')
        if not base_listing or not isinstance(base_listing, dict):
            continue
            
        new_data = parsed_listings[matched_lang]
        
        key_map = {
            'Description': 'description',
            'ReleaseNotes': 'releaseNotes',
            'Features': 'features',
            'ShortDescription': 'shortDescription',
            'Keywords': 'keywords'
        }
        
        for json_key, parsed_key in key_map.items():
            if parsed_key in new_data and new_data[parsed_key]:
                if json_key in base_listing:
                    base_listing[json_key] = new_data[parsed_key]
                elif json_key.lower() in base_listing:
                    base_listing[json_key.lower()] = new_data[parsed_key]
                else:
                    base_listing[json_key] = new_data[parsed_key]
                    
        updated_count += 1
        print(f"Successfully updated metadata listing fields for: {lang}")
        
    return updated_count

def find_msstore_cli():
    # 1. Check if msstore is in PATH
    path_val = shutil.which("msstore")
    if path_val:
        return path_val
        
    # 2. Check localappdata fallback path
    local_app_data = os.environ.get("LOCALAPPDATA", "")
    if local_app_data:
        fallback = os.path.join(local_app_data, "Microsoft", "WindowsApps", "msstore.exe")
        if os.path.exists(fallback):
            return fallback
            
    return None

def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    repo_root = os.path.dirname(script_dir)
    config_path = os.path.join(script_dir, "local_store_config.json")
    
    # 1. Load config
    if not os.path.exists(config_path):
        print(f"Error: Config file not found at {config_path}")
        sys.exit(1)
        
    with open(config_path, 'r', encoding='utf-8-sig') as f:
        config = json.load(f)
        
    tenant_id = config.get("TenantId")
    client_id = config.get("ClientId")
    client_secret = config.get("ClientSecret")
    seller_id = config.get("SellerId")
    product_id = config.get("ProductId")
    msix_path = config.get("MsixPath")
    
    if not all([tenant_id, client_id, client_secret, seller_id, product_id, msix_path]):
        print("Error: Missing credentials or paths in config file.")
        sys.exit(1)
        
    # 2. Find msstore CLI
    msstore_bin = find_msstore_cli()
    if not msstore_bin:
        print("Error: Microsoft Store Developer CLI (msstore.exe) not found.")
        sys.exit(1)
    print(f"Found msstore CLI: {msstore_bin}")
    
    # 3. Configure credentials
    print("Configuring Microsoft Store Developer CLI credentials...")
    cmd_config = [
        msstore_bin, "reconfigure",
        "--tenantId", tenant_id,
        "--sellerId", seller_id,
        "--clientId", client_id,
        "--clientSecret", client_secret
    ]
    res = subprocess.run(cmd_config, capture_output=True, text=True)
    if res.returncode != 0:
        print("Error configuring credentials:")
        print(res.stderr or res.stdout)
        sys.exit(1)
    print("Credentials configured successfully.")
    
    # 4. Get current metadata
    print("Retrieving current app metadata from Partner Center...")
    cmd_get = [msstore_bin, "submission", "get", product_id]
    res_get = subprocess.run(cmd_get, capture_output=True, text=True, encoding='utf-8')
    if res_get.returncode != 0:
        print("Error retrieving submission:")
        print(res_get.stderr)
        sys.exit(1)
        
    raw_json = res_get.stdout
    
    # Sanitize and load JSON
    print("Sanitizing and parsing metadata JSON...")
    try:
        sanitized = sanitize_json_content(raw_json)
        metadata = json.loads(sanitized)
    except Exception as e:
        print("Failed to parse metadata JSON:")
        print(e)
        sys.exit(1)
        
    # 5. Parse markdown files
    print("Syncing app metadata from docs/StoreListing_*.md files...")
    parsed_listings = {}
    docs_dir = os.path.join(repo_root, 'docs')
    for suffix, locale in LOCALE_MAP.items():
        md_file = os.path.join(docs_dir, f"StoreListing_{suffix}.md")
        parsed = parse_markdown_listing(md_file)
        if parsed:
            parsed_listings[locale] = parsed
            
    if not parsed_listings:
        print("Error: No markdown store listing files were parsed.")
        sys.exit(1)
        
    # 6. Update metadata
    updated = update_metadata(metadata, parsed_listings)
    print(f"Updated {updated} language listings in the metadata object.")
    
    # 7. Minify JSON string
    minified_json = json.dumps(metadata, ensure_ascii=False, separators=(',', ':'))
    
    # 8. Upload updated metadata
    print("Uploading updated metadata to Partner Center...")
    cmd_update = [msstore_bin, "submission", "updateMetadata", product_id, minified_json, "-v"]
    res_up = subprocess.run(cmd_update, capture_output=True, text=True, encoding='utf-8')
    if res_up.returncode != 0:
        print("Error uploading metadata:")
        print(res_up.stderr or res_up.stdout)
        sys.exit(1)
    print("Successfully uploaded metadata to Partner Center.")
    
    # 9. Publish package
    print("Uploading MSIX package and submitting to Microsoft Store...")
    cmd_pub = [msstore_bin, "publish", msix_path, "-id", product_id]
    res_pub = subprocess.run(cmd_pub, capture_output=True, text=True)
    print(res_pub.stdout)
    if res_pub.returncode != 0:
        print("Error publishing package:")
        print(res_pub.stderr)
        sys.exit(1)
    print("SUCCESS: Clickra package successfully uploaded and submitted to Microsoft Store!")

if __name__ == '__main__':
    main()
