using System;

namespace Clickra.Core
{
    public static partial class Localization
    {
        private static void RegisterLibreOfficeManagementTranslations()
        {
            var data = new (string Key, string Tw, string Cn, string En, string Ja, string Ko)[]
            {
                ( "setting_libreoffice_download_prompt", "Clickra 將下載並驗證 LibreOffice 官方 MSI 安裝程式。\n\n版本：{0}\n版本類型：{1}\n下載大小：約 {2}\n安裝位置：{3}\nSHA256：{4}\n\n接下來 Windows 可能會要求系統安裝權限。安裝或更新完成後，Clickra 會在能驗證唯一 MSI 身分時管理這套系統 LibreOffice，並可從 Clickra 設定中解除安裝；LibreOffice 仍可在 Clickra 以外正常使用。是否繼續？", "Clickra 将下载并验证 LibreOffice 官方 MSI 安装程序。\n\n版本：{0}\n版本类型：{1}\n下载大小：约 {2}\n安装位置：{3}\nSHA256：{4}\n\n接下来 Windows 可能会要求系统安装权限。安装或更新完成后，Clickra 会在能够验证唯一 MSI 身份时管理这套系统 LibreOffice，并可从 Clickra 设置中卸载；LibreOffice 仍可在 Clickra 以外正常使用。是否继续？", "Clickra will download and verify the official LibreOffice MSI installer.\n\nVersion: {0}\nEdition: {1}\nDownload size: about {2}\nInstall path: {3}\nSHA256: {4}\n\nWindows may ask for permission to install system software. After installation or update, Clickra will manage this system LibreOffice only when Windows can verify one unique MSI identity; a verified installation can then be uninstalled from Clickra settings. LibreOffice can still be used outside Clickra. Continue?", "Clickra は LibreOffice 公式 MSI インストーラーをダウンロードして検証します。\n\nバージョン：{0}\nエディション：{1}\nダウンロードサイズ：約 {2}\nインストール先：{3}\nSHA256：{4}\n\nWindows がシステムへのインストール許可を求める場合があります。インストールまたは更新後、Windows が一意の MSI 識別情報を確認できた場合にのみ、このシステム LibreOffice は Clickra の管理対象となり、Clickra の設定から削除できます。LibreOffice は引き続き Clickra 以外でも使用できます。続行しますか？", "Clickra가 공식 LibreOffice MSI 설치 파일을 다운로드하고 검증합니다.\n\n버전: {0}\n에디션: {1}\n다운로드 크기: 약 {2}\n설치 위치: {3}\nSHA256: {4}\n\nWindows가 시스템 소프트웨어 설치 권한을 요청할 수 있습니다. 설치 또는 업데이트 후 Windows에서 하나의 고유한 MSI ID를 확인할 수 있을 때만 이 시스템 LibreOffice를 Clickra가 관리하며, Clickra 설정에서 제거할 수 있습니다. LibreOffice는 계속 Clickra 밖에서도 사용할 수 있습니다. 계속하시겠습니까?" ),
                ( "setting_libreoffice_management_unverified", "LibreOffice 已完成安裝或更新，但 Windows 無法唯一驗證其 MSI 身分，因此 Clickra 未取得解除安裝管理權。這套 LibreOffice 仍可正常使用。", "LibreOffice 已完成安装或更新，但 Windows 无法唯一验证其 MSI 身份，因此 Clickra 未取得卸载管理权限。这套 LibreOffice 仍可正常使用。", "LibreOffice was installed or updated successfully, but Windows could not verify one unique MSI identity. Clickra therefore did not take uninstall management of this installation. LibreOffice remains available for normal use.", "LibreOffice のインストールまたは更新は完了しましたが、Windows で一意の MSI 識別情報を確認できませんでした。そのため Clickra はアンインストール管理を取得していません。LibreOffice は通常どおり使用できます。", "LibreOffice 설치 또는 업데이트는 완료되었지만 Windows에서 하나의 고유한 MSI ID를 확인할 수 없었습니다. 따라서 Clickra는 이 설치의 제거 관리 권한을 갖지 않습니다. LibreOffice는 정상적으로 사용할 수 있습니다." ),
                ( "setting_libreoffice_adopt", "交由 Clickra 管理", "交给 Clickra 管理", "Manage with Clickra", "Clickra で管理", "Clickra에서 관리" ),
                ( "setting_libreoffice_adopt_confirm", "確定要將此既有 LibreOffice 交由 Clickra 管理嗎？\n納管後您將能直接在 Clickra 設定中更新或解除安裝此 LibreOffice。", "确定要将此现有 LibreOffice 交给 Clickra 管理吗？\n接管后您将能直接在 Clickra 设置中更新或卸载此 LibreOffice。", "Adopt this existing LibreOffice installation into Clickra management?\nOnce adopted, Clickra will be able to update or uninstall this LibreOffice directly from settings.", "この既存の LibreOffice を Clickra の管理下に移行しますか？\n移行後は Clickra の設定から直接更新や削除ができるようになります。", "기존 LibreOffice를 Clickra 관리 대상으로 전환하시겠습니까?\n전환 후에는 Clickra 설정에서 직접 업데이트하거나 제거할 수 있습니다." ),
                ( "setting_libreoffice_adopt_success", "此 LibreOffice 現已交由 Clickra 管理。", "此 LibreOffice 现已交给 Clickra 管理。", "This LibreOffice is now managed by Clickra.", "この LibreOffice は Clickra の管理下に移行されました。", "이 LibreOffice는 이제 Clickra에서 관리됩니다." )
            };

            RegisterTranslations(data);
        }

        private static void RegisterFluentDashboardTranslations()
        {
            var data = new (string Key, string Tw, string Cn, string En, string Ja, string Ko)[]
            {
                ("fluent_nav_overview", "總覽", "总览", "Overview", "概要", "개요"),
                ("fluent_nav_convert", "轉檔", "转换", "Convert", "変換", "변환"),
                ("fluent_nav_history", "歷史", "历史", "History", "履歴", "기록"),
                ("fluent_nav_settings", "設定", "设置", "Settings", "設定", "설정"),
                ("fluent_nav_about", "關於", "关于", "About", "情報", "정보"),
                ("fluent_overview_title", "轉換檔案", "转换文件", "Convert files", "ファイルを変換", "파일 변환"),
                ("fluent_overview_subtitle", "PDF、Office、Markdown 與圖片工具集中在同一個工作區。", "PDF、Office、Markdown 与图片工具集中在同一个工作区。", "PDF, Office, Markdown, and image tools in one workspace.", "PDF、Office、Markdown、画像ツールを 1 つの作業領域に集約。", "PDF, Office, Markdown, 이미지 도구를 한 작업 공간에서 사용합니다."),
                ("fluent_choose_files", "選擇檔案", "选择文件", "Choose files", "ファイルを選択", "파일 선택"),
                ("fluent_recent_jobs", "近期作業", "近期作业", "Recent jobs", "最近のジョブ", "최근 작업"),
                ("fluent_recent_activity", "近期活動", "近期活动", "Recent activity", "最近の操作", "최근 활동"),
                ("fluent_activity_summary", "活動摘要", "活动摘要", "Activity summary", "操作サマリー", "활동 요약"),
                ("fluent_total", "總計", "总计", "Total", "合計", "전체"),
                ("fluent_success", "成功", "成功", "OK", "成功", "성공"),
                ("fluent_failed", "失敗", "失败", "Fail", "失敗", "실패"),
                ("fluent_tools", "PDF 與 Office 工具", "PDF 与 Office 工具", "PDF and Office tools", "PDF と Office ツール", "PDF 및 Office 도구"),
                ("fluent_explorer_menu", "檔案總管選單", "文件资源管理器菜单", "Explorer menu", "Explorer メニュー", "Explorer 메뉴"),
                ("fluent_available", "可用", "可用", "Available", "利用可能", "사용 가능"),
                ("fluent_pdf_desc", "合併、壓縮、翻譯、解密。", "合并、压缩、翻译、解密。", "Merge, compress, translate, decrypt.", "結合、圧縮、翻訳、復号。", "병합, 압축, 번역, 암호 해제."),
                ("fluent_office_desc", "Word、Excel、PowerPoint 轉 PDF。", "Word、Excel、PowerPoint 转 PDF。", "Word, Excel, PowerPoint to PDF.", "Word、Excel、PowerPoint を PDF へ。", "Word, Excel, PowerPoint를 PDF로 변환."),
                ("fluent_images_desc", "建立 PDF、合併、拼接。", "创建 PDF、合并、拼接。", "Create PDFs, merge, stitch.", "PDF 作成、結合、連結。", "PDF 생성, 병합, 이어붙이기."),
                ("fluent_drop_title", "拖放檔案到這裡", "拖放文件到这里", "Drop files here", "ここにファイルをドロップ", "여기에 파일 놓기"),
                ("fluent_drop_browse", "點擊此區域選取檔案", "点击此区域选择文件", "Click this area to browse", "この領域をクリックして選択", "이 영역을 클릭해 선택"),
                ("fluent_drop_types", "PDF、Office、Markdown 與圖片", "PDF、Office、Markdown 与图片", "PDF, Office, Markdown, and images", "PDF、Office、Markdown、画像", "PDF, Office, Markdown, 이미지"),
                ("fluent_selected_files", "已選取檔案", "已选择文件", "Selected files", "選択したファイル", "선택한 파일"),
                ("fluent_selected_files_desc", "可個別移除；轉換後只清除用到的檔案。", "可单独移除；转换后只清除用到的文件。", "Files can be removed individually; only used files are cleared after conversion.", "個別に削除できます。変換後は使用したファイルだけがクリアされます。", "개별로 제거할 수 있으며, 변환 후 사용된 파일만 지워집니다."),
                ("fluent_no_files", "未選取檔案", "未选择文件", "No files selected", "ファイル未選択", "선택한 파일 없음"),
                ("fluent_command", "命令", "命令", "Command", "コマンド", "명령"),
                ("fluent_choose_command", "選擇命令", "选择命令", "Choose a command", "コマンドを選択", "명령 선택"),
                ("fluent_selected_command", "已選擇：{0}", "已选择：{0}", "Selected: {0}", "選択中: {0}", "선택됨: {0}"),
                ("fluent_run", "執行", "运行", "Run", "実行", "실행"),
                ("fluent_start", "開始轉換", "开始转换", "Start conversion", "変換開始", "변환 시작"),
                ("fluent_ready", "準備就緒", "准备就绪", "Ready", "準備完了", "준비됨"),
                ("fluent_select_history", "選取一筆歷史紀錄", "选择一条历史记录", "Select a history item", "履歴項目を選択", "기록 항목 선택"),
                ("fluent_files", "檔案", "文件", "Files", "ファイル", "파일"),
                ("fluent_elapsed", "耗時", "耗时", "Elapsed", "経過時間", "소요 시간"),
                ("fluent_result", "結果", "结果", "Result", "結果", "결과"),
                ("fluent_settings_subtitle", "使用者介面與檔案總管命令的預設值", "界面与文件资源管理器命令的默认值", "Defaults used by the dashboard and Explorer commands", "ダッシュボードと Explorer コマンドの既定値", "대시보드와 Explorer 명령의 기본값"),
                ("fluent_output_dir", "輸出資料夾", "输出文件夹", "Output directory", "出力フォルダー", "출력 폴더"),
                ("fluent_output_dir_desc", "轉換後檔案的儲存位置", "转换后文件的保存位置", "Where converted files are saved", "変換後ファイルの保存先", "변환된 파일 저장 위치"),
                ("fluent_output_source", "與來源相同", "与来源相同", "Same as source", "元と同じ", "원본과 같음"),
                ("fluent_office_engine", "Office 引擎", "Office 引擎", "Office engine", "Office エンジン", "Office 엔진"),
                ("fluent_office_engine_desc", "Office 轉檔使用的引擎", "Office 转换使用的引擎", "Engine used for Office conversion", "Office 変換に使うエンジン", "Office 변환에 사용할 엔진"),
                ("fluent_custom", "自訂...", "自定义...", "Custom...", "カスタム...", "사용자 지정..."),
                ("fluent_default_language", "預設語言", "默认语言", "Default language", "既定の言語", "기본 언어"),
                ("fluent_default_language_desc", "用於介面、檔案總管命令與處理訊息。", "用于界面、文件资源管理器命令与处理消息。", "Used by the interface, Explorer commands, and processor messages.", "UI、Explorer コマンド、処理メッセージに使用します。", "UI, Explorer 명령, 처리 메시지에 사용합니다."),
                ("fluent_pdf_target", "PDF 翻譯目標", "PDF 翻译目标", "PDF translation target", "PDF 翻訳先", "PDF 번역 대상"),
                ("fluent_behavior", "行為", "行为", "Behavior", "動作", "동작"),
                ("fluent_quiet_mode", "靜默模式", "静默模式", "Quiet mode", "静音モード", "무음 모드"),
                ("fluent_quiet_mode_desc", "檔案總管命令預設使用；此視窗仍會顯示。", "文件资源管理器命令默认使用；此窗口仍会显示。", "Default for Explorer commands; this dashboard still stays visible.", "Explorer コマンドの既定。この画面は表示されます。", "Explorer 명령의 기본값입니다. 이 창은 계속 표시됩니다."),
                ("fluent_notifications", "通知", "通知", "Notifications", "通知", "알림"),
                ("fluent_notifications_desc", "轉換完成時顯示通知", "转换完成时显示通知", "Show toast when conversion completes", "変換完了時に通知を表示", "변환 완료 시 알림 표시"),
                ("fluent_pdf_compression", "PDF 壓縮", "PDF 压缩", "PDF compression", "PDF 圧縮", "PDF 압축"),
                ("fluent_strip_fonts", "移除嵌入字型", "移除嵌入字体", "Strip embedded fonts", "埋め込みフォントを削除", "포함 글꼴 제거"),
                ("fluent_minify_content", "最佳化 PDF 結構", "优化 PDF 结构", "Optimize PDF structure", "PDF 構造を最適化", "PDF 구조 최적화"),
                ("fluent_about_desc", "Clickra 是 Windows 上快速、輕量的檔案轉換工作區。", "Clickra 是 Windows 上快速、轻量的文件转换工作区。", "A fast, lightweight file conversion workspace for Windows.", "Windows 向けの高速で軽量なファイル変換ワークスペース。", "Windows용 빠르고 가벼운 파일 변환 작업 공간입니다."),
                ("fluent_github", "在 GitHub 檢視", "在 GitHub 查看", "View on GitHub", "GitHub で表示", "GitHub에서 보기"),
                ("fluent_platform", "平台", "平台", "Platform", "プラットフォーム", "플랫폼"),
                ("fluent_app_model", "應用程式模型", "应用模型", "App model", "アプリモデル", "앱 모델"),
                ("fluent_toast_done_title", "Clickra 轉換完成", "Clickra 转换完成", "Clickra conversion completed", "Clickra 変換完了", "Clickra 변환 완료"),
                ("fluent_toast_done_body", "{0} 已完成，共 {1} 個檔案。", "{0} 已完成，共 {1} 个文件。", "{0} finished for {1} file(s).", "{0} が完了しました。{1} 件。", "{0} 완료, {1}개 파일."),
                ("fluent_toast_canceled_title", "Clickra 轉換已取消", "Clickra 转换已取消", "Clickra conversion canceled", "Clickra 変換キャンセル", "Clickra 변환 취소"),
                ("fluent_toast_canceled_body", "{0} 已取消。", "{0} 已取消。", "{0} was canceled.", "{0} はキャンセルされました。", "{0} 취소됨."),
                ("fluent_toast_failed_title", "Clickra 轉換失敗", "Clickra 转换失败", "Clickra conversion failed", "Clickra 変換失敗", "Clickra 변환 실패"),
                ("fluent_validate_min_files", "{0} 至少需要 {1} 個檔案。", "{0} 至少需要 {1} 个文件。", "{0} needs at least {1} file(s).", "{0} には少なくとも {1} 件のファイルが必要です。", "{0}에는 최소 {1}개 파일이 필요합니다."),
                ("fluent_validate_bad_ext", "{0} 不適用於 {1}。", "{0} 不适用于 {1}。", "{0} is not valid for {1}.", "{0} は {1} に使用できません。", "{0}은(는) {1}에 사용할 수 없습니다."),
                ("fluent_progress_starting", "正在開始...", "正在开始...", "Starting...", "開始中...", "시작 중..."),
                ("fluent_progress_completed", "已完成。", "已完成。", "Completed.", "完了しました。", "완료됨."),
                ("fluent_progress_canceled", "已取消。", "已取消。", "Canceled.", "キャンセルしました。", "취소됨."),
                ("fluent_progress_failed", "失敗：{0}", "失败：{0}", "Failed: {0}", "失敗: {0}", "실패: {0}"),
                ("fluent_progress_running_title", "正在{0}", "正在{0}", "{0} in progress", "{0} を実行中", "{0} 진행 중"),
                ("fluent_progress_preparing", "準備中", "准备中", "Preparing", "準備中", "준비 중"),
                ("fluent_progress_output", "輸出：", "输出：", "Output: ", "出力: ", "출력: "),
                ("fluent_progress_waiting", "請稍候，正在背景處理中...", "请稍候，正在后台处理中...", "Please wait. Processing in the background...", "お待ちください。バックグラウンドで処理しています...", "잠시만 기다려 주세요. 백그라운드에서 처리 중입니다..."),
                ("fluent_progress_processing", "正在處理...", "正在处理...", "Processing...", "処理中...", "처리 중..."),
                ("fluent_progress_done_title", "處理完成", "处理完成", "Completed", "処理完了", "처리 완료"),
                ("fluent_progress_failed_title", "處理未完成", "处理未完成", "Not completed", "未完了", "완료되지 않음"),
                ("fluent_progress_done_footer", "處理完成，可以開啟輸出資料夾。", "处理完成，可以打开输出文件夹。", "Completed. You can open the output folder.", "完了しました。出力フォルダーを開けます。", "완료되었습니다. 출력 폴더를 열 수 있습니다."),
                ("fluent_progress_failed_footer", "請檢查訊息後關閉視窗。", "请检查消息后关闭窗口。", "Check the message, then close this window.", "メッセージを確認してから閉じてください。", "메시지를 확인한 후 창을 닫아 주세요."),
                ("fluent_progress_open_folder", "開啟資料夾", "打开文件夹", "Open folder", "フォルダーを開く", "폴더 열기"),
                ("fluent_progress_close", "關閉", "关闭", "Close", "閉じる", "닫기"),
                ("fluent_progress_done_summary", "{0} 個檔案 · 耗時 {1} 秒", "{0} 个文件 · 耗时 {1} 秒", "{0} file(s) · {1} s", "{0} 件 · {1} 秒", "{0}개 파일 · {1}초"),
                ("fluent_progress_failed_generic", "轉換過程中發生錯誤。", "转换过程中发生错误。", "An error occurred during conversion.", "変換中にエラーが発生しました。", "변환 중 오류가 발생했습니다."),
                ("fluent_progress_invalid_command", "無效的轉換命令。", "无效的转换命令。", "Invalid conversion command.", "無効な変換コマンドです。", "잘못된 변환 명령입니다."),
                ("fluent_progress_file_not_found", "找不到可轉換的檔案。", "找不到可转换的文件。", "No convertible files were found.", "変換できるファイルが見つかりません。", "변환할 파일을 찾을 수 없습니다."),
                ("fluent_progress_multiple_files", "{0} 等 {1} 個檔案", "{0} 等 {1} 个文件", "{0} and {1} files", "{0} ほか {1} 件", "{0} 외 {1}개 파일"),
                ("fluent_task_queue_title", "進行中任務", "进行中任务", "Active tasks", "実行中のタスク", "실행 중인 작업"),
                ("fluent_task_queue_running", "{0} 個任務進行中", "{0} 个任务进行中", "{0} task(s) in progress", "{0} 件のタスク実行中", "{0}개 작업 실행 중"),
                ("fluent_task_ledger_title", "進行中任務", "进行中任务", "Active tasks", "実行中のタスク", "실행 중인 작업"),
                ("fluent_task_ledger_empty", "目前沒有進行中的任務。", "当前没有进行中的任务。", "No active tasks.", "実行中のタスクはありません。", "실행 중인 작업이 없습니다."),
                ("fluent_task_view", "查看", "查看", "View", "表示", "보기"),
                ("fluent_task_resume", "繼續", "继续", "Resume", "再開", "재개"),
                ("setting_parked_ttl_title", "待繼續任務保留期限", "待继续任务保留期限", "Paused task retention", "再開待ちタスクの保持期限", "재개 대기 작업 보관 기간"),
                ("setting_parked_ttl_desc", "暫停後等待繼續的轉換任務，超過此天數會自動清理；0 = 永久保留", "暂停后等待继续的转换任务，超过此天数会自动清理；0 = 永久保留", "Paused conversions are cleaned up after this many days; 0 keeps them indefinitely", "一時停止して再開待ちの変換は、この日数を過ぎると自動的に削除されます。0 = 無期限に保持", "일시 중지되어 재개를 기다리는 변환은 이 기간이 지나면 자동 정리됩니다. 0 = 영구 보관"),
                ("setting_parked_ttl_days", RetentionDayZh, RetentionDayZh, "{0} days", "{0} 日", "{0} 일"),
                ("setting_parked_ttl_day_single", RetentionDayZh, RetentionDayZh, "{0} day", "{0} 日", "{0} 일"),
                ("setting_parked_ttl_unlimited", "0（無限期）", "0（无期限）", "0 (unlimited)", "0（無期限）", "0 (무제한)"),
                ("setting_parked_ttl_default", "{0} 天（預設）", "{0} 天（默认）", "{0} days (default)", "{0} 日（デフォルト）", "{0} 일 (기본값)"),
                ("setting_parked_ttl_current", "目前保留：{0}", "当前保留：{0}", "Current retention: {0}", "現在の保持期間: {0}", "현재 보관 기간: {0}"),
                ("fluent_park_toast_title", "Clickra 轉換已暫存", "Clickra 转换已暂存", "Clickra conversion parked", "Clickra 変換を一時停止", "Clickra 변환이 보류됨"),
                ("fluent_park_toast_body", "可在「歷史」頁繼續或取消。", "可在“历史”页继续或取消。", "Resume or cancel it from the History page.", "「履歴」ページで再開またはキャンセルできます。", "「기록」페이지에서 재개하거나 취소할 수 있습니다."),
                ("fluent_pdf_password", "PDF 密碼", "PDF 密码", "PDF password", "PDF パスワード", "PDF 암호"),
                ("fluent_pdf_password_placeholder", "輸入 PDF 密碼", "输入 PDF 密码", "Enter PDF password", "PDF パスワードを入力", "PDF 암호 입력"),
                ("fluent_ok", "確定", "确定", "OK", "OK", "확인"),
                ("fluent_office", OfficeName, OfficeName, OfficeName, OfficeName, OfficeName),
                ("fluent_images", "圖片", "图片", "Images", "画像", "이미지"),
                ("fluent_history_subtitle", "近期轉換結果", "近期转换结果", "Recent conversion results", "最近の変換結果", "최근 변환 결과"),
                ("task_parked_waiting", "等待輸入", "等待输入", "Waiting for input", "入力待ち", "입력 대기"),
                ("task_parked_title", "待繼續任務", "待继续任务", "Tasks awaiting continuation", "再開待ちタスク", "재개 대기 작업"),
                ("status_canceled", "已取消", "已取消", "Canceled", "キャンセル済み", "취소됨"),
                ("task_active_title", "進行中的轉換", "进行中的转换", "Conversions in progress", "進行中の変換", "진행 중인 변환"),
                ("task_file_index", "第 {0}/{1} 檔", "第 {0}/{1} 个文件", "File {0}/{1}", "{0}/{1} ファイル", "{0}/{1} 파일"),
                ("task_parked_desc", "已暫存的轉換作業，可在過期前隨時繼續、取消，或只調整這一件的保留期限。", "已暂存的转换任务，可在过期前随时继续、取消，或只调整这一件的保留期限。", "Parked conversions can be resumed, cancelled, or given their own retention before expiring.", "一時停止した変換作業は、有効期限が切れる前に再開・キャンセル、またはこのタスクだけ保留期間を変更できます。", "보류된 변환 작업은 만료되기 전에 언제든지 재개·취소하거나 이 작업만 보관 기간을 바꿀 수 있습니다."),
                ("task_parked_cancel_confirm", "確定要取消此暫存任務嗎？", "确定要取消此暂存任务吗？", "Are you sure you want to cancel this parked task?", "この一時停止タスクをキャンセルしてもよろしいですか？", "이 보류된 작업을 취소하시겠습니까?"),
                ("task_parked_ttl_days", "剩餘 {0} 天過期", "剩余 {0} 天过期", "Expires in {0} days", "残り {0} 日で期限切れ", "{0}일 후 만료"),
                ("task_parked_ttl_days_one", "剩餘 {0} 天過期", "剩余 {0} 天过期", "Expires in {0} day", "残り {0} 日で期限切れ", "{0}일 후 만료"),
                ("task_parked_ttl_expiring_soon", "即將過期（剩餘不到 1 天）", "即将过期（剩余不到 1 天）", "Expiring soon (less than 1 day left)", "まもなく期限切れ（残り1日未満）", "곧 만료됨 (1일 미만 남음)"),
                ("task_parked_ttl_unlimited", "永久保留", "永久保留", "Never expires", "無期限に保持", "영구 보관"),
                ("task_parked_ttl_expired", "已過期（即將清理）", "已过期（即将清理）", "Expired (pending cleanup)", "期限切れ（まもなく削除）", "만료됨 (곧 정리됨)"),
                ("task_parked_expiring_warning", "⚠️ 有 {0} 個待繼續任務即將過期，請儘速處理。", "⚠️ 有 {0} 个待继续任务即将过期，请尽快处理。", "⚠️ {0} parked task(s) expiring soon. Please resume or cancel promptly.", "⚠️ {0} 件の再開待ちタスクがまもなく期限切れになります。速やかに処理してください。", "⚠️ {0}개의 재개 대기 작업이 곧 만료됩니다. 신속히 처리해 주세요."),
                ("task_parked_badge_expiring", "即將過期", "即将过期", "Expiring soon", "まもなく期限切れ", "곧 만료됨"),
                ("task_parked_extend_days", "延長 {0} 天", "延长 {0} 天", "Extend by {0} days", "{0} 日延長", "{0}일 연장"),
                ("task_parked_shorten_days", "縮短 {0} 天", "缩短 {0} 天", "Shorten by {0} days", "{0} 日短縮", "{0}일 단축"),
                ("task_parked_retention_reset", "恢復全域設定", "恢复全局设置", "Use the global setting", "全体設定に戻す", "전역 설정으로"),
                ("task_parked_ttl_override", "（此任務自訂）", "（此任务自定义）", " (set for this task)", "（このタスク専用）", "(이 작업 전용)"),
                ("setting_image_compress_title", "圖片壓縮品質", "图片压缩质量", "Image Compression Quality", "画像圧縮品質", "이미지 압축 품질"),
                ("setting_image_compress_desc", "選擇圖片壓縮品質等級（等級越高，壓縮比越大）", "选择图片压缩质量等级（等级越高，压缩比越大）", "Select image compression quality level (higher levels compress more)", "画像圧縮品質レベルを選択（高いほど高圧縮）", "이미지 압축 품질 수준 선택 (높을수록 압축률 증가)"),
                ("setting_image_level_min", "最低", "最低", "Minimum", "最小", "최소"),
                ("setting_image_level_small", "較小", "较小", "Small", "小", "작게"),
                ("setting_image_level_std", "標準", "标准", "Standard", "標準", "표준"),
                ("setting_image_level_high", "高壓縮", "高压缩", "High", "高圧縮", "고압축"),
                ("setting_image_max_dimension_title", "輸出尺寸", "输出尺寸", "Output size", "出力サイズ", "출력 크기"),
                ("setting_image_max_dimension_desc", "小圖不會被放大", "小图不会被放大", "Smaller images are never enlarged", "小さい画像は拡大しません", "작은 이미지는 확대하지 않습니다"),
            };

            RegisterTranslations(data);
        }
    }
}
