using System;

namespace Clickra.Core
{
    public static partial class Localization
    {
        private static void RegisterGeneralTranslations()
        {
            var data = new (string Key, string Tw, string Cn, string En, string Ja, string Ko)[]
            {
                ("tab_status", "狀態", "状态", "Status", "状態", "상태"),
                ("tab_history", "歷史", "历史", "History", "履歴", "기록"),
                ("tab_settings", "設定", "设置", "Settings", "設定", "설정"),
                ("setting_silent_title", "背景靜默轉檔", "背景静默转档", "Silent Mode", "サイレントモード", "자동 변환 모드"),
                ("setting_silent_desc", "在右鍵選單點擊時直接於背景處理，不顯示進度視窗", "在右键菜单点击时直接于背景处理，不显示进度窗口", "Process in background without showing progress window", "進行状況ウィンドウを表示せず、バックグラウンドで処理します", "진행 창을 표시하지 않고 백그라운드에서 바로 처리합니다"),
                ("setting_notify_title", "顯示轉換通知", "显示转换通知", "Show Notifications", "変換通知を表示", "변환 알림 표시"),
                ("setting_notify_desc", "作業完成或失敗後，於系統右下角彈出 Windows Toast 通知", "作业完成或失败后，于系统右下角弹出 Windows Toast 通知", "Show Toast notification when conversion completes/fails", "完了または失敗時に、Windows トースト通知を表示します", "완료 또는 실패 시 Windows 토스트 알림을 표시합니다"),
                ("setting_output_title", "預設輸出路徑", "默认输出路径", "Default Output Path", "既定の出力先", "기본 출력 경로"),
                ("setting_output_desc", "選擇轉換後 PDF 與圖片預設的儲存位置", "选择转换后 PDF 与图片默认的存储位置", "Select the default save location for converted files", "変換後のファイルの保存先を選択します", "변환된 파일의 기본 저장 위치를 선택합니다"),
                ("setting_output_same_as_source", "與來源相同", "与来源相同", "Same as source", "ソースと同じ", "원본과 동일"),
                ("setting_output_desktop", "桌面", "桌面", "Desktop", "デスクトップ", "바탕 화면"),
                ("setting_output_downloads", "下載", "下载", "Downloads", "ダウンロード", "다운로드"),
                ("setting_output_custom", "自訂...", "自定义...", "Custom...", "カスタム...", "사용자 정의..."),
                ("setting_output_selected_path", "已選取路徑", "已选择路径", "Selected path", "選択されたパス", "선택한 경로"),
                ("setting_output_browse_title", "選擇預設輸出資料夾", "选择默认输出文件夹", "Select Default Output Folder", "既定の出力フォルダを選択", "기본 출력 폴더 선택"),
                ("overview_engine_status", "轉換引擎狀態", "转换引擎状态", "Conversion Engine Status", "変換エンジンの状態", "변환 엔진 상태"),
                ("overview_stats", "轉換統計", "转换统计", "Conversion Stats", "統計情報", "오늘의 통계"),
                ("overview_stat_total", "總轉換次數", "总转换次数", "Total Conversions", "総変換回数", "총 변환 횟수"),
                ("overview_stat_success", "成功次數", "成功次数", "Successful", "成功回数", "성공 횟수"),
                ("overview_stat_failed", "失敗次數", "失败次数", "Failed", "失敗回数", "실패 횟수"),
                ("overview_office_conversion", "Office 轉檔", "Office 转换", "Office conversion", "Office 変換", "Office 변환"),
                ("overview_engine_active", "使用 {0}", "使用 {0}", "Using {0}", "{0} を使用", "{0} 사용"),
                ("overview_engine_unavailable", "{0} 尚未就緒", "{0} 尚未就绪", "{0} not ready", "{0} は未準備です", "{0} 준비되지 않음"),
                ("history_clear", "清除紀錄", "清除记录", "Clear History", "履歴をクリア", "기록 삭제"),
                ("history_clear_confirm", "您確定要清除所有的轉換歷史紀錄嗎？", "您确定要清除所有的转换历史记录吗？", "Are you sure you want to clear all history?", "すべての変換履歴をクリアしてもよろしいですか？", "모든 변환 기록을 삭제하시겠습니까?"),
                ("history_empty", "尚無任何轉換紀錄。", "尚无任何转换记录。", "No conversion history.", "変換履歴はありません。", "변환 기록이 없습니다."),
                ("status_pending", "等待中", "等待中", "Pending", "待機中", "대기 중"),
                ("status_converting", "轉換中", "转换中", "Converting", "変換中", "변환 중"),
                ("status_success", "成功", "成功", "Success", "成功", "성공"),
                ("status_failed", "失敗", "失败", "Failed", "失敗", "실패"),
                ("label_files", "個檔案", "个文件", "files", "個のファイル", "개의 파일"),
                ("setting_lang_title", "介面語言", "界面语言", "Interface Language", "表示言語", "표시 언어"),
                ("setting_lang_desc", "選擇 Dashboard 的顯示語言", "选择 Dashboard 的显示语言", "Select the display language for the Dashboard", "Dashboard の表示言語を選択します", "Dashboard 표시 언어를 선택합니다"),
                ("search_lang_placeholder", "搜尋語言 / Search...", "搜索语言...", "Search language...", "言語を検索...", "언어 검색..."),
                ("engine_pdf", "PDF 處理核心 (PDF Engine)", "PDF 处理核心 (PDF Engine)", "PDF Processing Engine", "PDF 処理エンジン", "PDF 처리 엔진"),
                ("engine_ppt", "PowerPoint 轉換器 (PowerPoint)", "PowerPoint 转换器 (PowerPoint)", "PowerPoint Converter", "PowerPoint 変換器", "PowerPoint 변환기"),
                ("engine_word", "Word 轉換器 (Word)", "Word 转换器 (Word)", "Word Converter", "Word 変換器", "Word 변환기"),
                ("engine_excel", "Excel 轉換器 (Excel)", "Excel 转换器 (Excel)", "Excel Converter", "Excel 変換器", "Excel 변환기"),
                ("engine_libreoffice", "LibreOffice 離線引擎", "LibreOffice 离线引擎", "LibreOffice Offline Engine", "LibreOffice オフラインエンジン", "LibreOffice 오프라인 엔진"),
                ("engine_ready", "已就緒", "已就绪", "Ready", "準備完了", "준비 완료"),
                ("engine_office_not_installed", "Office 未安裝", "Office 未安装", "Office Not Installed", "Office 未インストール", "Office 미설치"),
                ("setting_engine_title", "Office 轉檔引擎", "Office 转档引擎", "Office Conversion Engine", "Office 変換エンジン", "Office 변환 엔진"),
                ("setting_engine_desc", "選擇 Word、Excel、PowerPoint 轉 PDF 時使用的引擎", "选择 Word、Excel、PowerPoint 转 PDF 时使用的引擎", "Choose the engine used for Word, Excel, and PowerPoint to PDF conversion", "Word、Excel、PowerPoint から PDF への変換に使うエンジンを選択します", "Word, Excel, PowerPoint를 PDF로 변환할 때 사용할 엔진을 선택합니다"),
                ("setting_engine_auto", "自動", "自动", "Auto", "自動", "자동"),
                ("setting_engine_microsoft", MicrosoftOfficeLabel, MicrosoftOfficeLabel, MicrosoftOfficeLabel, MicrosoftOfficeLabel, MicrosoftOfficeLabel),
                ("setting_engine_libreoffice", LibreOfficeLabel, LibreOfficeLabel, LibreOfficeLabel, LibreOfficeLabel, LibreOfficeLabel),
                ("setting_libreoffice_ready", "LibreOffice 已就緒", "LibreOffice 已就绪", "LibreOffice ready", "LibreOffice 準備完了", "LibreOffice 준비 완료"),
                ("setting_libreoffice_missing", "LibreOffice 尚未設定", "LibreOffice 尚未设置", "LibreOffice is not configured", "LibreOffice は未設定です", "LibreOffice가 설정되지 않았습니다"),
                ("setting_libreoffice_optional", "Microsoft Office 已就緒；LibreOffice 可作為免費備援引擎。", "Microsoft Office 已就绪；LibreOffice 可作为免费备用引擎。", "Microsoft Office is ready; LibreOffice can be used as a free fallback engine.", "Microsoft Office は準備完了です。LibreOffice は無料の予備エンジンとして使用できます。", "Microsoft Office가 준비되었습니다. LibreOffice는 무료 예비 엔진으로 사용할 수 있습니다."),
                ("setting_libreoffice_browse", "手動指定位置", "手动指定位置", "Choose location", "場所を手動指定", "위치 수동 지정"),
                ("setting_libreoffice_browse_title", "選擇 LibreOffice soffice.exe", "选择 LibreOffice soffice.exe", "Select LibreOffice soffice.exe", "LibreOffice soffice.exe を選択", "LibreOffice soffice.exe 선택"),
                ("setting_libreoffice_invalid", "請選擇 LibreOffice 的 soffice.exe。", "请选择 LibreOffice 的 soffice.exe。", "Please select LibreOffice soffice.exe.", "LibreOffice の soffice.exe を選択してください。", "LibreOffice의 soffice.exe를 선택하세요."),
                ("setting_libreoffice_download", "取得 LibreOffice", "获取 LibreOffice", "Get LibreOffice", "LibreOffice を取得", "LibreOffice 받기"),
                ("setting_libreoffice_download_ready", "LibreOffice 已安裝並啟用：\n{0}", "LibreOffice 已安装并启用：\n{0}", "LibreOffice is installed and enabled:\n{0}", "LibreOffice をインストールして有効にしました：\n{0}", "LibreOffice 설치 및 사용 설정 완료:\n{0}"),
                ("setting_libreoffice_install_restart_required", "LibreOffice 已安裝，但 Windows 需要重新啟動才會完全完成設定。\n{0}", "LibreOffice 已安装，但 Windows 需要重新启动才会完全完成设置。\n{0}", "LibreOffice is installed, but Windows needs a restart to finish configuration.\n{0}", "LibreOffice をインストールしましたが、設定を完了するには Windows の再起動が必要です。\n{0}", "LibreOffice가 설치되었지만 설정을 완료하려면 Windows를 다시 시작해야 합니다.\n{0}"),
                ("setting_libreoffice_download_failed", "LibreOffice 連線、下載、安裝或驗證失敗：\n{0}", "LibreOffice 连接、下载、安装或验证失败：\n{0}", "LibreOffice connection, download, installation, or verification failed:\n{0}", "LibreOffice への接続、ダウンロード、インストール、または検証に失敗しました：\n{0}", "LibreOffice 연결, 다운로드, 설치 또는 검증 실패:\n{0}"),
                ("setting_libreoffice_download_starting", "正在準備下載 LibreOffice...", "正在准备下载 LibreOffice...", "Preparing LibreOffice download...", "LibreOffice のダウンロードを準備しています...", "LibreOffice 다운로드를 준비 중..."),
                ("setting_libreoffice_reinstall_starting", "正在準備重新安裝 LibreOffice...", "正在准备重新安装 LibreOffice...", "Preparing LibreOffice reinstall...", "LibreOffice の再インストールを準備しています...", "LibreOffice 재설치를 준비 중..."),
                ("setting_libreoffice_download_progress", "正在下載 LibreOffice... {0}%", "正在下载 LibreOffice... {0}%", "Downloading LibreOffice... {0}%", "LibreOffice をダウンロード中... {0}%", "LibreOffice 다운로드 중... {0}%"),
                ("setting_libreoffice_verifying", "正在驗證 LibreOffice 安裝檔...", "正在验证 LibreOffice 安装文件...", "Verifying LibreOffice installer...", "LibreOffice インストーラーを検証しています...", "LibreOffice 설치 파일을 검증 중..."),
                ("setting_libreoffice_installing", "正在安裝 LibreOffice...", "正在安装 LibreOffice...", "Installing LibreOffice...", "LibreOffice をインストール中...", "LibreOffice 설치 중..."),
                ("setting_libreoffice_download_in_progress", "LibreOffice 正在下載、安裝或移除中，請稍候。", "LibreOffice 正在下载、安装或移除中，请稍候。", "LibreOffice is already downloading, installing, or being removed. Please wait.", "LibreOffice のダウンロード、インストール、または削除を実行中です。お待ちください。", "LibreOffice 다운로드, 설치 또는 제거가 진행 중입니다. 잠시 기다려 주세요."),
                ("setting_libreoffice_validated", "LibreOffice 驗證成功：\n{0}", "LibreOffice 验证成功：\n{0}", "LibreOffice validated:\n{0}", "LibreOffice の検証に成功しました：\n{0}", "LibreOffice 검증 성공:\n{0}"),
                ("setting_libreoffice_validation_failed", "LibreOffice 安裝不完整。請重新安裝 LibreOffice，或選擇完整安裝目錄中的 soffice.exe。", "LibreOffice 安装不完整。请重新安装 LibreOffice，或选择完整安装目录中的 soffice.exe。", "LibreOffice installation is incomplete. Reinstall LibreOffice, or choose soffice.exe from a complete installation folder.", "LibreOffice のインストールが不完全です。再インストールするか、完全なインストール先の soffice.exe を選択してください。", "LibreOffice 설치가 완전하지 않습니다. LibreOffice를 다시 설치하거나 전체 설치 폴더의 soffice.exe를 선택하세요."),
                ("setting_libreoffice_update", "更新 LibreOffice", "更新 LibreOffice", "Update LibreOffice", "LibreOffice を更新", "LibreOffice 업데이트"),
                ("setting_libreoffice_reinstall", "重新安裝 LibreOffice", "重新安装 LibreOffice", "Reinstall LibreOffice", "LibreOffice を再インストール", "LibreOffice 재설치"),
                ("setting_libreoffice_uninstall", "移除 LibreOffice", "移除 LibreOffice", "Remove LibreOffice", "LibreOffice を削除", "LibreOffice 제거"),
                ("setting_libreoffice_uninstall_confirm", "Clickra 會在背景移除系統中的 LibreOffice，並清除 Clickra 的 LibreOffice 設定。移除期間可能會要求系統權限。是否繼續？", "Clickra 会在后台移除系统中的 LibreOffice，并清除 Clickra 的 LibreOffice 设置。移除期间可能会要求系统权限。是否继续？", "Clickra will remove LibreOffice in the background and clear Clickra's LibreOffice settings. Windows may ask for permission. Continue?", "Clickra がバックグラウンドで LibreOffice を削除し、Clickra の LibreOffice 設定を消去します。Windows が権限を要求する場合があります。続行しますか？", "Clickra가 백그라운드에서 LibreOffice를 제거하고 Clickra의 LibreOffice 설정을 지웁니다. Windows 권한 요청이 표시될 수 있습니다. 계속하시겠습니까?"),
                (KeyLibreOfficeExternalNote, "這台電腦上的 LibreOffice 不是由 Clickra 安裝，Clickra 不會移除它。如需移除，請使用 Windows 的「應用程式與功能」。", "这台电脑上的 LibreOffice 不是由 Clickra 安装，Clickra 不会移除它。如需移除，请使用 Windows 的“应用和功能”。", "This LibreOffice was not installed by Clickra, so Clickra will not remove it. Use Windows Settings > Apps to remove it yourself.", "このコンピューターの LibreOffice は Clickra がインストールしたものではありません。Clickra は削除しません。削除する場合は Windows の「アプリと機能」をご利用ください。", "이 컴퓨터의 LibreOffice는 Clickra가 설치한 것이 아니므로 Clickra가 제거하지 않습니다. 제거하려면 Windows의 '앱 및 기능'을 사용하세요."),
                (KeyLibreOfficeExternalHint, "未由 Clickra 安裝：請改用 Windows 的「應用程式與功能」移除。", "非 Clickra 安装：请改用 Windows 的“应用和功能”移除。", "Not installed by Clickra: remove it from Windows Settings > Apps.", "Clickra 未インストール：Windows の「アプリと機能」から削除してください。", "Clickra가 설치하지 않음: Windows의 '앱 및 기능'에서 제거하세요."),
                ("setting_libreoffice_uninstalling", "正在背景移除 LibreOffice...", "正在后台移除 LibreOffice...", "Removing LibreOffice in the background...", "バックグラウンドで LibreOffice を削除しています...", "백그라운드에서 LibreOffice 제거 중..."),
                ("setting_libreoffice_uninstall_ready", "LibreOffice 已移除，Clickra 已改回自動引擎。", "LibreOffice 已移除，Clickra 已切回自动引擎。", "LibreOffice has been removed. Clickra switched back to Auto.", "LibreOffice を削除しました。Clickra は自動エンジンに戻りました。", "LibreOffice가 제거되었습니다. Clickra가 자동 엔진으로 돌아갔습니다."),
                ("setting_libreoffice_uninstall_restart_required", "LibreOffice 已排程移除，Clickra 已改回自動引擎。請重新啟動 Windows 以完成移除。", "LibreOffice 已安排移除，Clickra 已切回自动引擎。请重新启动 Windows 以完成移除。", "LibreOffice removal is scheduled. Clickra switched back to Auto. Restart Windows to finish removal.", "LibreOffice の削除を予約しました。Clickra は自動エンジンに戻りました。削除を完了するには Windows を再起動してください。", "LibreOffice 제거가 예약되었습니다. Clickra가 자동 엔진으로 돌아갔습니다. 제거를 완료하려면 Windows를 다시 시작하세요."),
                ("setting_libreoffice_removal_pending", "LibreOffice 正在等待 Windows 重新啟動以完成移除。", "LibreOffice 正在等待 Windows 重新启动以完成移除。", "LibreOffice is waiting for Windows to restart and finish removal.", "LibreOffice は Windows の再起動後に削除が完了します。", "LibreOffice가 Windows 재시작 후 제거를 완료하도록 대기 중입니다."),
                ("setting_libreoffice_uninstall_failed", "LibreOffice 移除失敗：\n{0}", "LibreOffice 移除失败：\n{0}", "LibreOffice removal failed:\n{0}", "LibreOffice の削除に失敗しました：\n{0}", "LibreOffice 제거 실패:\n{0}"),
                ("setting_libreoffice_already_current", "目前已安裝的 LibreOffice 已是 Clickra 建議版本（{0}），不需要更新。", "当前已安装的 LibreOffice 已是 Clickra 建议版本（{0}），不需要更新。", "The installed LibreOffice is already Clickra's recommended version ({0}). No update is needed.", "インストール済みの LibreOffice は Clickra 推奨バージョン（{0}）です。更新は不要です。", "설치된 LibreOffice가 이미 Clickra 권장 버전({0})입니다. 업데이트가 필요 없습니다."),
                ("setting_microsoft_ready", "Microsoft Office 已就緒", "Microsoft Office 已就绪", "Microsoft Office ready", "Microsoft Office 準備完了", "Microsoft Office 준비 완료"),
                ("setting_microsoft_missing", "Microsoft Office 尚未安裝或不完整", "Microsoft Office 尚未安装或不完整", "Microsoft Office is not installed or is incomplete", "Microsoft Office が未インストール、または不完全です", "Microsoft Office가 설치되지 않았거나 완전하지 않습니다"),
                ("setting_engine_auto_using", "自動：使用 {0}", "自动：使用 {0}", "Auto: using {0}", "自動：{0} を使用", "자동: {0} 사용"),
                ("setting_engine_none_available", "沒有可用的 Office 轉檔引擎。請安裝 Microsoft Office 或取得 LibreOffice。", "没有可用的 Office 转换引擎。请安装 Microsoft Office 或获取 LibreOffice。", "No Office conversion engine is available. Install Microsoft Office or get LibreOffice.", "利用可能な Office 変換エンジンがありません。Microsoft Office をインストールするか、LibreOffice を取得してください。", "사용 가능한 Office 변환 엔진이 없습니다. Microsoft Office를 설치하거나 LibreOffice를 받으세요."),
                ("overview_tip", "提示：直接在檔案總管選取檔案，右鍵即可呼叫 Clickra 選單進行轉換。", "提示：直接在文件资源管理器中选择文件，右键即可呼叫 Clickra 菜单进行转换。", "Tip: Select files in File Explorer, right-click, and select Clickra to convert.", "ヒント：エクスプローラーでファイルを選択し、右クリックして Clickra から変換します。", "팁: 파일 탐색기에서 파일을 선택하고 마우스 오른쪽 버튼을 클릭하여 Clickra로 변환하세요."),
                ("cmd_word_to_pdf", WordToPdfLabel, WordToPdfLabel, WordToPdfLabel, WordToPdfLabel, WordToPdfLabel),
                ("cmd_excel_to_pdf", ExcelToPdfLabel, ExcelToPdfLabel, ExcelToPdfLabel, ExcelToPdfLabel, ExcelToPdfLabel),
                ("cmd_ppt_to_pdf", PptToPdfLabel, PptToPdfLabel, PptToPdfLabel, PptToPdfLabel, PptToPdfLabel),
                ("cmd_md_to_pdf", MarkdownToPdfLabel, MarkdownToPdfLabel, MarkdownToPdfLabel, MarkdownToPdfLabel, MarkdownToPdfLabel),
                ("cmd_md_to_word", MarkdownToWordLabel, MarkdownToWordLabel, MarkdownToWordLabel, MarkdownToWordLabel, MarkdownToWordLabel),
                ("md_options_title", "Markdown 轉換選項", "Markdown 转换选项", "Markdown conversion options", "Markdown 変換オプション", "Markdown 변환 옵션"),
                ("md_options_hint", "已套用預設排版；需要不同呈現時再調整即可。", "已应用默认排版；需要不同呈现时再调整即可。", "The default layout is selected. Change these options only when you need a different presentation.", "既定のレイアウトが選択されています。別の表示が必要な場合のみ変更してください。", "기본 레이아웃이 선택되어 있습니다. 다른 표현이 필요할 때만 변경하세요."),
                ("md_options_style", "樣式", "样式", "Style", "スタイル", "스타일"),
                ("md_options_style_default", "預設", "默认", "Default", "デフォルト", "기본"),
                ("md_options_style_minimal", "極簡", "极简", "Minimal", "ミニマル", "미니멀"),
                ("md_options_style_academic", "學術", "学术", "Academic", "学術", "학술"),
                ("md_options_paper", "紙張", "纸张", "Paper", "用紙", "용지"),
                ("md_options_text_size", "文字大小", "文字大小", "Text size", "文字サイズ", "텍스트 크기"),
                ("md_options_text_small", "小", "小", "Small", "小", "작게"),
                ("md_options_text_standard", "標準", "标准", "Standard", "標準", "표준"),
                ("md_options_text_large", "大", "大", "Large", "大", "크게"),
                ("md_options_code_theme", "程式碼區塊", "代码区块", "Code blocks", "コードブロック", "코드 블록"),
                ("md_options_code_dark", "深色", "深色", "Dark", "ダーク", "어둡게"),
                ("md_options_code_light", "淺色", "浅色", "Light", "ライト", "밝게"),
                ("md_options_layout_source", "版面來源", "版面来源", "Layout source", "レイアウト元", "레이아웃 원본"),
                ("md_options_layout_clickra", "Clickra 樣式", "Clickra 样式", "Clickra styles", "Clickra スタイル", "Clickra 스타일"),
                ("md_options_layout_word", "Word 範本", "Word 模板", "Word template", "Word テンプレート", "Word 템플릿"),
                ("md_options_template", "Word 範本", "Word 模板", "Word template", "Word テンプレート", "Word 템플릿"),
                ("md_options_template_browse", "匯入 DOCX...", "导入 DOCX...", "Import DOCX...", "DOCX を読み込む...", "DOCX 가져오기..."),
                ("md_options_template_none", "未匯入 Word 範本", "未导入 Word 模板", "No Word template imported", "Word テンプレート未読込", "Word 템플릿을 가져오지 않음"),
                ("md_options_template_required", "請先選擇 DOCX 範本", "请先选择 DOCX 模板", "Choose a DOCX template first", "先に DOCX テンプレートを選択してください", "먼저 DOCX 템플릿을 선택하세요"),
                ("md_options_template_selected", "已選擇：{0}", "已选择：{0}", "Selected: {0}", "選択済み：{0}", "선택됨: {0}"),
                ("md_options_template_invalid", "Word 範本無效或不受支援，請選擇其他 DOCX。", "Word 模板无效或不受支持，请选择其他 DOCX。", "The Word template is invalid or unsupported. Choose another DOCX file.", "Word テンプレートが無効または未対応です。別の DOCX を選択してください。", "Word 템플릿이 잘못되었거나 지원되지 않습니다. 다른 DOCX 파일을 선택하세요."),
                ("md_options_template_picker", "匯入 Word 樣式範本", "导入 Word 样式模板", "Import Word style template", "Word スタイルテンプレートを読み込む", "Word 스타일 템플릿 가져오기"),
                ("md_options_convert", "開始轉換", "开始转换", "Convert", "変換", "변환"),
                ("cmd_merge_pdf", "合併 PDF", "合并 PDF", "Merge PDF", "PDF 結合", "PDF 병합"),
                ("cmd_img_to_pdf", "圖片 → PDF", "图片 → PDF", "Image → PDF", "画像 → PDF", "이미지 → PDF"),
                ("cmd_merge_img", "圖片合併", "图片合并", "Merge Images", "画像結合", "이미지 병합"),
                ("cmd_stitch_img", "圖片拼接", "图片拼接", "Stitch Images", "画像結合 (縦/横)", "이미지 이어붙이기"),
                ("tab_convert", "轉檔", "转档", "Convert", "変換", "변환"),
                ("convert_drag_drop_hint", "拖曳檔案至此，或點擊此處選取檔案", "拖拽文件至此，或点击此处选择文件", "Drag files here, or click to browse", "ここにファイルをドラッグするか、クリックして選択", "여기에 파일을 끌어다 놓거나 클릭하여 선택"),
                ("convert_drag_drop_sub", "支援 Office、Markdown、PDF 及多種圖片格式", "支持 Office、Markdown、PDF 及多种图片格式", "Supports Office, Markdown, PDF, and image files", "Office、Markdown、PDF、および画像ファイルをサポート", "Office, Markdown, PDF 및 이미지 파일 지원"),
                ("convert_selected_count", "已選取 {0} 個檔案", "已选择 {0} 个文件", "{0} files selected", "{0} 個のファイルが選択されました", "{0}개의 파일이 선택됨"),
                ("convert_clear", "清除", "清除", "Clear", "クリア", "지우기"),
                ("convert_start", "開始轉檔", "开始转档", "Start Conversion", "変換開始", "변환 시작"),
                ("convert_group_office", "文件轉 PDF", "文档转 PDF", "Documents to PDF", "ドキュメントから PDF", "문서를 PDF로"),
                ("convert_group_pdf", "PDF 工具", "PDF 工具", "PDF Tools", "PDF ツール", "PDF 도구"),
                ("convert_group_image", "圖片工具", "图片工具", "Image Tools", "画像ツール", "이미지 도구"),
                ("convert_err_min_files", "此功能至少需要 {0} 個檔案！", "此功能至少需要 {0} 个文件！", "This action requires at least {0} files!", "この機能には少なくとも {0} 個のファイルが必要です！", "이 작업은 최소 {0}개의 파일이 필요합니다!"),
                ("convert_err_invalid_ext", "檔案格式不符，請重新選取！", "文件格式不符，请重新选择！", "Invalid file extensions detected!", "無効なファイル形式が含まれています！", "잘못된 파일 확장자가 감지되었습니다!"),
                ("tab_about", "關於", "关于", "About", "紹介", "정보"),
                ("about_desc_title", "專案說明", "项目说明", "About Project", "プロジェクトについて", "프로젝트 정보"),
                ("about_desc_body", "Clickra 是一款專為 Windows 11 量身打造的極致輕量、現代化右鍵轉檔工具。\n底層採用先進的 C# NativeAOT 技術，擺脫笨重的執行環境，實現小於 0.01 秒的瞬時啟動與免安裝極致體驗，與系統完美融為一體。", "Clickra 是一款专为 Windows 11 量身打造的极致轻量、现代化右键转档工具。\n底层采用先进的 C# NativeAOT 技术，摆脱臃肿的运行环境，实现小于 0.01 秒的瞬时启动与免安装极致体验，与系统完美融为一体。", "Clickra is a premium, ultra-lightweight modern context menu utility designed for Windows 11.\nBuilt with C# NativeAOT, it skips all runtime overhead to deliver sub-10ms instantaneous startup and a zero-dependency user experience that feels like a native OS feature.", "Clickra は、Windows 11 のために設計された極めて軽量でモダンな右鍵コンテキストメニュー変換ツールです。\nC# NativeAOT 技術を採用し、不要なランタイムを排除することで、0.01秒未満の瞬間起動と完全なスタンドアロン動作を実現しました。", "Clickra는 Windows 11을 위해 특별히 설계된 초경량 현대식 마우스 오른쪽 버튼 변환 도구입니다.\n최첨단 C# NativeAOT 기술을 적용하여 불필요한 런타임을 배제하고 0.01초 미만의 즉각적인 실행 속도와 무설치 작동을 제공합니다."),
                ("about_collab_title", "協作開發與原始碼", "协作开发与源码", "Collaboration & Source", "コラボレーションとソースコード", "협업 및 소스 코드"),
                ("about_collab_body", "本專案以 Apache 2.0 協議完全開源！我們熱烈歡迎各位開發者加入，共同改善與擴充功能。\n您可以透過 GitHub 提交 Pull Request、回報 Issue，一起打造更實用的 Windows 生態系工具。", "本项目以 Apache 2.0 协议完全开源！我们热烈欢迎各位开发者加入，共同改善与扩充功能。\n您可以通过 GitHub 提交 Pull Request、反馈 Issue，一起打造更实用的 Windows 生态系工具。", "This project is fully open-source under the Apache 2.0 license! We love community contributions.\nVisit our GitHub repository to submit Pull Requests, report issues, or collaborate on building better tools for Windows.", "本プロジェクトは Apache 2.0 ライセンスの下で完全にオープンソース化されています！\nGitHub での Pull Request や Issue の報告を通じて、Windows ユーザーのための優れたツール開発にぜひご協力ください。", "이 프로젝트는 Apache 2.0 라이선스 하에 완전한 오픈 소스로 제공됩니다!\nGitHub 리포지토리에서 Pull Request 제출, Issue 등록을 통해 더 편리한 Windows 환경을 만드는 데 동참해 주세요."),
                ("about_diag_title", "診斷與回報說明", "诊断与反馈说明", "Diagnostics & Support", "診断とサポート", "진단 및 지원"),
                ("about_diag_body", "遇到轉檔失敗或異常嗎？我們為您簡化了回報流程！\n點擊下方按鈕將一鍵開啟 Gmail 線上郵件撰寫，並同步在檔案總管為您選取好日誌檔「history.log」，您只需將該檔案拖曳至郵件中即可快速傳送診斷資訊。", "遇到转档失败或异常吗？我们为您简化了反馈流程！\n点击下方按钮将一键开启 Gmail 网页版邮件撰写，并同步在文件资源管理器中为您选好日志「history.log」，您只需将该文件拖拽至邮件中即可快速发送诊断信息。", "Encountered a conversion issue? We've streamlined the feedback process!\nClick below to open Gmail Web Composer and highlight 'history.log' in File Explorer. Simply drag the highlighted file into Gmail to send us the diagnostic details.", "変換エラーや不具合が発生しましたか？フィードバックの手順を劇的に簡略化しました！\nボタンをクリックすると、Gmail 作成画面が開き、エクスプローラーでログファイル「history.log」が自動選択されます。ファイルをそのままドラッグ＆ドロップして送信してください。", "변환 중 문제가 발생하면 아래 버튼을 누르면 Gmail 작성 창이 열리고 탐색기에서 로그 파일「history.log」가 자동 선택됩니다. 파일을 메일에 드래그 앤 드롭하여 손쉽게 진단 정보를 보내주세요."),
                ("about_btn_open_data_dir", "檢視日誌資料夾", "查看日志文件夹", "Open Log Folder", "ログフォルダを開く", "로그 폴더 열기"),
                ("about_btn_github", "GitHub 專案", "GitHub 项目", "View on GitHub", "GitHub で表示", "GitHub 리포지토리"),
                ("about_btn_gmail", "Gmail 回報", "Gmail 反馈", "Gmail Diagnostics", "Gmail でフィードバック", "Gmail 피드백"),
                ("history_detail_inputs", "輸入路徑", "输入路径", "Input Paths", "入力パス", "입력 경로"),
                ("history_detail_outputs", "輸出路徑", "输出路径", "Output Path", "出力パス", "출력 경로"),
                ("history_detail_time", "轉換時間", "转换时间", "Conversion Time", "変換日時", "변환 시간"),
                ("history_detail_elapsed", "執行耗時", "执行耗时", "Elapsed Time", "処理時間", "소요 시간"),
                ("progress_cancel_confirm", "您確定要取消目前的轉換作業嗎？", "您确定要取消当前的转换作业吗？", "Are you sure you want to cancel the current conversion?", "現在の変換作業をキャンセルしてもよろしいですか？", "현재 변환 작업을 취소하시겠습니까?"),
                ("history_detail_error", "錯誤訊息", "错误信息", "Error Message", "エラーメッセージ", "오류 메시지"),
                ("error_user_aborted", "取消", "取消", "Canceled", "キャンセル", "취소됨"),
                ("progress_tray_hint", "縮至系統匣後仍會在背景繼續執行", "最小化到系统托盘后仍会在后台继续运行", "Keeps running in the background after minimizing to the tray", "トレイに最小化してもバックグラウンドで実行を続けます", "트레이로 최소화해도 백그라운드에서 계속 실행됩니다"),
                ("progress_background", "縮小至系統匣", "最小化到系统托盘", "Minimize to System Tray", "システムトレイに最小化", "시스템 트레이로 최소화"),
                ("error_processing_failed", "處理過程中發生錯誤：\n{0}", "处理过程中发生错误：\n{0}", "An error occurred while processing:\n{0}", "処理中にエラーが発生しました：\n{0}", "처리 중 오류가 발생했습니다:\n{0}"),
                ("error_libreoffice_not_ready", "LibreOffice 引擎尚未就緒。請到「設定」重新取得 LibreOffice，或將 Office 轉檔引擎改回「自動」或「Microsoft Office」。", "LibreOffice 引擎尚未就绪。请到“设置”重新获取 LibreOffice，或将 Office 转换引擎改回“自动”或“Microsoft Office”。", "The LibreOffice engine is not ready. Open Settings and get LibreOffice again, or switch the Office engine back to Auto or Microsoft Office.", "LibreOffice エンジンはまだ準備できていません。設定で LibreOffice を再取得するか、Office 変換エンジンを「自動」または「Microsoft Office」に戻してください。", "LibreOffice 엔진이 아직 준비되지 않았습니다. 설정에서 LibreOffice를 다시 받거나 Office 변환 엔진을 자동 또는 Microsoft Office로 변경하세요."),
                ("error_libreoffice_unusable", "目前的 LibreOffice 無法正常啟動。請到「設定」重新取得 LibreOffice，或手動指定一個可正常執行的 LibreOffice。", "当前的 LibreOffice 无法正常启动。请到“设置”重新获取 LibreOffice，或手动指定一个可正常运行的 LibreOffice。", "The current LibreOffice engine cannot start correctly. Open Settings and get LibreOffice again, or choose a working LibreOffice installation manually.", "現在の LibreOffice は正常に起動できません。設定で LibreOffice を再取得するか、正常に動作する LibreOffice を手動で指定してください。", "현재 LibreOffice를 정상적으로 시작할 수 없습니다. 설정에서 LibreOffice를 다시 받거나 정상 실행되는 LibreOffice를 직접 지정하세요."),
                ("error_microsoftoffice_not_ready", "Microsoft Office 尚未就緒。請安裝對應的 Office 應用程式，或將 Office 轉檔引擎改為「自動」或「LibreOffice」。", "Microsoft Office 尚未就绪。请安装对应的 Office 应用程序，或将 Office 转换引擎改为“自动”或“LibreOffice”。", "Microsoft Office is not ready. Install the required Office app, or switch the Office engine to Auto or LibreOffice.", "Microsoft Office は準備できていません。必要な Office アプリをインストールするか、Office 変換エンジンを「自動」または「LibreOffice」に変更してください。", "Microsoft Office가 준비되지 않았습니다. 필요한 Office 앱을 설치하거나 Office 변환 엔진을 자동 또는 LibreOffice로 변경하세요."),
                ("status_office_fallback_to_libreoffice", "Microsoft {0} 轉換失敗，正在改用 LibreOffice：{1}...", "Microsoft {0} 转换失败，正在改用 LibreOffice：{1}...", "Microsoft {0} conversion failed; switching to LibreOffice: {1}...", "Microsoft {0} の変換に失敗しました。LibreOffice に切り替えています：{1}...", "Microsoft {0} 변환에 실패했습니다. LibreOffice로 전환 중: {1}..."),
                ("status_libreoffice_starting", "正在啟動 LibreOffice 引擎 ({0}/{1})...", "正在启动 LibreOffice 引擎 ({0}/{1})...", "Starting LibreOffice engine ({0}/{1})...", "LibreOffice エンジンを起動しています ({0}/{1})...", "LibreOffice 엔진 시작 중 ({0}/{1})..."),
                ("status_libreoffice_exporting", "正在使用 LibreOffice 匯出 PDF：{0}...", "正在使用 LibreOffice 导出 PDF：{0}...", "Exporting PDF with LibreOffice: {0}...", "LibreOffice で PDF を書き出しています：{0}...", "LibreOffice로 PDF 내보내는 중: {0}..."),
                ("status_libreoffice_completed", "已完成 LibreOffice 轉換：{0}", "已完成 LibreOffice 转换：{0}", "LibreOffice conversion completed: {0}", "LibreOffice 変換が完了しました：{0}", "LibreOffice 변환 완료: {0}"),
                ("setting_pdf_title", "PDF 一鍵翻譯", "PDF 翻译", "PDF One-Click Translation", "PDF 一括翻訳", "PDF 일괄 번역"),
                ("setting_pdf_desc", "設定 PDF 翻譯目標語言", "设置 PDF 翻译语言", "Configure target language for translation", "翻訳の対象言語を設定します", "번역 대상 언어를 설정합니다"),
                ("setting_pdf_lang", "目標語言 (Target Language)", "目标语言", "Target Language", "対象言語 (Target Language)", "대상 언어 (Target Language)"),
                ("cmd_translate_pdf", "PDF 一鍵翻譯", "PDF 翻译", "PDF Translation", "PDF 翻訳", "PDF 번역"),
                ("cmd_decrypt_pdf", "去除 PDF 密碼", "去除 PDF 密码", "Remove PDF Password", "PDF パスワード解除", "PDF 비밀번호 제거"),
                ("pdf_password_title", "輸入 PDF 密碼", "输入 PDF 密码", "Enter PDF Password", "PDF パスワード入力", "PDF 비밀번호 입력"),
                ("pdf_password_prompt", "「{0}」受密碼保護，請輸入開啟密碼：", "「{0}」受密码保护，请输入打开密码：", "\"{0}\" is password protected. Enter open password:", "「{0}」はパスワードで保護されています。パスワードを入力してください：", "「{0}」 파일이 비밀번호로 보호되어 있습니다. 비밀번호를 입력하십시오:"),
                ("pdf_password_retry", "密碼錯誤。請重新輸入「{0}」的密碼：", "密码错误。请重新输入「{0}」的密码：", "Incorrect password. Re-enter password for \"{0}\":", "パスワードが正しくありません。もう一度入力してください：「{0}」", "비밀번호가 잘못되었습니다. 다시 입력하십시오:「{0}」"),
                ("error_pdf_password_quiet", "密碼錯誤或未提供密碼（靜默模式下無法手動輸入密碼）。", "密码错误或未提供密码（静默模式下无法手动输入密码）。", "Incorrect or missing password (cannot prompt for password in quiet mode).", "パスワードが正しくないか入力されていません（サイレントモードではパスワードを入力できません）。", "비밀번호가 잘못되었거나 누락되었습니다 (조용한 모드에서는 비밀번호를 입력할 수 없습니다)."),
                ("pdf_not_encrypted", "此檔案未加密，無須解除密碼。", "此文件未加密，无需解除密码。", "This file is not encrypted; no decryption needed.", "このファイルは暗号化されていません。パスワード解除は不要です。", "이 파일은 암호화되어 있지 않아 비밀번호를 제거할 필요가 없습니다."),
                ("dialog_ok", "確定", "确定", "OK", "確定", "확인"),
                ("dialog_cancel", "取消", "取消", "Cancel", "キャンセル", "취소"),
            };

            RegisterTranslations(data);
        }
    }
}
