using System;
using System.Collections.Generic;

namespace Clickra.Core
{
    public static class Localization
    {
        private const string LangTw = "zh-TW";
        private const string LangCn = "zh-CN";
        private const string LangEn = "en-US";
        private const string LangJa = "ja-JP";
        private const string LangKo = "ko-KR";
        private const string KeyCmdCompressPdf = "cmd_compress_pdf";
        private const string KeyCmdSplitPdf = "cmd_split_pdf";
        private const string KeySplitPdfTitle = "pdf_split_title";
        private const string KeySplitPdfPrompt = "pdf_split_prompt";

        private static readonly Dictionary<string, Dictionary<string, string>> Translations = new(StringComparer.OrdinalIgnoreCase)
        {
            [LangTw] = new(StringComparer.OrdinalIgnoreCase)
            {
                ["tab_status"] = "狀態",
                ["tab_history"] = "歷史",
                ["tab_settings"] = "設定",
                ["setting_silent_title"] = "背景靜默轉檔",
                ["setting_silent_desc"] = "在右鍵選單點擊時直接於背景處理，不顯示進度視窗",
                ["setting_notify_title"] = "顯示轉換通知",
                ["setting_notify_desc"] = "作業完成或失敗後，於系統右下角彈出 Windows Toast 通知",
                ["setting_output_title"] = "預設輸出路徑",
                ["setting_output_desc"] = "選擇轉換後 PDF 與圖片預設的儲存位置",
                ["setting_output_same_as_source"] = "與來源相同",
                ["setting_output_desktop"] = "桌面",
                ["setting_output_downloads"] = "下載",
                ["setting_output_custom"] = "自訂...",
                ["setting_output_selected_path"] = "已選取路徑",
                ["setting_output_browse_title"] = "選擇預設輸出資料夾",
                ["overview_engine_status"] = "轉換引擎狀態",
                ["overview_stats"] = "轉換統計",
                ["overview_stat_total"] = "總轉換次數",
                ["overview_stat_success"] = "成功次數",
                ["overview_stat_failed"] = "失敗次數",
                ["overview_office_conversion"] = "Office 轉檔",
                ["overview_engine_active"] = "使用 {0}",
                ["overview_engine_unavailable"] = "{0} 尚未就緒",
                ["history_clear"] = "清除紀錄",
                ["history_clear_confirm"] = "您確定要清除所有的轉換歷史紀錄嗎？",
                ["history_empty"] = "尚無任何轉換紀錄。",
                ["status_pending"] = "等待中",
                ["status_converting"] = "轉換中",
                ["status_success"] = "成功",
                ["status_failed"] = "失敗",
                ["status_error"] = "錯誤",
                ["label_files"] = "個檔案",
                ["setting_lang_title"] = "介面語言",
                ["setting_lang_desc"] = "選擇 Dashboard 的顯示語言",
                ["search_lang_placeholder"] = "搜尋語言 / Search...",
                ["engine_pdf"] = "PDF 處理核心 (PDF Engine)",
                ["engine_ppt"] = "PowerPoint 轉換器 (PowerPoint)",
                ["engine_word"] = "Word 轉換器 (Word)",
                ["engine_excel"] = "Excel 轉換器 (Excel)",
                ["engine_libreoffice"] = "LibreOffice 離線引擎",
                ["engine_ready"] = "已就緒",
                ["engine_office_not_installed"] = "Office 未安裝",
                ["setting_engine_title"] = "Office 轉檔引擎",
                ["setting_engine_desc"] = "選擇 Word、Excel、PowerPoint 轉 PDF 時使用的引擎",
                ["setting_engine_auto"] = "自動",
                ["setting_engine_microsoft"] = "Microsoft Office",
                ["setting_engine_libreoffice"] = "LibreOffice",
                ["setting_libreoffice_ready"] = "LibreOffice 已就緒",
                ["setting_libreoffice_missing"] = "LibreOffice 尚未設定",
                ["setting_libreoffice_optional"] = "Microsoft Office 已就緒；LibreOffice 可作為免費備援引擎。",
                ["setting_libreoffice_browse"] = "手動指定位置",
                ["setting_libreoffice_browse_title"] = "選擇 LibreOffice soffice.exe",
                ["setting_libreoffice_invalid"] = "請選擇 LibreOffice 的 soffice.exe。",
                ["setting_libreoffice_download"] = "取得 LibreOffice",
                ["setting_libreoffice_download_prompt"] = "Clickra 將下載並驗證 LibreOffice 官方 MSI 安裝程式。\n\n版本：{0}\n版本類型：{1}\n下載大小：約 {2}\n安裝位置：{3}\nSHA256：{4}\n\n接下來 Windows 可能會要求系統安裝權限。安裝完成後，LibreOffice 也可在 Clickra 以外正常使用。是否繼續？",
                ["setting_libreoffice_download_ready"] = "LibreOffice 已安裝並啟用：\n{0}",
                ["setting_libreoffice_install_restart_required"] = "LibreOffice 已安裝，但 Windows 需要重新啟動才會完全完成設定。\n{0}",
                ["setting_libreoffice_download_failed"] = "LibreOffice 連線、下載、安裝或驗證失敗：\n{0}",
                ["setting_libreoffice_download_starting"] = "正在準備下載 LibreOffice...",
                ["setting_libreoffice_reinstall_starting"] = "正在準備重新安裝 LibreOffice...",
                ["setting_libreoffice_download_progress"] = "正在下載 LibreOffice... {0}%",
                ["setting_libreoffice_verifying"] = "正在驗證 LibreOffice 安裝檔...",
                ["setting_libreoffice_installing"] = "正在安裝 LibreOffice...",
                ["setting_libreoffice_download_in_progress"] = "LibreOffice 正在下載、安裝或移除中，請稍候。",
                ["setting_libreoffice_validated"] = "LibreOffice 驗證成功：\n{0}",
                ["setting_libreoffice_validation_failed"] = "LibreOffice 安裝不完整。請重新安裝 LibreOffice，或選擇完整安裝目錄中的 soffice.exe。",
                ["setting_libreoffice_update"] = "更新 LibreOffice",
                ["setting_libreoffice_reinstall"] = "重新安裝 LibreOffice",
                ["setting_libreoffice_uninstall"] = "移除 LibreOffice",
                ["setting_libreoffice_uninstall_confirm"] = "Clickra 會在背景移除系統中的 LibreOffice，並清除 Clickra 的 LibreOffice 設定。移除期間可能會要求系統權限。是否繼續？",
                ["setting_libreoffice_uninstalling"] = "正在背景移除 LibreOffice...",
                ["setting_libreoffice_uninstall_ready"] = "LibreOffice 已移除，Clickra 已改回自動引擎。",
                ["setting_libreoffice_uninstall_restart_required"] = "LibreOffice 已排程移除，Clickra 已改回自動引擎。請重新啟動 Windows 以完成移除。",
                ["setting_libreoffice_removal_pending"] = "LibreOffice 正在等待 Windows 重新啟動以完成移除。",
                ["setting_libreoffice_uninstall_failed"] = "LibreOffice 移除失敗：\n{0}",
                ["setting_libreoffice_already_current"] = "目前已安裝的 LibreOffice 已是 Clickra 建議版本（{0}），不需要更新。",
                ["setting_microsoft_ready"] = "Microsoft Office 已就緒",
                ["setting_microsoft_missing"] = "Microsoft Office 尚未安裝或不完整",
                ["setting_engine_auto_using"] = "自動：使用 {0}",
                ["setting_engine_none_available"] = "沒有可用的 Office 轉檔引擎。請安裝 Microsoft Office 或取得 LibreOffice。",
                ["overview_tip"] = "提示：直接在檔案總管選取檔案，右鍵即可呼叫 Clickra 選單進行轉換。",
                ["cmd_word_to_pdf"] = "Word → PDF",
                ["cmd_excel_to_pdf"] = "Excel → PDF",
                ["cmd_ppt_to_pdf"] = "PPT → PDF",
                ["cmd_merge_pdf"] = "合併 PDF",
                ["cmd_img_to_pdf"] = "圖片 → PDF",
                ["cmd_merge_img"] = "圖片合併",
                ["cmd_stitch_img"] = "圖片拼接",
                ["tab_convert"] = "轉檔",
                ["convert_drag_drop_hint"] = "拖曳檔案至此，或點擊此處選取檔案",
                ["convert_drag_drop_sub"] = "支援 Word, PPT, PDF 及多種圖片格式",
                ["convert_selected_count"] = "已選取 {0} 個檔案",
                ["convert_clear"] = "清除",
                ["convert_start"] = "開始轉檔",
                ["convert_group_office"] = "Office 轉 PDF",
                ["convert_group_pdf"] = "PDF 工具",
                ["convert_group_image"] = "圖片工具",
                ["convert_err_min_files"] = "此功能至少需要 {0} 個檔案！",
                ["convert_err_invalid_ext"] = "檔案格式不符，請重新選取！",
                ["tab_about"] = "關於",
                ["about_desc_title"] = "專案說明",
                ["about_desc_body"] = "Clickra 是一款專為 Windows 11 量身打造的極致輕量、現代化右鍵轉檔工具。\n底層採用先進的 C# NativeAOT 技術，擺脫笨重的執行環境，實現小於 0.01 秒的瞬時啟動與免安裝極致體驗，與系統完美融為一體。",
                ["about_collab_title"] = "協作開發與原始碼",
                ["about_collab_body"] = "本專案以 Apache 2.0 協議完全開源！我們熱烈歡迎各位開發者加入，共同改善與擴充功能。\n您可以透過 GitHub 提交 Pull Request、回報 Issue，一起打造更實用的 Windows 生態系工具。",
                ["about_diag_title"] = "診斷與回報說明",
                ["about_diag_body"] = "遇到轉檔失敗或異常嗎？我們為您簡化了回報流程！\n點擊下方按鈕將一鍵開啟 Gmail 線上郵件撰寫，並同步在檔案總管為您選取好日誌檔「history.log」，您只需將該檔案拖曳至郵件中即可快速傳送診斷資訊。",
                ["about_btn_open_data_dir"] = "檢視日誌資料夾",
                ["about_btn_github"] = "GitHub 專案",
                ["about_btn_gmail"] = "Gmail 回報",
                ["history_detail_inputs"] = "輸入路徑",
                ["history_detail_outputs"] = "輸出路徑",
                ["history_detail_time"] = "轉換時間",
                ["history_detail_elapsed"] = "執行耗時",
                ["progress_cancel_confirm"] = "您確定要取消目前的轉換作業嗎？",
                ["history_detail_error"] = "錯誤訊息",
                ["error_user_aborted"] = "取消",
                ["progress_tray_hint"] = "按 — 或工作列圖示可縮至系統匣繼續執行",
                ["progress_background"] = "縮小至系統匣",
                ["error_processing_failed"] = "處理過程中發生錯誤：\n{0}",
                ["error_libreoffice_not_ready"] = "LibreOffice 引擎尚未就緒。請到「設定」重新取得 LibreOffice，或將 Office 轉檔引擎改回「自動」或「Microsoft Office」。",
                ["error_libreoffice_unusable"] = "目前的 LibreOffice 無法正常啟動。請到「設定」重新取得 LibreOffice，或手動指定一個可正常執行的 LibreOffice。",
                ["error_microsoftoffice_not_ready"] = "Microsoft Office 尚未就緒。請安裝對應的 Office 應用程式，或將 Office 轉檔引擎改為「自動」或「LibreOffice」。",
                ["status_office_fallback_to_libreoffice"] = "Microsoft {0} 轉換失敗，正在改用 LibreOffice：{1}...",
                ["status_libreoffice_starting"] = "正在啟動 LibreOffice 引擎 ({0}/{1})...",
                ["status_libreoffice_exporting"] = "正在使用 LibreOffice 匯出 PDF：{0}...",
                ["status_libreoffice_completed"] = "已完成 LibreOffice 轉換：{0}",
                ["setting_pdf_title"] = "PDF 一鍵翻譯",
                ["setting_pdf_desc"] = "設定 PDF 翻譯目標語言",
                ["setting_pdf_lang"] = "目標語言 (Target Language)",
                ["cmd_translate_pdf"] = "PDF 一鍵翻譯",
                ["cmd_decrypt_pdf"] = "去除 PDF 密碼",
                [KeyCmdSplitPdf] = "分割 PDF",
                [KeySplitPdfTitle] = "輸入 PDF 分割頁碼範圍",
                [KeySplitPdfPrompt] = "請輸入分頁範圍（例如 1-5, 8 或 all 拆分為單頁檔）：",
                ["pdf_password_title"] = "輸入 PDF 密碼",
                ["pdf_password_prompt"] = "「{0}」受密碼保護，請輸入開啟密碼：",
                ["pdf_password_retry"] = "密碼錯誤。請重新輸入「{0}」的密碼：",
                ["error_pdf_password_quiet"] = "密碼錯誤或未提供密碼（靜默模式下無法手動輸入密碼）。",
                ["pdf_not_encrypted"] = "此檔案未加密，無須解除密碼。",
                ["dialog_ok"] = "確定",
                ["dialog_cancel"] = "取消"
            },
            [LangCn] = new(StringComparer.OrdinalIgnoreCase)
            {
                ["tab_status"] = "状态",
                ["tab_history"] = "历史",
                ["tab_settings"] = "设置",
                ["setting_silent_title"] = "背景静默转档",
                ["setting_silent_desc"] = "在右键菜单点击时直接于背景处理，不显示进度窗口",
                ["setting_notify_title"] = "显示转换通知",
                ["setting_notify_desc"] = "作业完成或失败后，于系统右下角弹出 Windows Toast 通知",
                ["setting_output_title"] = "默认输出路径",
                ["setting_output_desc"] = "选择转换后 PDF 与图片默认的存储位置",
                ["setting_output_same_as_source"] = "与来源相同",
                ["setting_output_desktop"] = "桌面",
                ["setting_output_downloads"] = "下载",
                ["setting_output_custom"] = "自定义...",
                ["setting_output_selected_path"] = "已选择路径",
                ["setting_output_browse_title"] = "选择默认输出文件夹",
                ["overview_engine_status"] = "转换引擎状态",
                ["overview_stats"] = "转换统计",
                ["overview_stat_total"] = "总转换次数",
                ["overview_stat_success"] = "成功次数",
                ["overview_stat_failed"] = "失败次数",
                ["overview_office_conversion"] = "Office 转换",
                ["overview_engine_active"] = "使用 {0}",
                ["overview_engine_unavailable"] = "{0} 尚未就绪",
                ["history_clear"] = "清除记录",
                ["history_clear_confirm"] = "您确定要清除所有的转换历史记录吗？",
                ["history_empty"] = "尚无任何转换记录。",
                ["status_pending"] = "等待中",
                ["status_converting"] = "转换中",
                ["status_success"] = "成功",
                ["status_failed"] = "失败",
                ["status_error"] = "错误",
                ["label_files"] = "个文件",
                ["setting_lang_title"] = "界面语言",
                ["setting_lang_desc"] = "选择 Dashboard 的显示语言",
                ["search_lang_placeholder"] = "搜索语言...",
                ["engine_pdf"] = "PDF 处理核心 (PDF Engine)",
                ["engine_ppt"] = "PowerPoint 转换器 (PowerPoint)",
                ["engine_word"] = "Word 转换器 (Word)",
                ["engine_excel"] = "Excel 转换器 (Excel)",
                ["engine_libreoffice"] = "LibreOffice 离线引擎",
                ["engine_ready"] = "已就绪",
                ["engine_office_not_installed"] = "Office 未安装",
                ["setting_engine_title"] = "Office 转档引擎",
                ["setting_engine_desc"] = "选择 Word、Excel、PowerPoint 转 PDF 时使用的引擎",
                ["setting_engine_auto"] = "自动",
                ["setting_engine_microsoft"] = "Microsoft Office",
                ["setting_engine_libreoffice"] = "LibreOffice",
                ["setting_libreoffice_ready"] = "LibreOffice 已就绪",
                ["setting_libreoffice_missing"] = "LibreOffice 尚未设置",
                ["setting_libreoffice_optional"] = "Microsoft Office 已就绪；LibreOffice 可作为免费备用引擎。",
                ["setting_libreoffice_browse"] = "手动指定位置",
                ["setting_libreoffice_browse_title"] = "选择 LibreOffice soffice.exe",
                ["setting_libreoffice_invalid"] = "请选择 LibreOffice 的 soffice.exe。",
                ["setting_libreoffice_download"] = "获取 LibreOffice",
                ["setting_libreoffice_download_prompt"] = "Clickra 将下载并验证 LibreOffice 官方 MSI 安装程序。\n\n版本：{0}\n版本类型：{1}\n下载大小：约 {2}\n安装位置：{3}\nSHA256：{4}\n\n接下来 Windows 可能会要求系统安装权限。安装完成后，LibreOffice 也可在 Clickra 以外正常使用。是否继续？",
                ["setting_libreoffice_download_ready"] = "LibreOffice 已安装并启用：\n{0}",
                ["setting_libreoffice_install_restart_required"] = "LibreOffice 已安装，但 Windows 需要重新启动才会完全完成设置。\n{0}",
                ["setting_libreoffice_download_failed"] = "LibreOffice 连接、下载、安装或验证失败：\n{0}",
                ["setting_libreoffice_download_starting"] = "正在准备下载 LibreOffice...",
                ["setting_libreoffice_reinstall_starting"] = "正在准备重新安装 LibreOffice...",
                ["setting_libreoffice_download_progress"] = "正在下载 LibreOffice... {0}%",
                ["setting_libreoffice_verifying"] = "正在验证 LibreOffice 安装文件...",
                ["setting_libreoffice_installing"] = "正在安装 LibreOffice...",
                ["setting_libreoffice_download_in_progress"] = "LibreOffice 正在下载、安装或移除中，请稍候。",
                ["setting_libreoffice_validated"] = "LibreOffice 验证成功：\n{0}",
                ["setting_libreoffice_validation_failed"] = "LibreOffice 安装不完整。请重新安装 LibreOffice，或选择完整安装目录中的 soffice.exe。",
                ["setting_libreoffice_update"] = "更新 LibreOffice",
                ["setting_libreoffice_reinstall"] = "重新安装 LibreOffice",
                ["setting_libreoffice_uninstall"] = "移除 LibreOffice",
                ["setting_libreoffice_uninstall_confirm"] = "Clickra 会在后台移除系统中的 LibreOffice，并清除 Clickra 的 LibreOffice 设置。移除期间可能会要求系统权限。是否继续？",
                ["setting_libreoffice_uninstalling"] = "正在后台移除 LibreOffice...",
                ["setting_libreoffice_uninstall_ready"] = "LibreOffice 已移除，Clickra 已切回自动引擎。",
                ["setting_libreoffice_uninstall_restart_required"] = "LibreOffice 已安排移除，Clickra 已切回自动引擎。请重新启动 Windows 以完成移除。",
                ["setting_libreoffice_removal_pending"] = "LibreOffice 正在等待 Windows 重新启动以完成移除。",
                ["setting_libreoffice_uninstall_failed"] = "LibreOffice 移除失败：\n{0}",
                ["setting_libreoffice_already_current"] = "当前已安装的 LibreOffice 已是 Clickra 建议版本（{0}），不需要更新。",
                ["setting_microsoft_ready"] = "Microsoft Office 已就绪",
                ["setting_microsoft_missing"] = "Microsoft Office 尚未安装或不完整",
                ["setting_engine_auto_using"] = "自动：使用 {0}",
                ["setting_engine_none_available"] = "没有可用的 Office 转换引擎。请安装 Microsoft Office 或获取 LibreOffice。",
                ["overview_tip"] = "提示：直接在文件资源管理器中选择文件，右键即可呼叫 Clickra 菜单进行转换。",
                ["cmd_word_to_pdf"] = "Word → PDF",
                ["cmd_excel_to_pdf"] = "Excel → PDF",
                ["cmd_ppt_to_pdf"] = "PPT → PDF",
                ["cmd_merge_pdf"] = "合并 PDF",
                ["cmd_img_to_pdf"] = "图片 → PDF",
                ["cmd_merge_img"] = "图片合并",
                ["cmd_stitch_img"] = "图片拼接",
                ["tab_convert"] = "转档",
                ["convert_drag_drop_hint"] = "拖拽文件至此，或点击此处选择文件",
                ["convert_drag_drop_sub"] = "支持 Word, PPT, PDF 及多种图片格式",
                ["convert_selected_count"] = "已选择 {0} 个文件",
                ["convert_clear"] = "清除",
                ["convert_start"] = "开始转档",
                ["convert_group_office"] = "Office 转 PDF",
                ["convert_group_pdf"] = "PDF 工具",
                ["convert_group_image"] = "图片工具",
                ["convert_err_min_files"] = "此功能至少需要 {0} 个文件！",
                ["convert_err_invalid_ext"] = "文件格式不符，请重新选择！",
                ["tab_about"] = "关于",
                ["about_desc_title"] = "项目说明",
                ["about_desc_body"] = "Clickra 是一款专为 Windows 11 量身打造的极致轻量、现代化右键转档工具。\n底层采用先进的 C# NativeAOT 技术，摆脱臃肿的运行环境，实现小于 0.01 秒的瞬时启动与免安装极致体验，与系统完美融为一体。",
                ["about_collab_title"] = "协作开发与源码",
                ["about_collab_body"] = "本项目以 Apache 2.0 协议完全开源！我们热烈欢迎各位开发者加入，共同改善与扩充功能。\n您可以通过 GitHub 提交 Pull Request、反馈 Issue，一起打造更实用的 Windows 生态系工具。",
                ["about_diag_title"] = "诊断与反馈说明",
                ["about_diag_body"] = "遇到转档失败或异常吗？我们为您简化了反馈流程！\n点击下方按钮将一键开启 Gmail 网页版邮件撰写，并同步在文件资源管理器中为您选好日志「history.log」，您只需将该文件拖拽至邮件中即可快速发送诊断信息。",
                ["about_btn_open_data_dir"] = "查看日志文件夹",
                ["about_btn_github"] = "GitHub 项目",
                ["about_btn_gmail"] = "Gmail 反馈",
                ["history_detail_inputs"] = "输入路径",
                ["history_detail_outputs"] = "输出路径",
                ["history_detail_time"] = "转换时间",
                ["history_detail_elapsed"] = "执行耗时",
                ["progress_cancel_confirm"] = "您确定要取消当前的转换作业吗？",
                ["history_detail_error"] = "错误信息",
                ["error_user_aborted"] = "取消",
                ["progress_tray_hint"] = "按 — 或任务栏图标可最小化到系统托盘继续运行",
                ["progress_background"] = "最小化到系统托盘",
                ["error_processing_failed"] = "处理过程中发生错误：\n{0}",
                ["error_libreoffice_not_ready"] = "LibreOffice 引擎尚未就绪。请到“设置”重新获取 LibreOffice，或将 Office 转换引擎改回“自动”或“Microsoft Office”。",
                ["error_libreoffice_unusable"] = "当前的 LibreOffice 无法正常启动。请到“设置”重新获取 LibreOffice，或手动指定一个可正常运行的 LibreOffice。",
                ["error_microsoftoffice_not_ready"] = "Microsoft Office 尚未就绪。请安装对应的 Office 应用程序，或将 Office 转换引擎改为“自动”或“LibreOffice”。",
                ["status_office_fallback_to_libreoffice"] = "Microsoft {0} 转换失败，正在改用 LibreOffice：{1}...",
                ["status_libreoffice_starting"] = "正在启动 LibreOffice 引擎 ({0}/{1})...",
                ["status_libreoffice_exporting"] = "正在使用 LibreOffice 导出 PDF：{0}...",
                ["status_libreoffice_completed"] = "已完成 LibreOffice 转换：{0}",
                ["setting_pdf_title"] = "PDF 翻译",
                ["setting_pdf_desc"] = "设置 PDF 翻译语言",
                ["setting_pdf_lang"] = "目标语言",
                ["cmd_translate_pdf"] = "PDF 翻译",
                ["cmd_decrypt_pdf"] = "去除 PDF 密码",
                [KeyCmdSplitPdf] = "分割 PDF",
                [KeySplitPdfTitle] = "输入 PDF 分割页码范围",
                [KeySplitPdfPrompt] = "请输入分页范围（例如 1-5, 8 或 all 拆分为单页档）：",
                ["pdf_password_title"] = "输入 PDF 密码",
                ["pdf_password_prompt"] = "「{0}」受密码保护，请输入打开密码：",
                ["pdf_password_retry"] = "密码错误。请重新输入「{0}」的密码：",
                ["error_pdf_password_quiet"] = "密码错误或未提供密码（静默模式下无法手动输入密码）。",
                ["pdf_not_encrypted"] = "此文件未加密，无需解除密码。",
                ["dialog_ok"] = "确定",
                ["dialog_cancel"] = "取消"
            },
            [LangEn] = new(StringComparer.OrdinalIgnoreCase)
            {
                ["tab_status"] = "Status",
                ["tab_history"] = "History",
                ["tab_settings"] = "Settings",
                ["setting_silent_title"] = "Silent Mode",
                ["setting_silent_desc"] = "Process in background without showing progress window",
                ["setting_notify_title"] = "Show Notifications",
                ["setting_notify_desc"] = "Show Toast notification when conversion completes/fails",
                ["setting_output_title"] = "Default Output Path",
                ["setting_output_desc"] = "Select the default save location for converted files",
                ["setting_output_same_as_source"] = "Same as source",
                ["setting_output_desktop"] = "Desktop",
                ["setting_output_downloads"] = "Downloads",
                ["setting_output_custom"] = "Custom...",
                ["setting_output_selected_path"] = "Selected path",
                ["setting_output_browse_title"] = "Select Default Output Folder",
                ["overview_engine_status"] = "Conversion Engine Status",
                ["overview_stats"] = "Conversion Stats",
                ["overview_stat_total"] = "Total Conversions",
                ["overview_stat_success"] = "Successful",
                ["overview_stat_failed"] = "Failed",
                ["overview_office_conversion"] = "Office conversion",
                ["overview_engine_active"] = "Using {0}",
                ["overview_engine_unavailable"] = "{0} not ready",
                ["history_clear"] = "Clear History",
                ["history_clear_confirm"] = "Are you sure you want to clear all history?",
                ["history_empty"] = "No conversion history.",
                ["status_pending"] = "Pending",
                ["status_converting"] = "Converting",
                ["status_success"] = "Success",
                ["status_failed"] = "Failed",
                ["status_error"] = "Error",
                ["label_files"] = "files",
                ["setting_lang_title"] = "Interface Language",
                ["setting_lang_desc"] = "Select the display language for the Dashboard",
                ["search_lang_placeholder"] = "Search language...",
                ["engine_pdf"] = "PDF Processing Engine",
                ["engine_ppt"] = "PowerPoint Converter",
                ["engine_word"] = "Word Converter",
                ["engine_excel"] = "Excel Converter",
                ["engine_libreoffice"] = "LibreOffice Offline Engine",
                ["engine_ready"] = "Ready",
                ["engine_office_not_installed"] = "Office Not Installed",
                ["setting_engine_title"] = "Office Conversion Engine",
                ["setting_engine_desc"] = "Choose the engine used for Word, Excel, and PowerPoint to PDF conversion",
                ["setting_engine_auto"] = "Auto",
                ["setting_engine_microsoft"] = "Microsoft Office",
                ["setting_engine_libreoffice"] = "LibreOffice",
                ["setting_libreoffice_ready"] = "LibreOffice ready",
                ["setting_libreoffice_missing"] = "LibreOffice is not configured",
                ["setting_libreoffice_optional"] = "Microsoft Office is ready; LibreOffice can be used as a free fallback engine.",
                ["setting_libreoffice_browse"] = "Choose location",
                ["setting_libreoffice_browse_title"] = "Select LibreOffice soffice.exe",
                ["setting_libreoffice_invalid"] = "Please select LibreOffice soffice.exe.",
                ["setting_libreoffice_download"] = "Get LibreOffice",
                ["setting_libreoffice_download_prompt"] = "Clickra will download and verify the official LibreOffice MSI installer.\n\nVersion: {0}\nEdition: {1}\nDownload size: about {2}\nInstall path: {3}\nSHA256: {4}\n\nWindows may ask for permission to install system software. After installation, LibreOffice can also be used outside Clickra. Continue?",
                ["setting_libreoffice_download_ready"] = "LibreOffice is installed and enabled:\n{0}",
                ["setting_libreoffice_install_restart_required"] = "LibreOffice is installed, but Windows needs a restart to finish configuration.\n{0}",
                ["setting_libreoffice_download_failed"] = "LibreOffice connection, download, installation, or verification failed:\n{0}",
                ["setting_libreoffice_download_starting"] = "Preparing LibreOffice download...",
                ["setting_libreoffice_reinstall_starting"] = "Preparing LibreOffice reinstall...",
                ["setting_libreoffice_download_progress"] = "Downloading LibreOffice... {0}%",
                ["setting_libreoffice_verifying"] = "Verifying LibreOffice installer...",
                ["setting_libreoffice_installing"] = "Installing LibreOffice...",
                ["setting_libreoffice_download_in_progress"] = "LibreOffice is already downloading, installing, or being removed. Please wait.",
                ["setting_libreoffice_validated"] = "LibreOffice validated:\n{0}",
                ["setting_libreoffice_validation_failed"] = "LibreOffice installation is incomplete. Reinstall LibreOffice, or choose soffice.exe from a complete installation folder.",
                ["setting_libreoffice_update"] = "Update LibreOffice",
                ["setting_libreoffice_reinstall"] = "Reinstall LibreOffice",
                ["setting_libreoffice_uninstall"] = "Remove LibreOffice",
                ["setting_libreoffice_uninstall_confirm"] = "Clickra will remove LibreOffice in the background and clear Clickra's LibreOffice settings. Windows may ask for permission. Continue?",
                ["setting_libreoffice_uninstalling"] = "Removing LibreOffice in the background...",
                ["setting_libreoffice_uninstall_ready"] = "LibreOffice has been removed. Clickra switched back to Auto.",
                ["setting_libreoffice_uninstall_restart_required"] = "LibreOffice removal is scheduled. Clickra switched back to Auto. Restart Windows to finish removal.",
                ["setting_libreoffice_removal_pending"] = "LibreOffice is waiting for Windows to restart and finish removal.",
                ["setting_libreoffice_uninstall_failed"] = "LibreOffice removal failed:\n{0}",
                ["setting_libreoffice_already_current"] = "The installed LibreOffice is already Clickra's recommended version ({0}). No update is needed.",
                ["setting_microsoft_ready"] = "Microsoft Office ready",
                ["setting_microsoft_missing"] = "Microsoft Office is not installed or is incomplete",
                ["setting_engine_auto_using"] = "Auto: using {0}",
                ["setting_engine_none_available"] = "No Office conversion engine is available. Install Microsoft Office or get LibreOffice.",
                ["overview_tip"] = "Tip: Select files in File Explorer, right-click, and select Clickra to convert.",
                ["cmd_word_to_pdf"] = "Word → PDF",
                ["cmd_excel_to_pdf"] = "Excel → PDF",
                ["cmd_ppt_to_pdf"] = "PPT → PDF",
                ["cmd_merge_pdf"] = "Merge PDF",
                ["cmd_img_to_pdf"] = "Image → PDF",
                ["cmd_merge_img"] = "Merge Images",
                ["cmd_stitch_img"] = "Stitch Images",
                ["tab_convert"] = "Convert",
                ["convert_drag_drop_hint"] = "Drag files here, or click to browse",
                ["convert_drag_drop_sub"] = "Supports Word, PPT, PDF, and image files",
                ["convert_selected_count"] = "{0} files selected",
                ["convert_clear"] = "Clear",
                ["convert_start"] = "Start Conversion",
                ["convert_group_office"] = "Office to PDF",
                ["convert_group_pdf"] = "PDF Tools",
                ["convert_group_image"] = "Image Tools",
                ["convert_err_min_files"] = "This action requires at least {0} files!",
                ["convert_err_invalid_ext"] = "Invalid file extensions detected!",
                ["tab_about"] = "About",
                ["about_desc_title"] = "About Project",
                ["about_desc_body"] = "Clickra is a premium, ultra-lightweight modern context menu utility designed for Windows 11.\nBuilt with C# NativeAOT, it skips all runtime overhead to deliver sub-10ms instantaneous startup and a zero-dependency user experience that feels like a native OS feature.",
                ["about_collab_title"] = "Collaboration & Source",
                ["about_collab_body"] = "This project is fully open-source under the Apache 2.0 license! We love community contributions.\nVisit our GitHub repository to submit Pull Requests, report issues, or collaborate on building better tools for Windows.",
                ["about_diag_title"] = "Diagnostics & Support",
                ["about_diag_body"] = "Encountered a conversion issue? We've streamlined the feedback process!\nClick below to open Gmail Web Composer and highlight 'history.log' in File Explorer. Simply drag the highlighted file into Gmail to send us the diagnostic details.",
                ["about_btn_open_data_dir"] = "Open Log Folder",
                ["about_btn_github"] = "View on GitHub",
                ["about_btn_gmail"] = "Gmail Diagnostics",
                ["history_detail_inputs"] = "Input Paths",
                ["history_detail_outputs"] = "Output Path",
                ["history_detail_time"] = "Conversion Time",
                ["history_detail_elapsed"] = "Elapsed Time",
                ["progress_cancel_confirm"] = "Are you sure you want to cancel the current conversion?",
                ["history_detail_error"] = "Error Message",
                ["error_user_aborted"] = "Canceled",
                ["progress_tray_hint"] = "Click — or taskbar icon to minimize to tray",
                ["progress_background"] = "Minimize to System Tray",
                ["error_processing_failed"] = "An error occurred while processing:\n{0}",
                ["error_libreoffice_not_ready"] = "The LibreOffice engine is not ready. Open Settings and get LibreOffice again, or switch the Office engine back to Auto or Microsoft Office.",
                ["error_libreoffice_unusable"] = "The current LibreOffice engine cannot start correctly. Open Settings and get LibreOffice again, or choose a working LibreOffice installation manually.",
                ["error_microsoftoffice_not_ready"] = "Microsoft Office is not ready. Install the required Office app, or switch the Office engine to Auto or LibreOffice.",
                ["status_office_fallback_to_libreoffice"] = "Microsoft {0} conversion failed; switching to LibreOffice: {1}...",
                ["status_libreoffice_starting"] = "Starting LibreOffice engine ({0}/{1})...",
                ["status_libreoffice_exporting"] = "Exporting PDF with LibreOffice: {0}...",
                ["status_libreoffice_completed"] = "LibreOffice conversion completed: {0}",
                ["setting_pdf_title"] = "PDF One-Click Translation",
                ["setting_pdf_desc"] = "Configure target language for translation",
                ["setting_pdf_lang"] = "Target Language",
                ["cmd_translate_pdf"] = "PDF Translation",
                ["cmd_decrypt_pdf"] = "Remove PDF Password",
                [KeyCmdSplitPdf] = "Split PDF",
                [KeySplitPdfTitle] = "Enter Page Range to Split PDF",
                [KeySplitPdfPrompt] = "Enter page range (e.g. 1-5, 8 or all to split into single pages):",
                ["pdf_password_title"] = "Enter PDF Password",
                ["pdf_password_prompt"] = "\"{0}\" is password protected. Enter open password:",
                ["pdf_password_retry"] = "Incorrect password. Re-enter password for \"{0}\":",
                ["error_pdf_password_quiet"] = "Incorrect or missing password (cannot prompt for password in quiet mode).",
                ["pdf_not_encrypted"] = "This file is not encrypted; no decryption needed.",
                ["dialog_ok"] = "OK",
                ["dialog_cancel"] = "Cancel"
            },
            [LangJa] = new(StringComparer.OrdinalIgnoreCase)
            {
                ["tab_status"] = "状態",
                ["tab_history"] = "履歴",
                ["tab_settings"] = "設定",
                ["tab_convert"] = "変換",
                ["tab_about"] = "紹介",
                ["setting_silent_title"] = "サイレントモード",
                ["setting_silent_desc"] = "進行状況ウィンドウを表示せず、バックグラウンドで処理します",
                ["setting_notify_title"] = "変換通知を表示",
                ["setting_notify_desc"] = "完了または失敗時に、Windows トースト通知を表示します",
                ["setting_output_title"] = "既定の出力先",
                ["setting_output_desc"] = "変換後のファイルの保存先を選択します",
                ["setting_output_same_as_source"] = "ソースと同じ",
                ["setting_output_desktop"] = "デスクトップ",
                ["setting_output_downloads"] = "ダウンロード",
                ["setting_output_custom"] = "カスタム...",
                ["setting_output_selected_path"] = "選択されたパス",
                ["setting_output_browse_title"] = "既定の出力フォルダを選択",
                ["overview_engine_status"] = "変換エンジンの状態",
                ["overview_stats"] = "統計情報",
                ["overview_stat_total"] = "総変換回数",
                ["overview_stat_success"] = "成功回数",
                ["overview_stat_failed"] = "失敗回数",
                ["overview_office_conversion"] = "Office 変換",
                ["overview_engine_active"] = "{0} を使用",
                ["overview_engine_unavailable"] = "{0} は未準備です",
                ["history_clear"] = "履歴をクリア",
                ["history_clear_confirm"] = "すべての変換履歴をクリアしてもよろしいですか？",
                ["history_empty"] = "変換履歴はありません。",
                ["status_pending"] = "待機中",
                ["status_converting"] = "変換中",
                ["status_success"] = "成功",
                ["status_failed"] = "失敗",
                ["status_error"] = "エラー",
                ["label_files"] = "個のファイル",
                ["setting_lang_title"] = "表示言語",
                ["setting_lang_desc"] = "Dashboard の表示言語を選択します",
                ["search_lang_placeholder"] = "言語を検索...",
                ["engine_pdf"] = "PDF 処理エンジン",
                ["engine_ppt"] = "PowerPoint 変換器",
                ["engine_word"] = "Word 変換器",
                ["engine_excel"] = "Excel 変換器",
                ["engine_libreoffice"] = "LibreOffice オフラインエンジン",
                ["engine_ready"] = "準備完了",
                ["engine_office_not_installed"] = "Office 未インストール",
                ["setting_engine_title"] = "Office 変換エンジン",
                ["setting_engine_desc"] = "Word、Excel、PowerPoint から PDF への変換に使うエンジンを選択します",
                ["setting_engine_auto"] = "自動",
                ["setting_engine_microsoft"] = "Microsoft Office",
                ["setting_engine_libreoffice"] = "LibreOffice",
                ["setting_libreoffice_ready"] = "LibreOffice 準備完了",
                ["setting_libreoffice_missing"] = "LibreOffice は未設定です",
                ["setting_libreoffice_optional"] = "Microsoft Office は準備完了です。LibreOffice は無料の予備エンジンとして使用できます。",
                ["setting_libreoffice_browse"] = "場所を手動指定",
                ["setting_libreoffice_browse_title"] = "LibreOffice soffice.exe を選択",
                ["setting_libreoffice_invalid"] = "LibreOffice の soffice.exe を選択してください。",
                ["setting_libreoffice_download"] = "LibreOffice を取得",
                ["setting_libreoffice_download_prompt"] = "Clickra は LibreOffice 公式 MSI インストーラーをダウンロードして検証します。\n\nバージョン：{0}\nエディション：{1}\nダウンロードサイズ：約 {2}\nインストール先：{3}\nSHA256：{4}\n\nWindows がシステムへのインストール許可を求める場合があります。完了後、LibreOffice は Clickra 以外でも使用できます。続行しますか？",
                ["setting_libreoffice_download_ready"] = "LibreOffice をインストールして有効にしました：\n{0}",
                ["setting_libreoffice_install_restart_required"] = "LibreOffice をインストールしましたが、設定を完了するには Windows の再起動が必要です。\n{0}",
                ["setting_libreoffice_download_failed"] = "LibreOffice への接続、ダウンロード、インストール、または検証に失敗しました：\n{0}",
                ["setting_libreoffice_download_starting"] = "LibreOffice のダウンロードを準備しています...",
                ["setting_libreoffice_reinstall_starting"] = "LibreOffice の再インストールを準備しています...",
                ["setting_libreoffice_download_progress"] = "LibreOffice をダウンロード中... {0}%",
                ["setting_libreoffice_verifying"] = "LibreOffice インストーラーを検証しています...",
                ["setting_libreoffice_installing"] = "LibreOffice をインストール中...",
                ["setting_libreoffice_download_in_progress"] = "LibreOffice のダウンロード、インストール、または削除を実行中です。お待ちください。",
                ["setting_libreoffice_validated"] = "LibreOffice の検証に成功しました：\n{0}",
                ["setting_libreoffice_validation_failed"] = "LibreOffice のインストールが不完全です。再インストールするか、完全なインストール先の soffice.exe を選択してください。",
                ["setting_libreoffice_update"] = "LibreOffice を更新",
                ["setting_libreoffice_reinstall"] = "LibreOffice を再インストール",
                ["setting_libreoffice_uninstall"] = "LibreOffice を削除",
                ["setting_libreoffice_uninstall_confirm"] = "Clickra がバックグラウンドで LibreOffice を削除し、Clickra の LibreOffice 設定を消去します。Windows が権限を要求する場合があります。続行しますか？",
                ["setting_libreoffice_uninstalling"] = "バックグラウンドで LibreOffice を削除しています...",
                ["setting_libreoffice_uninstall_ready"] = "LibreOffice を削除しました。Clickra は自動エンジンに戻りました。",
                ["setting_libreoffice_uninstall_restart_required"] = "LibreOffice の削除を予約しました。Clickra は自動エンジンに戻りました。削除を完了するには Windows を再起動してください。",
                ["setting_libreoffice_removal_pending"] = "LibreOffice は Windows の再起動後に削除が完了します。",
                ["setting_libreoffice_uninstall_failed"] = "LibreOffice の削除に失敗しました：\n{0}",
                ["setting_libreoffice_already_current"] = "インストール済みの LibreOffice は Clickra 推奨バージョン（{0}）です。更新は不要です。",
                ["setting_microsoft_ready"] = "Microsoft Office 準備完了",
                ["setting_microsoft_missing"] = "Microsoft Office が未インストール、または不完全です",
                ["setting_engine_auto_using"] = "自動：{0} を使用",
                ["setting_engine_none_available"] = "利用可能な Office 変換エンジンがありません。Microsoft Office をインストールするか、LibreOffice を取得してください。",
                ["overview_tip"] = "ヒント：エクスプローラーでファイルを選択し、右クリックして Clickra から変換します。",
                ["cmd_word_to_pdf"] = "Word → PDF",
                ["cmd_excel_to_pdf"] = "Excel → PDF",
                ["cmd_ppt_to_pdf"] = "PPT → PDF",
                ["cmd_merge_pdf"] = "PDF 結合",
                ["cmd_img_to_pdf"] = "画像 → PDF",
                ["cmd_merge_img"] = "画像結合",
                ["cmd_stitch_img"] = "画像結合 (縦/横)",
                ["convert_drag_drop_hint"] = "ここにファイルをドラッグするか、クリックして選択",
                ["convert_drag_drop_sub"] = "Word、PPT、PDF、および画像ファイルをサポート",
                ["convert_selected_count"] = "{0} 個のファイルが選択されました",
                ["convert_clear"] = "クリア",
                ["convert_start"] = "変換開始",
                ["convert_group_office"] = "Office から PDF",
                ["convert_group_pdf"] = "PDF ツール",
                ["convert_group_image"] = "画像ツール",
                ["convert_err_min_files"] = "この機能には少なくとも {0} 個のファイルが必要です！",
                ["convert_err_invalid_ext"] = "無効なファイル形式が含まれています！",
                ["about_desc_title"] = "プロジェクトについて",
                ["about_desc_body"] = "Clickra は、Windows 11 のために設計された極めて軽量でモダンな右鍵コンテキストメニュー変換ツールです。\nC# NativeAOT 技術を採用し、不要なランタイムを排除することで、0.01秒未満の瞬間起動と完全なスタンドアロン動作を実現しました。",
                ["about_collab_title"] = "コラボレーションとソースコード",
                ["about_collab_body"] = "本プロジェクトは Apache 2.0 ライセンスの下で完全にオープンソース化されています！\nGitHub での Pull Request や Issue の報告を通じて、Windows ユーザーのための優れたツール開発にぜひご協力ください。",
                ["about_diag_title"] = "診断とサポート",
                ["about_diag_body"] = "変換エラーや不具合が発生しましたか？フィードバックの手順を劇的に簡略化しました！\nボタンをクリックすると、Gmail 作成画面が開き、エクスプローラーでログファイル「history.log」が自動選択されます。ファイルをそのままドラッグ＆ドロップして送信してください。",
                ["about_btn_open_data_dir"] = "ログフォルダを開く",
                ["about_btn_github"] = "GitHub で表示",
                ["about_btn_gmail"] = "Gmail でフィードバック",
                ["history_detail_inputs"] = "入力パス",
                ["history_detail_outputs"] = "出力パス",
                ["history_detail_time"] = "変換日時",
                ["history_detail_elapsed"] = "処理時間",
                ["progress_cancel_confirm"] = "現在の変換作業をキャンセルしてもよろしいですか？",
                ["history_detail_error"] = "エラーメッセージ",
                ["error_user_aborted"] = "キャンセル",
                ["progress_tray_hint"] = "— またはタスクバーアイコンでトレイに最小化できます",
                ["progress_background"] = "システムトレイに最小化",
                ["error_processing_failed"] = "処理中にエラーが発生しました：\n{0}",
                ["error_libreoffice_not_ready"] = "LibreOffice エンジンはまだ準備できていません。設定で LibreOffice を再取得するか、Office 変換エンジンを「自動」または「Microsoft Office」に戻してください。",
                ["error_libreoffice_unusable"] = "現在の LibreOffice は正常に起動できません。設定で LibreOffice を再取得するか、正常に動作する LibreOffice を手動で指定してください。",
                ["error_microsoftoffice_not_ready"] = "Microsoft Office は準備できていません。必要な Office アプリをインストールするか、Office 変換エンジンを「自動」または「LibreOffice」に変更してください。",
                ["status_office_fallback_to_libreoffice"] = "Microsoft {0} の変換に失敗しました。LibreOffice に切り替えています：{1}...",
                ["status_libreoffice_starting"] = "LibreOffice エンジンを起動しています ({0}/{1})...",
                ["status_libreoffice_exporting"] = "LibreOffice で PDF を書き出しています：{0}...",
                ["status_libreoffice_completed"] = "LibreOffice 変換が完了しました：{0}",
                ["setting_pdf_title"] = "PDF 一括翻訳",
                ["setting_pdf_desc"] = "翻訳の対象言語を設定します",
                ["setting_pdf_lang"] = "対象言語 (Target Language)",
                ["cmd_translate_pdf"] = "PDF 翻訳",
                ["cmd_decrypt_pdf"] = "PDF パスワード解除",
                [KeyCmdSplitPdf] = "PDF 分割",
                [KeySplitPdfTitle] = "PDF 分割ページ範囲の入力",
                [KeySplitPdfPrompt] = "ページ範囲を入力してください（例：1-5, 8 または全ページ分割の all）：",
                ["pdf_password_title"] = "PDF パスワード入力",
                ["pdf_password_prompt"] = "「{0}」はパスワードで保護されています。パスワードを入力してください：",
                ["pdf_password_retry"] = "パスワードが正しくありません。もう一度入力してください：「{0}」",
                ["error_pdf_password_quiet"] = "パスワードが正しくないか入力されていません（サイレントモードではパスワードを入力できません）。",
                ["pdf_not_encrypted"] = "このファイルは暗号化されていません。パスワード解除は不要です。",
                ["dialog_ok"] = "確定",
                ["dialog_cancel"] = "キャンセル"
            },
            [LangKo] = new(StringComparer.OrdinalIgnoreCase)
            {
                ["tab_status"] = "상태",
                ["tab_history"] = "기록",
                ["tab_settings"] = "설정",
                ["tab_convert"] = "변환",
                ["tab_about"] = "정보",
                ["setting_silent_title"] = "자동 변환 모드",
                ["setting_silent_desc"] = "진행 창을 표시하지 않고 백그라운드에서 바로 처리합니다",
                ["setting_notify_title"] = "변환 알림 표시",
                ["setting_notify_desc"] = "완료 또는 실패 시 Windows 토스트 알림을 표시합니다",
                ["setting_output_title"] = "기본 출력 경로",
                ["setting_output_desc"] = "변환된 파일의 기본 저장 위치를 선택합니다",
                ["setting_output_same_as_source"] = "원본과 동일",
                ["setting_output_desktop"] = "바탕 화면",
                ["setting_output_downloads"] = "다운로드",
                ["setting_output_custom"] = "사용자 정의...",
                ["setting_output_selected_path"] = "선택한 경로",
                ["setting_output_browse_title"] = "기본 출력 폴더 선택",
                ["overview_engine_status"] = "변환 엔진 상태",
                ["overview_stats"] = "오늘의 통계",
                ["overview_stat_total"] = "총 변환 횟수",
                ["overview_stat_success"] = "성공 횟수",
                ["overview_stat_failed"] = "실패 횟수",
                ["overview_office_conversion"] = "Office 변환",
                ["overview_engine_active"] = "{0} 사용",
                ["overview_engine_unavailable"] = "{0} 준비되지 않음",
                ["history_clear"] = "기록 삭제",
                ["history_clear_confirm"] = "모든 변환 기록을 삭제하시겠습니까?",
                ["history_empty"] = "변환 기록이 없습니다.",
                ["status_pending"] = "대기 중",
                ["status_converting"] = "변환 중",
                ["status_success"] = "성공",
                ["status_failed"] = "실패",
                ["status_error"] = "오류",
                ["label_files"] = "개의 파일",
                ["setting_lang_title"] = "표시 언어",
                ["setting_lang_desc"] = "Dashboard 표시 언어를 선택합니다",
                ["search_lang_placeholder"] = "언어 검색...",
                ["engine_pdf"] = "PDF 처리 엔진",
                ["engine_ppt"] = "PowerPoint 변환기",
                ["engine_word"] = "Word 변환기",
                ["engine_excel"] = "Excel 변환기",
                ["engine_libreoffice"] = "LibreOffice 오프라인 엔진",
                ["engine_ready"] = "준비 완료",
                ["engine_office_not_installed"] = "Office 미설치",
                ["setting_engine_title"] = "Office 변환 엔진",
                ["setting_engine_desc"] = "Word, Excel, PowerPoint를 PDF로 변환할 때 사용할 엔진을 선택합니다",
                ["setting_engine_auto"] = "자동",
                ["setting_engine_microsoft"] = "Microsoft Office",
                ["setting_engine_libreoffice"] = "LibreOffice",
                ["setting_libreoffice_ready"] = "LibreOffice 준비 완료",
                ["setting_libreoffice_missing"] = "LibreOffice가 설정되지 않았습니다",
                ["setting_libreoffice_optional"] = "Microsoft Office가 준비되었습니다. LibreOffice는 무료 예비 엔진으로 사용할 수 있습니다.",
                ["setting_libreoffice_browse"] = "위치 수동 지정",
                ["setting_libreoffice_browse_title"] = "LibreOffice soffice.exe 선택",
                ["setting_libreoffice_invalid"] = "LibreOffice의 soffice.exe를 선택하세요.",
                ["setting_libreoffice_download"] = "LibreOffice 받기",
                ["setting_libreoffice_download_prompt"] = "Clickra가 공식 LibreOffice MSI 설치 파일을 다운로드하고 검증합니다.\n\n버전: {0}\n에디션: {1}\n다운로드 크기: 약 {2}\n설치 위치: {3}\nSHA256: {4}\n\nWindows가 시스템 소프트웨어 설치 권한을 요청할 수 있습니다. 설치 후 LibreOffice는 Clickra 밖에서도 사용할 수 있습니다. 계속하시겠습니까?",
                ["setting_libreoffice_download_ready"] = "LibreOffice 설치 및 사용 설정 완료:\n{0}",
                ["setting_libreoffice_install_restart_required"] = "LibreOffice가 설치되었지만 설정을 완료하려면 Windows를 다시 시작해야 합니다.\n{0}",
                ["setting_libreoffice_download_failed"] = "LibreOffice 연결, 다운로드, 설치 또는 검증 실패:\n{0}",
                ["setting_libreoffice_download_starting"] = "LibreOffice 다운로드를 준비 중...",
                ["setting_libreoffice_reinstall_starting"] = "LibreOffice 재설치를 준비 중...",
                ["setting_libreoffice_download_progress"] = "LibreOffice 다운로드 중... {0}%",
                ["setting_libreoffice_verifying"] = "LibreOffice 설치 파일을 검증 중...",
                ["setting_libreoffice_installing"] = "LibreOffice 설치 중...",
                ["setting_libreoffice_download_in_progress"] = "LibreOffice 다운로드, 설치 또는 제거가 진행 중입니다. 잠시 기다려 주세요.",
                ["setting_libreoffice_validated"] = "LibreOffice 검증 성공:\n{0}",
                ["setting_libreoffice_validation_failed"] = "LibreOffice 설치가 완전하지 않습니다. LibreOffice를 다시 설치하거나 전체 설치 폴더의 soffice.exe를 선택하세요.",
                ["setting_libreoffice_update"] = "LibreOffice 업데이트",
                ["setting_libreoffice_reinstall"] = "LibreOffice 재설치",
                ["setting_libreoffice_uninstall"] = "LibreOffice 제거",
                ["setting_libreoffice_uninstall_confirm"] = "Clickra가 백그라운드에서 LibreOffice를 제거하고 Clickra의 LibreOffice 설정을 지웁니다. Windows 권한 요청이 표시될 수 있습니다. 계속하시겠습니까?",
                ["setting_libreoffice_uninstalling"] = "백그라운드에서 LibreOffice 제거 중...",
                ["setting_libreoffice_uninstall_ready"] = "LibreOffice가 제거되었습니다. Clickra가 자동 엔진으로 돌아갔습니다.",
                ["setting_libreoffice_uninstall_restart_required"] = "LibreOffice 제거가 예약되었습니다. Clickra가 자동 엔진으로 돌아갔습니다. 제거를 완료하려면 Windows를 다시 시작하세요.",
                ["setting_libreoffice_removal_pending"] = "LibreOffice가 Windows 재시작 후 제거를 완료하도록 대기 중입니다.",
                ["setting_libreoffice_uninstall_failed"] = "LibreOffice 제거 실패:\n{0}",
                ["setting_libreoffice_already_current"] = "설치된 LibreOffice가 이미 Clickra 권장 버전({0})입니다. 업데이트가 필요 없습니다.",
                ["setting_microsoft_ready"] = "Microsoft Office 준비 완료",
                ["setting_microsoft_missing"] = "Microsoft Office가 설치되지 않았거나 완전하지 않습니다",
                ["setting_engine_auto_using"] = "자동: {0} 사용",
                ["setting_engine_none_available"] = "사용 가능한 Office 변환 엔진이 없습니다. Microsoft Office를 설치하거나 LibreOffice를 받으세요.",
                ["overview_tip"] = "팁: 파일 탐색기에서 파일을 선택하고 마우스 오른쪽 버튼을 클릭하여 Clickra로 변환하세요.",
                ["cmd_word_to_pdf"] = "Word → PDF",
                ["cmd_excel_to_pdf"] = "Excel → PDF",
                ["cmd_ppt_to_pdf"] = "PPT → PDF",
                ["cmd_merge_pdf"] = "PDF 병합",
                ["cmd_img_to_pdf"] = "이미지 → PDF",
                ["cmd_merge_img"] = "이미지 병합",
                ["cmd_stitch_img"] = "이미지 이어붙이기",
                ["tab_convert"] = "변환",
                ["convert_drag_drop_hint"] = "여기에 파일을 끌어다 놓거나 클릭하여 선택",
                ["convert_drag_drop_sub"] = "Word, PPT, PDF 및 이미지 파일 지원",
                ["convert_selected_count"] = "{0}개의 파일이 선택됨",
                ["convert_clear"] = "지우기",
                ["convert_start"] = "변환 시작",
                ["convert_group_office"] = "Office to PDF",
                ["convert_group_pdf"] = "PDF 도구",
                ["convert_group_image"] = "이미지 도구",
                ["convert_err_min_files"] = "이 작업은 최소 {0}개의 파일이 필요합니다!",
                ["convert_err_invalid_ext"] = "잘못된 파일 확장자가 감지되었습니다!",
                ["tab_about"] = "정보",
                ["about_desc_title"] = "프로젝트 정보",
                ["about_desc_body"] = "Clickra는 Windows 11을 위해 특별히 설계된 초경량 현대식 마우스 오른쪽 버튼 변환 도구입니다.\n최첨단 C# NativeAOT 기술을 적용하여 불필요한 런타임을 배제하고 0.01초 미만의 즉각적인 실행 속도와 무설치 작동을 제공합니다.",
                ["about_collab_title"] = "협업 및 소스 코드",
                ["about_collab_body"] = "이 프로젝트는 Apache 2.0 라이선스 하에 완전한 오픈 소스로 제공됩니다!\nGitHub 리포지토리에서 Pull Request 제출, Issue 등록을 통해 더 편리한 Windows 환경을 만드는 데 동참해 주세요.",
                ["about_diag_title"] = "진단 및 지원",
                ["about_diag_body"] = "변환 중 문제가 발생하면 아래 버튼을 누르면 Gmail 작성 창이 열리고 탐색기에서 로그 파일「history.log」가 자동 선택됩니다. 파일을 메일에 드래그 앤 드롭하여 손쉽게 진단 정보를 보내주세요.",
                ["about_btn_open_data_dir"] = "로그 폴더 열기",
                ["about_btn_github"] = "GitHub 리포지토리",
                ["about_btn_gmail"] = "Gmail 피드백",
                ["history_detail_inputs"] = "입력 경로",
                ["history_detail_outputs"] = "출력 경로",
                ["history_detail_time"] = "변환 시간",
                ["history_detail_elapsed"] = "소요 시간",
                ["progress_cancel_confirm"] = "현재 변환 작업을 취소하시겠습니까?",
                ["history_detail_error"] = "오류 메시지",
                ["error_user_aborted"] = "취소됨",
                ["progress_tray_hint"] = "— 또는 작업 표시줄 아이콘을 클릭하면 트레이로 최소화됩니다",
                ["progress_background"] = "시스템 트레이로 최소화",
                ["error_processing_failed"] = "처리 중 오류가 발생했습니다:\n{0}",
                ["error_libreoffice_not_ready"] = "LibreOffice 엔진이 아직 준비되지 않았습니다. 설정에서 LibreOffice를 다시 받거나 Office 변환 엔진을 자동 또는 Microsoft Office로 변경하세요.",
                ["error_libreoffice_unusable"] = "현재 LibreOffice를 정상적으로 시작할 수 없습니다. 설정에서 LibreOffice를 다시 받거나 정상 실행되는 LibreOffice를 직접 지정하세요.",
                ["error_microsoftoffice_not_ready"] = "Microsoft Office가 준비되지 않았습니다. 필요한 Office 앱을 설치하거나 Office 변환 엔진을 자동 또는 LibreOffice로 변경하세요.",
                ["status_office_fallback_to_libreoffice"] = "Microsoft {0} 변환에 실패했습니다. LibreOffice로 전환 중: {1}...",
                ["status_libreoffice_starting"] = "LibreOffice 엔진 시작 중 ({0}/{1})...",
                ["status_libreoffice_exporting"] = "LibreOffice로 PDF 내보내는 중: {0}...",
                ["status_libreoffice_completed"] = "LibreOffice 변환 완료: {0}",
                ["setting_pdf_title"] = "PDF 일괄 번역",
                ["setting_pdf_desc"] = "번역 대상 언어를 설정합니다",
                ["setting_pdf_lang"] = "대상 언어 (Target Language)",
                ["cmd_translate_pdf"] = "PDF 번역",
                ["cmd_decrypt_pdf"] = "PDF 비밀번호 제거",
                [KeyCmdSplitPdf] = "PDF 분할",
                [KeySplitPdfTitle] = "PDF 분할 페이지 범위 입력",
                [KeySplitPdfPrompt] = "페이지 범위를 입력하십시오 (예: 1-5, 8 또는 전체 분할 all):",
                ["pdf_password_title"] = "PDF 비밀번호 입력",
                ["pdf_password_prompt"] = "「{0}」 파일이 비밀번호로 보호되어 있습니다. 비밀번호를 입력하십시오:",
                ["pdf_password_retry"] = "비밀번호가 잘못되었습니다. 다시 입력하십시오:「{0}」",
                ["error_pdf_password_quiet"] = "비밀번호가 잘못되었거나 누락되었습니다 (조용한 모드에서는 비밀번호를 입력할 수 없습니다).",
                ["pdf_not_encrypted"] = "이 파일은 암호화되어 있지 않아 비밀번호를 제거할 필요가 없습니다.",
                ["dialog_ok"] = "확인",
                ["dialog_cancel"] = "취소"
            }
        };

        /// <summary>Maps a language code (or the current UI culture when empty) to one of the
        /// supported language keys, defaulting to Traditional Chinese.</summary>
        public static string NormalizeLanguageCode(string langCode)
        {
            if (string.IsNullOrEmpty(langCode))
            {
                langCode = System.Globalization.CultureInfo.CurrentUICulture.Name;
            }

            if (langCode.StartsWith("en", StringComparison.OrdinalIgnoreCase)) return LangEn;
            if (langCode.Equals(LangCn, StringComparison.OrdinalIgnoreCase)) return LangCn;
            if (langCode.StartsWith("ja", StringComparison.OrdinalIgnoreCase)) return LangJa;
            if (langCode.StartsWith("ko", StringComparison.OrdinalIgnoreCase)) return LangKo;
            if (langCode.StartsWith("zh", StringComparison.OrdinalIgnoreCase)) return LangTw;

            return LangTw;
        }

        /// <summary>Translates a resource key into the target language, falling back to
        /// Traditional Chinese and finally to the key itself.</summary>
        public static string T(string key, string langCode)
        {
            string targetKey = NormalizeLanguageCode(langCode);

            // Try looking up the logical ID in the target language
            if (Translations.TryGetValue(targetKey, out var dict) && dict.TryGetValue(key, out var translated))
            {
                return translated;
            }

            // Fallback: If not found in target language, try Traditional Chinese (zh-TW)
            if (targetKey != LangTw && Translations.TryGetValue(LangTw, out var twDict) && twDict.TryGetValue(key, out var twTranslated))
            {
                return twTranslated;
            }

            // Fallback: If not found anywhere, return the key as-is
            return key;
        }

        static Localization()
        {
            RegisterCompressionTranslations();
            RegisterFluentDashboardTranslations();
        }

        private static void RegisterCompressionTranslations()
        {
            // Register cmd_compress_pdf
            Translations[LangTw][KeyCmdCompressPdf] = "壓縮 PDF";
            Translations[LangCn][KeyCmdCompressPdf] = "压缩 PDF";
            Translations[LangEn][KeyCmdCompressPdf] = "Compress PDF";
            Translations[LangJa][KeyCmdCompressPdf] = "PDF 圧縮";
            Translations[LangKo][KeyCmdCompressPdf] = "PDF 압축";

            var data = new[]
            {
                new[] { LangTw, "PDF 壓縮設定", "自訂 PDF 壓縮的字型、圖片解析度與向量結構簡化方式", "圖片壓縮", "其他優化", "目標解析度 (DPI)", "JPEG 質量", "剝離嵌入字型以極致壓縮", "簡化向量圖形與排版結構", "← 體積最小", "質量最高 →", "極小", "小檔", "標準", "高品質" },
                new[] { LangCn, "PDF 压缩设置", "自定义 PDF 压缩的字体、图片分辨率与矢量结构简化方式", "图片压缩", "其他优化", "目标分辨率 (DPI)", "JPEG 质量", "剥离嵌入字体以极致压缩", "简化矢量图形与排版结构", "← 体积最小", "质量最高 →", "极小", "小档", "标准", "高质量" },
                new[] { LangEn, "PDF Compression Settings", "Customize font embedding, image resolution, and vector structure options", "Image Compression", "Other Optimization", "Target DPI", "JPEG Quality", "Strip Embedded Fonts for Maximum Compression", "Minify Vector Graphics & Content Streams", "← Smaller", "Higher Quality →", "Min", "Small", "Std", "High" },
                new[] { LangJa, "PDF 圧縮設定", "フォントの埋め込み、画像の解像度、ベクター構造の最適化をカスタマイズします", "画像圧縮", "その他の最適化", "目標解像度 (DPI)", "JPEG 画質", "フォントの埋め込みを解除して極限圧縮", "ベクターグラフィックスとコンテンツストリームの簡素化", "← 最小サイズ", "最高品質 →", "最小", "小", "標準", "高品質" },
                new[] { LangKo, "PDF 압축 설정", "글꼴 포함, 이미지 해상도 및 벡터 구조 최적화 옵션을 사용자 정의합니다", "이미지 압축", "기타 최적화", "대상 해상도 (DPI)", "JPEG 화질", "글꼴 포함을 해제하여 극대 압축", "벡터 그래픽 및 콘텐츠 스트림 단순화", "← 최소 크기", "최고 품질 →", "최소", "소형", "표준", "고품질" }
            };

            foreach (var row in data)
            {
                AddCompressDetails(row[0], row);
            }
        }

        private static void AddCompressDetails(string lang, string[] values)
        {
            var dict = Translations[lang];
            dict["setting_pdf_compress_title"] = values[1];
            dict["setting_pdf_compress_desc"] = values[2];
            dict["setting_pdf_compress_group_image"] = values[3];
            dict["setting_pdf_compress_group_other"] = values[4];
            dict["setting_pdf_compress_dpi"] = values[5];
            dict["setting_pdf_compress_quality"] = values[6];
            dict["setting_pdf_compress_strip_fonts"] = values[7];
            dict["setting_pdf_compress_minify_content"] = values[8];
            dict["setting_pdf_compress_smaller"] = values[9];
            dict["setting_pdf_compress_higher"] = values[10];
            dict["setting_pdf_compress_level_min"] = values[11];
            dict["setting_pdf_compress_level_small"] = values[12];
            dict["setting_pdf_compress_level_std"] = values[13];
            dict["setting_pdf_compress_level_high"] = values[14];
        }

        private static void RegisterFluentDashboardTranslations()
        {
            var data = new (string Key, string Tw, string Cn, string En, string Ja, string Ko)[]
            {
                ("fluent_nav_overview", "總覽", "总览", "Overview", "概要", "개요"),
                ("fluent_nav_convert", "轉檔", "转换", "Convert", "変換", "변환"),
                ("fluent_nav_history", "歷史", "历史", "History", "履歴", "기록"),
                ("fluent_nav_settings", "設定", "设置", "Settings", "設定", "설정"),
                ("fluent_nav_about", "關於", "关于", "About", "情報", "정보"),
                ("fluent_overview_title", "轉換檔案", "转换文件", "Convert files", "ファイルを変換", "파일 변환"),
                ("fluent_overview_subtitle", "PDF、Office 與圖片工具集中在同一個工作區。", "PDF、Office 与图片工具集中在同一个工作区。", "PDF, Office, and image tools in one workspace.", "PDF、Office、画像ツールを 1 つの作業領域に集約。", "PDF, Office, 이미지 도구를 한 작업 공간에서 사용합니다."),
                ("fluent_choose_files", "選擇檔案", "选择文件", "Choose files", "ファイルを選択", "파일 선택"),
                ("fluent_recent_jobs", "近期作業", "近期作业", "Recent jobs", "最近のジョブ", "최근 작업"),
                ("fluent_recent_activity", "近期活動", "近期活动", "Recent activity", "最近の操作", "최근 활동"),
                ("fluent_no_history", "尚無轉換紀錄。", "暂无转换记录。", "No conversion history yet.", "変換履歴はまだありません。", "변환 기록이 없습니다."),
                ("fluent_activity_summary", "活動摘要", "活动摘要", "Activity summary", "操作サマリー", "활동 요약"),
                ("fluent_total", "總計", "总计", "Total", "合計", "전체"),
                ("fluent_success", "成功", "成功", "OK", "成功", "성공"),
                ("fluent_failed", "失敗", "失败", "Fail", "失敗", "실패"),
                ("fluent_tools", "PDF 與 Office 工具", "PDF 与 Office 工具", "PDF and Office tools", "PDF と Office ツール", "PDF 및 Office 도구"),
                ("fluent_explorer_menu", "檔案總管選單", "文件资源管理器菜单", "Explorer menu", "Explorer メニュー", "Explorer 메뉴"),
                ("fluent_available", "可用", "可用", "Available", "利用可能", "사용 가능"),
                ("fluent_pdf_desc", "合併、壓縮、翻譯、解密。", "合并、压缩、翻译、解密。", "Merge, compress, translate, decrypt.", "結合、圧縮、翻訳、復号。", "병합, 압축, 번역, 암호 해제."),
                ("fluent_office_desc", "Word、Excel、PowerPoint 轉 PDF。", "Word、Excel、PowerPoint 转 PDF。", "Word, Excel, PowerPoint to PDF.", "Word、Excel、PowerPoint を PDF へ。", "Word, Excel, PowerPoint를 PDF로 변환."),
                ("fluent_images_desc", "建立 PDF、合併、拼接。", "创建 PDF、合并、拼接。", "Create PDFs, merge, stitch.", "PDF 作成、結合、連結。", "PDF 생성, 병합, 이어붙이기."),
                ("fluent_drop_title", "拖放檔案到這裡", "拖放文件到这里", "Drop files here", "ここにファイルをドロップ", "여기에 파일 놓기"),
                ("fluent_drop_browse", "點擊此區域選取檔案", "点击此区域选择文件", "Click this area to browse", "この領域をクリックして選択", "이 영역을 클릭해 선택"),
                ("fluent_drop_types", "PDF、Office 文件與圖片", "PDF、Office 文档与图片", "PDF, Office documents, and images", "PDF、Office 文書、画像", "PDF, Office 문서, 이미지"),
                ("fluent_selected_files", "已選取檔案", "已选择文件", "Selected files", "選択したファイル", "선택한 파일"),
                ("fluent_selected_files_desc", "檔案會依照目前命令驗證。", "文件会按照当前命令验证。", "Files are validated against the selected command.", "ファイルは選択中のコマンドで検証されます。", "선택한 명령에 맞게 파일을 확인합니다."),
                ("fluent_clear", "清除", "清除", "Clear", "クリア", "지우기"),
                ("fluent_no_files", "未選取檔案", "未选择文件", "No files selected", "ファイル未選択", "선택한 파일 없음"),
                ("fluent_command", "命令", "命令", "Command", "コマンド", "명령"),
                ("fluent_choose_command", "選擇命令", "选择命令", "Choose a command", "コマンドを選択", "명령 선택"),
                ("fluent_selected_command", "已選擇：{0}", "已选择：{0}", "Selected: {0}", "選択中: {0}", "선택됨: {0}"),
                ("fluent_run", "執行", "运行", "Run", "実行", "실행"),
                ("fluent_start", "開始轉換", "开始转换", "Start conversion", "変換開始", "변환 시작"),
                ("fluent_cancel", "取消", "取消", "Cancel", "キャンセル", "취소"),
                ("fluent_ready", "準備就緒", "准备就绪", "Ready", "準備完了", "준비됨"),
                ("fluent_file_count", "個檔案", "个文件", "file(s)", "件", "개 파일"),
                ("fluent_select_history", "選取一筆歷史紀錄", "选择一条历史记录", "Select a history item", "履歴項目を選択", "기록 항목 선택"),
                ("fluent_files", "檔案", "文件", "Files", "ファイル", "파일"),
                ("fluent_elapsed", "耗時", "耗时", "Elapsed", "経過時間", "소요 시간"),
                ("fluent_result", "結果", "结果", "Result", "結果", "결과"),
                ("fluent_input_paths", "輸入路徑", "输入路径", "Input paths", "入力パス", "입력 경로"),
                ("fluent_output_paths", "輸出路徑", "输出路径", "Output paths", "出力パス", "출력 경로"),
                ("fluent_error_message", "錯誤訊息", "错误消息", "Error message", "エラーメッセージ", "오류 메시지"),
                ("fluent_settings_subtitle", "使用者介面與檔案總管命令的預設值", "界面与文件资源管理器命令的默认值", "Defaults used by the dashboard and Explorer commands", "ダッシュボードと Explorer コマンドの既定値", "대시보드와 Explorer 명령의 기본값"),
                ("fluent_output_dir", "輸出資料夾", "输出文件夹", "Output directory", "出力フォルダー", "출력 폴더"),
                ("fluent_output_dir_desc", "轉換後檔案的儲存位置", "转换后文件的保存位置", "Where converted files are saved", "変換後ファイルの保存先", "변환된 파일 저장 위치"),
                ("fluent_output_source", "與來源相同", "与来源相同", "Same as source", "元と同じ", "원본과 같음"),
                ("fluent_desktop", "桌面", "桌面", "Desktop", "デスクトップ", "바탕 화면"),
                ("fluent_downloads", "下載", "下载", "Downloads", "ダウンロード", "다운로드"),
                ("fluent_custom", "自訂...", "自定义...", "Custom...", "カスタム...", "사용자 지정..."),
                ("fluent_office_engine", "Office 引擎", "Office 引擎", "Office engine", "Office エンジン", "Office 엔진"),
                ("fluent_office_engine_desc", "Office 轉檔使用的引擎", "Office 转换使用的引擎", "Engine used for Office conversion", "Office 変換に使うエンジン", "Office 변환에 사용할 엔진"),
                ("fluent_auto", "自動", "自动", "Auto", "自動", "자동"),
                ("fluent_default_language", "預設語言", "默认语言", "Default language", "既定の言語", "기본 언어"),
                ("fluent_default_language_desc", "用於介面、檔案總管命令與處理訊息。", "用于界面、文件资源管理器命令与处理消息。", "Used by the interface, Explorer commands, and processor messages.", "UI、Explorer コマンド、処理メッセージに使用します。", "UI, Explorer 명령, 처리 메시지에 사용합니다."),
                ("fluent_pdf_target", "PDF 翻譯目標", "PDF 翻译目标", "PDF translation target", "PDF 翻訳先", "PDF 번역 대상"),
                ("fluent_behavior", "行為", "行为", "Behavior", "動作", "동작"),
                ("fluent_quiet_mode", "靜默模式", "静默模式", "Quiet mode", "静音モード", "무음 모드"),
                ("fluent_quiet_mode_desc", "檔案總管命令預設使用；此視窗仍會顯示。", "文件资源管理器命令默认使用；此窗口仍会显示。", "Default for Explorer commands; this dashboard still stays visible.", "Explorer コマンドの既定。この画面は表示されます。", "Explorer 명령의 기본값입니다. 이 창은 계속 표시됩니다."),
                ("fluent_notifications", "通知", "通知", "Notifications", "通知", "알림"),
                ("fluent_notifications_desc", "轉換完成時顯示通知", "转换完成时显示通知", "Show toast when conversion completes", "変換完了時に通知を表示", "변환 완료 시 알림 표시"),
                ("fluent_pdf_compression", "PDF 壓縮", "PDF 压缩", "PDF compression", "PDF 圧縮", "PDF 압축"),
                ("fluent_strip_fonts", "移除嵌入字型", "移除嵌入字体", "Strip embedded fonts", "埋め込みフォントを削除", "포함 글꼴 제거"),
                ("fluent_minify_content", "最佳化 PDF 結構", "优化 PDF 结构", "Optimize PDF structure", "PDF 構造を最適化", "PDF 구조 최적화"),
                ("fluent_about_desc", "Clickra 是 Windows 上快速、輕量的檔案轉換工作區。", "Clickra 是 Windows 上快速、轻量的文件转换工作区。", "A fast, lightweight file conversion workspace for Windows.", "Windows 向けの高速で軽量なファイル変換ワークスペース。", "Windows용 빠르고 가벼운 파일 변환 작업 공간입니다."),
                ("fluent_github", "在 GitHub 檢視", "在 GitHub 查看", "View on GitHub", "GitHub で表示", "GitHub에서 보기"),
                ("fluent_platform", "平台", "平台", "Platform", "プラットフォーム", "플랫폼"),
                ("fluent_app_model", "應用程式模型", "应用模型", "App model", "アプリモデル", "앱 모델"),
                ("fluent_toast_done_title", "Clickra 轉換完成", "Clickra 转换完成", "Clickra conversion completed", "Clickra 変換完了", "Clickra 변환 완료"),
                ("fluent_toast_done_body", "{0} 已完成，共 {1} 個檔案。", "{0} 已完成，共 {1} 个文件。", "{0} finished for {1} file(s).", "{0} が完了しました。{1} 件。", "{0} 완료, {1}개 파일."),
                ("fluent_toast_canceled_title", "Clickra 轉換已取消", "Clickra 转换已取消", "Clickra conversion canceled", "Clickra 変換キャンセル", "Clickra 변환 취소"),
                ("fluent_toast_canceled_body", "{0} 已取消。", "{0} 已取消。", "{0} was canceled.", "{0} はキャンセルされました。", "{0} 취소됨."),
                ("fluent_toast_failed_title", "Clickra 轉換失敗", "Clickra 转换失败", "Clickra conversion failed", "Clickra 変換失敗", "Clickra 변환 실패"),
                ("fluent_validate_min_files", "{0} 至少需要 {1} 個檔案。", "{0} 至少需要 {1} 个文件。", "{0} needs at least {1} file(s).", "{0} には少なくとも {1} 件のファイルが必要です。", "{0}에는 최소 {1}개 파일이 필요합니다."),
                ("fluent_validate_bad_ext", "{0} 不適用於 {1}。", "{0} 不适用于 {1}。", "{0} is not valid for {1}.", "{0} は {1} に使用できません。", "{0}은(는) {1}에 사용할 수 없습니다."),
                ("fluent_progress_starting", "正在開始...", "正在开始...", "Starting...", "開始中...", "시작 중..."),
                ("fluent_progress_completed", "已完成。", "已完成。", "Completed.", "完了しました。", "완료됨."),
                ("fluent_progress_canceled", "已取消。", "已取消。", "Canceled.", "キャンセルしました。", "취소됨."),
                ("fluent_progress_failed", "失敗：{0}", "失败：{0}", "Failed: {0}", "失敗: {0}", "실패: {0}"),
                ("fluent_progress_running_title", "正在{0}", "正在{0}", "{0} in progress", "{0} を実行中", "{0} 진행 중"),
                ("fluent_progress_preparing", "準備中", "准备中", "Preparing", "準備中", "준비 중"),
                ("fluent_progress_output", "輸出：", "输出：", "Output: ", "出力: ", "출력: "),
                ("fluent_progress_waiting", "請稍候，正在背景處理中...", "请稍候，正在后台处理中...", "Please wait. Processing in the background...", "お待ちください。バックグラウンドで処理しています...", "잠시만 기다려 주세요. 백그라운드에서 처리 중입니다..."),
                ("fluent_progress_running", "正在執行作業...", "正在执行作业...", "Working...", "処理を実行中...", "작업 실행 중..."),
                ("fluent_progress_processing", "正在處理...", "正在处理...", "Processing...", "処理中...", "처리 중..."),
                ("fluent_progress_done_title", "處理完成", "处理完成", "Completed", "処理完了", "처리 완료"),
                ("fluent_progress_failed_title", "處理未完成", "处理未完成", "Not completed", "未完了", "완료되지 않음"),
                ("fluent_progress_done_footer", "處理完成，可以開啟輸出資料夾。", "处理完成，可以打开输出文件夹。", "Completed. You can open the output folder.", "完了しました。出力フォルダーを開けます。", "완료되었습니다. 출력 폴더를 열 수 있습니다."),
                ("fluent_progress_failed_footer", "請檢查訊息後關閉視窗。", "请检查消息后关闭窗口。", "Check the message, then close this window.", "メッセージを確認してから閉じてください。", "메시지를 확인한 후 창을 닫아 주세요."),
                ("fluent_progress_open_folder", "開啟資料夾", "打开文件夹", "Open folder", "フォルダーを開く", "폴더 열기"),
                ("fluent_progress_close", "關閉", "关闭", "Close", "閉じる", "닫기"),
                ("fluent_progress_invalid_command", "無效的轉換命令。", "无效的转换命令。", "Invalid conversion command.", "無効な変換コマンドです。", "잘못된 변환 명령입니다."),
                ("fluent_progress_file_not_found", "找不到可轉換的檔案。", "找不到可转换的文件。", "No convertible files were found.", "変換できるファイルが見つかりません。", "변환할 파일을 찾을 수 없습니다."),
                ("fluent_progress_multiple_files", "{0} 等 {1} 個檔案", "{0} 等 {1} 个文件", "{0} and {1} files", "{0} ほか {1} 件", "{0} 외 {1}개 파일"),
                ("fluent_pdf_password", "PDF 密碼", "PDF 密码", "PDF password", "PDF パスワード", "PDF 암호"),
                ("fluent_pdf_password_placeholder", "輸入 PDF 密碼", "输入 PDF 密码", "Enter PDF password", "PDF パスワードを入力", "PDF 암호 입력"),
                ("fluent_ok", "確定", "确定", "OK", "OK", "확인"),
                ("fluent_office", "Office", "Office", "Office", "Office", "Office"),
                ("fluent_images", "圖片", "图片", "Images", "画像", "이미지"),
                ("fluent_history_subtitle", "近期轉換結果", "近期转换结果", "Recent conversion results", "最近の変換結果", "최근 변환 결과"),
                ("status_office_starting", "正在啟動 {0} 引擎 ({1}/{2})...", "正在启动 {0} 引擎 ({1}/{2})...", "Starting {0} engine ({1}/{2})...", "{0} エンジンを起動中 ({1}/{2})...", "{0} 엔진 시작 중 ({1}/{2})..."),
                ("status_office_reading", "正在讀取文件：{0}...", "正在读取文档：{0}...", "Reading document: {0}...", "文書を読み込み中: {0}...", "문서 읽는 중: {0}..."),
                ("status_office_exporting", "正在匯出 PDF：{0}...", "正在导出 PDF：{0}...", "Exporting PDF: {0}...", "PDF を書き出し中: {0}...", "PDF 내보내는 중: {0}..."),
                ("status_office_completed", "已完成轉換：{0}", "已完成转换：{0}", "Conversion completed: {0}", "変換完了: {0}", "변환 완료: {0}"),
                ("status_office_converting", "正在轉換 {0}：{1}...", "正在转换 {0}：{1}...", "Converting {0}: {1}...", "{0} を変換中: {1}...", "{0} 변환 중: {1}..."),
                ("error_office_unsupported", "不支援的 Office 應用程式：{0}。", "不支持的 Office 应用程序：{0}。", "Office application {0} is not supported.", "Office アプリ {0} はサポートされていません。", "Office 앱 {0}은(는) 지원되지 않습니다."),
                ("error_office_output_missing", "{0} 轉換失敗：未建立輸出 PDF。", "{0} 转换失败：未创建输出 PDF。", "{0} conversion failed: output PDF file was not created.", "{0} 変換失敗: 出力 PDF が作成されませんでした。", "{0} 변환 실패: 출력 PDF 파일이 생성되지 않았습니다."),
                ("error_office_powershell_start", "Microsoft {0} 轉換失敗：無法啟動 PowerShell。", "Microsoft {0} 转换失败：无法启动 PowerShell。", "Microsoft {0} conversion failed: unable to start PowerShell.", "Microsoft {0} 変換失敗: PowerShell を起動できません。", "Microsoft {0} 변환 실패: PowerShell을 시작할 수 없습니다."),
                ("error_office_timeout", "Microsoft {0} 轉換超過 2 分鐘。請改用其他 Office 引擎，或手動匯出此檔案。", "Microsoft {0} 转换超过 2 分钟。请改用其他 Office 引擎，或手动导出此文件。", "Microsoft {0} conversion timed out after 2 minutes. Try another Office engine or export this file manually.", "Microsoft {0} 変換が 2 分でタイムアウトしました。別の Office エンジンを使うか手動で書き出してください。", "Microsoft {0} 변환이 2분 후 시간 초과되었습니다. 다른 Office 엔진을 사용하거나 수동으로 내보내세요."),
                ("error_office_not_installed", "尚未安裝 Microsoft {0}。此功能需要系統中已安裝 Microsoft {0}。", "尚未安装 Microsoft {0}。此功能需要系统中已安装 Microsoft {0}。", "Microsoft {0} is not installed. This feature requires Microsoft {0} to be installed on your system.", "Microsoft {0} がインストールされていません。この機能には Microsoft {0} が必要です。", "Microsoft {0}이(가) 설치되어 있지 않습니다. 이 기능에는 Microsoft {0}이(가) 필요합니다."),
                ("error_office_failed", "{0} 轉換失敗：{1}", "{0} 转换失败：{1}", "{0} conversion failed: {1}", "{0} 変換失敗: {1}", "{0} 변환 실패: {1}"),
                ("error_office_exit_code", "{0} 轉換失敗，結束碼 {1}。", "{0} 转换失败，退出码 {1}。", "{0} conversion failed with exit code {1}.", "{0} 変換失敗、終了コード {1}。", "{0} 변환 실패, 종료 코드 {1}."),
                ("error_libreoffice_unsupported", "LibreOffice 不支援轉換 {0}。", "LibreOffice 不支持转换 {0}。", "LibreOffice conversion does not support {0}.", "LibreOffice は {0} 変換をサポートしていません。", "LibreOffice는 {0} 변환을 지원하지 않습니다."),
                ("error_libreoffice_start", "LibreOffice 轉換失敗：無法啟動程序。", "LibreOffice 转换失败：无法启动进程。", "LibreOffice conversion failed: unable to start process.", "LibreOffice 変換失敗: プロセスを起動できません。", "LibreOffice 변환 실패: 프로세스를 시작할 수 없습니다."),
                ("error_libreoffice_timeout", "LibreOffice 轉換超過 2 分鐘。請改用 Microsoft Office 或自動引擎處理此檔案。", "LibreOffice 转换超过 2 分钟。请改用 Microsoft Office 或自动引擎处理此文件。", "LibreOffice conversion timed out after 2 minutes. Try Microsoft Office or Auto engine for this file.", "LibreOffice 変換が 2 分でタイムアウトしました。Microsoft Office または自動エンジンを試してください。", "LibreOffice 변환이 2분 후 시간 초과되었습니다. Microsoft Office 또는 자동 엔진을 사용해 보세요."),
                ("error_libreoffice_exit_code", "LibreOffice 轉換失敗，結束碼 {0} ({1})：{2}", "LibreOffice 转换失败，退出码 {0} ({1})：{2}", "LibreOffice conversion failed with exit code {0} ({1}): {2}", "LibreOffice 変換失敗、終了コード {0} ({1}): {2}", "LibreOffice 변환 실패, 종료 코드 {0} ({1}): {2}"),
                ("error_libreoffice_output_missing", "LibreOffice 轉換失敗：未建立輸出 PDF。{0}", "LibreOffice 转换失败：未创建输出 PDF。{0}", "LibreOffice conversion failed: output PDF file was not created. {0}", "LibreOffice 変換失敗: 出力 PDF が作成されませんでした。{0}", "LibreOffice 변환 실패: 출력 PDF 파일이 생성되지 않았습니다. {0}"),
                ("pdf_progress_analyzing", "正在分析 PDF 版面結構與公式...", "正在分析 PDF 版面结构与公式...", "Analyzing PDF layout and formulas...", "PDF レイアウトと数式を解析中...", "PDF 레이아웃과 수식 분석 중..."),
                ("pdf_progress_translating", "正在翻譯文本內容...", "正在翻译文本内容...", "Translating text content...", "テキストを翻訳中...", "텍스트 내용 번역 중..."),
                ("pdf_progress_translating_page", "正在翻譯第 {0}/{1} 頁...", "正在翻译第 {0}/{1} 页...", "Translating page {0}/{1}...", "{0}/{1} ページを翻訳中...", "{0}/{1} 페이지 번역 중..."),
                ("pdf_progress_translating_batch", "正在翻譯第 {0}/{1} 頁，批次 {2}/{3}（段落 {4}-{5}/{6}）...", "正在翻译第 {0}/{1} 页，批次 {2}/{3}（段落 {4}-{5}/{6}）...", "Translating page {0}/{1}, batch {2}/{3} (paragraphs {4}-{5}/{6})...", "{0}/{1} ページ、バッチ {2}/{3} を翻訳中（段落 {4}-{5}/{6}）...", "{0}/{1} 페이지, 배치 {2}/{3} 번역 중(문단 {4}-{5}/{6})..."),
                ("pdf_progress_rebuilding", "正在重建 PDF 版面與公式...", "正在重建 PDF 版面与公式...", "Rebuilding PDF layout and formulas...", "PDF レイアウトと数式を再構築中...", "PDF 레이아웃과 수식 재구성 중..."),
                ("pdf_progress_saving", "正在儲存翻譯後的檔案...", "正在保存翻译后的文件...", "Saving translated file...", "翻訳済みファイルを保存中...", "번역된 파일 저장 중..."),
                ("pdf_error_deadline", "PDF 翻譯超過 10 分鐘文件時限。", "PDF 翻译超过 10 分钟文档时限。", "PDF translation exceeded the 10-minute document deadline.", "PDF 翻訳が 10 分の文書制限を超えました。", "PDF 번역이 10분 문서 제한 시간을 초과했습니다."),
                ("pdf_error_translation_failed_page", "PDF 第 {0} 頁翻譯失敗；自動批次拆分與供應商備援已用盡。", "PDF 第 {0} 页翻译失败；自动批次拆分与供应商备用已用尽。", "PDF translation failed on page {0}; automatic batch splitting and provider fallback were exhausted.", "PDF {0} ページの翻訳に失敗しました。自動バッチ分割とプロバイダー代替を使い切りました。", "PDF {0}페이지 번역 실패: 자동 배치 분할과 공급자 대체를 모두 사용했습니다."),
                ("pdf_error_mismatched_batch", "批次翻譯結果數量不一致。", "批次翻译结果数量不一致。", "Mismatched batch translation results count.", "バッチ翻訳結果数が一致しません。", "배치 번역 결과 수가 일치하지 않습니다."),
                ("pdf_error_provider_empty", "翻譯供應商回傳空白結果。", "翻译供应商返回空白结果。", "Translator returned an empty result.", "翻訳プロバイダーが空の結果を返しました。", "번역 공급자가 빈 결과를 반환했습니다."),
                ("pdf_error_unable_paragraph", "第 {0} 頁段落在批次拆分與供應商備援後仍無法翻譯。", "第 {0} 页段落在批次拆分与供应商备用后仍无法翻译。", "Unable to translate page {0} paragraph after batch splitting and provider fallback.", "{0} ページの段落をバッチ分割と代替後も翻訳できません。", "{0}페이지 문단을 배치 분할과 공급자 대체 후에도 번역할 수 없습니다."),
                ("pdf_error_provider_timeout", "翻譯供應商鏈呼叫超過 {0} 秒。", "翻译供应商链调用超过 {0} 秒。", "Translation provider chain call exceeded {0}s.", "翻訳プロバイダー呼び出しが {0} 秒を超えました。", "번역 공급자 호출이 {0}초를 초과했습니다.")
            };

            foreach (var item in data)
            {
                Translations[LangTw][item.Key] = item.Tw;
                Translations[LangCn][item.Key] = item.Cn;
                Translations[LangEn][item.Key] = item.En;
                Translations[LangJa][item.Key] = item.Ja;
                Translations[LangKo][item.Key] = item.Ko;
            }
        }
    }
}
